### ISSUE TITLE
Multiple Main Weapons

### ISSUE THREAD

**Issue by Keridos** [EpochModTeam/DayZ-Epoch#1021]
In the current vanilla DayZ Mod it is possible to have a Pistol, a melee and a ranged weapon at once. Something like Makarov, Crowbar and an M24 and you can SWITCH between each one. So you can actually put your M24 on your back and start swinging the Crowbar.
I started trying out Epoch now and noticed that that is currently not possible within it. Someone told me Arma 2 had restrictions there, but why does that work in the vanilla mod then?
Is it possible to import that behaviour into Epoch aswell so that Epoch players can use it aswell?

**Comment by ebaydayz** [comment]
1.8.7 weapon switching is now included for 1.0.6
