### ISSUE TITLE
Move Player Humanity from character_data to player_data

### ISSUE THREAD

**Issue by Skaronator** [EpochModTeam/DayZ-Epoch#1025]
Would fix #817

**Comment by ebayShopper** [comment]
As mentioned in the #817 this is only an issue if the player logs off dead and a SQL event is added to delete dead character_data entries.

We do not have an event that does that by default:
https://github.com/EpochModTeam/DayZ-Epoch/blob/master/Server%20Files/SQL/add_recommended_mysql_events.sql

But if you want to add one the issue can be easily avoided by just adding an interval. Like:
```sql
DELETE FROM Character_DATA WHERE Alive=0 AND LastLogin < NOW() - INTERVAL 60 DAY
```
If the player hasn't logged in for that long they should assume both their character and humanity have been wiped.
