### ISSUE TITLE
Lock vehicle while in vehicle

### ISSUE THREAD

**Issue by pj999** [EpochModTeam/DayZ-Epoch#1103]
It would be great if you could lock vehicle while you are in the vehicle if you have the right keys.
I know you can get killed...but for the sake of servers with safe zones.

**Comment by ebaydayz** [comment]
Added, tested and confirmed working: https://github.com/EpochModTeam/DayZ-Epoch/commit/03353b94831ce1acdeea60392a8d8d27d38be04c

I don't think the body getting stuck in the locked car is too big of a deal. There are always hotwire kits or key copies for that. I know on Arma 3 sometimes you need to get in the seat the body is in before it falls out.
