### ISSUE TITLE
Add Quantity to trader

### ISSUE THREAD

**Issue by Fank** [EpochModTeam/DayZ-Epoch#1117]
Add a quantity option to the trader to sell multiple item at once.
For example what is possible with one trade:
1x weapon
5x-10x magazines

Add option to sell item in Backpack, like you got 5 ak's, one in inventory 4 in backpack.
You select quantity of 5 and it will sell 0-5 possible ak's found in inventory/backpack.
That will help selling a huge amount of toolbelt items.

**Comment by icomrade** [comment]
fixed with advanced trading in 1.0.6
