### ISSUE TITLE
Support for Headless client

### ISSUE THREAD

**Issue by Fank** [EpochModTeam/DayZ-Epoch#1119]
Maybe add some function for spawning units on a HC if there is one connected.
For example:
https://github.com/Fankserver/ArmA-HeadlessClient

Here a example of my project and how to use:
https://github.com/Fankserver/ArmA-HeadlessClient/blob/master/server/exampleUnitSpawn.md

I think this will improve the performance of the servers because AI can be handled by a Headless client

Another idea is to tell the server to animals trough the HC

**Comment by AirwavesMan** [comment]
Epoch comes without a mission system. Headless clients are limited useful in epoch and arma 2 and only really needed if bigger AI numbers are spawned on the server.
