### ISSUE TITLE
Knock-out timer not allowing players to get back up

### ISSUE THREAD

**Issue by IjoreanGrey** [EpochModTeam/DayZ-Epoch#1145]
When falling down fatigued from large amount of weight you are unable to get back up unless you drop to the lobby.

**Comment by ebaydayz** [comment]
I changed it to break legs instead of knock out. Fn_unconscious is very glitchy, calls RE, PV and several network setVariables, so best to use it as little as possible.

The break legs sound is also better suited to this. It is silly to use the same dramatic scream you make when being eaten by zombies. 

https://github.com/EpochModTeam/DayZ-Epoch/commit/6bee7a17f03ff998ad99d3f9f795d0092d63d300

**Comment by icomrade** [comment]
Personally I think the leg breaking thing is a bit too much. Why not just use player forceWalk True; https://community.bistudio.com/wiki/forceWalk to give a Fallout style overburdened effect?

**Comment by ebaydayz** [comment]
@icomrade - That was my initial thought too. I tested both forceWalk and forceSpeed but it looks like they only work on AI. I even tried looping them every second, but they don't seem to have any affect on my player.

The only other way I can think of forcing a slow walking speed is to loop a player playAction "SlowF"; like autoRun does for "FastF". I will test detecting the player speed and forcing a loop of that if they are moving. Some Arma 3 mods do that with fatigue and I think it is a decent solution.

**Comment by icomrade** [comment]
This code works for limiting speed, the player still plays the sprint animation but is limited in speed. I haven't tested with the R3F variables I used in the while loop, just did a bit in the editor.

```
[] spawn {
	_i = 0;
	_speedLimit = 6.8; //Speed while slow walking is ~6.7
	player forceWalk true;
	while {R3F_TIRED_Accumulator  > R3F_TIRED_BLACKOUT_LEVEL} do {
		if (vehicle player == player) then {
			_vel = velocity player;
			_speed = speed player;
			_velX = _vel select 0;
			_velY = _vel select 1;
			if (_speed > _speedLimit) then {
				player setvelocity [-_velX,-_velY,_vel select 2];
			};
		};
		sleep 0.001;
	};
};
```

**Comment by ebaydayz** [comment]
Looks a little awkward, but still better than knockout or broken legs I think. Committed, thanks:
https://github.com/EpochModTeam/DayZ-Epoch/commit/0511dcdb421fee670de608fc19c0b9a5b80513e7
