### ISSUE TITLE
UI Option To Redeploy Plot Pole Markers

### ISSUE THREAD

**Issue by MjrStryker** [EpochModTeam/DayZ-Epoch#1177]
I believe it would be a benefit to those building bases if there was a UI option to redeploy the markers you get when you first deploy your plot pole. Currently the markers disappear on relog or server restart making it difficult to gauge how much space you have remaining to place items in. The UI option could be available to all players but only valid for those with build access (Owner and tagged as friendly) so that non-friendlies cannot easily see the edge of your build radius.

**Comment by Bruce-LXXVI** [comment]
This is implemented with plotManagement (PR #1686 ). But if @RimBlock and the other contributors to "Plot for Life" aswell as to "Dayz-Epoch" are ok with it, I'm happy to create another pull request to include P4L in the core.

**Comment by Windmolders** [comment]
I can give you a written permission from him. I'll look it up and post it here when I get to my PC.

**Comment by Windmolders** [comment]
@Bruce-LXXVI 

http://epochmod.com/forum/topic/32562-dayz-epoch-v106-test-current-bugs-list/

![Screenshot](http://i.imgur.com/cKr7SEn.png)

**Comment by icomrade** [comment]
feature is included with a plot for life that is now part of epoch
