### ISSUE TITLE
Combo lock and Safes/Lockbox crack possibility (1.0.4.2)

### ISSUE THREAD

**Issue by m3nda** [EpochModTeam/DayZ-Epoch#1187]
After typing/setting code on lock/safe you can use ESC button to leave, if code is correct, option to open appear (so you can bypass limitations and speed up safe/lock cracking, combined with macro app its a real threat).

Problem is in dayz_combination and DZE_Lock_Door vars, you need to set a temp var while typing/setting a code (for combo locks i think it is in player_changeCombo), and set this vars only after unlock action or whatever.

Sorry for my english,

Sorry if it was here already, im new to github.

**Comment by onnlinetool** [comment]
Downloaden Knack  Downloaden Knack  Downloaden Knack

http://bit.ly/2oWYzXw

http://bit.ly/2oWYzXw

http://bit.ly/2oWYzXw

http://bit.ly/2oWYzXw

http://bit.ly/2oWYzXw

http://bit.ly/2oWYzXw

http://bit.ly/2oWYzXw

http://bit.ly/2oWYzXw

**Comment by oiad** [comment]
@icomrade @ebayShopper

**Comment by icomrade** [comment]
@onnlinetool  What is this file?

**Comment by oiad** [comment]
I'm guessing it's a spammer.
