### ISSUE TITLE
Suggested DB Enhancement: Update Owner of Plot Pole(s)

### ISSUE THREAD

**Issue by Uro1** [EpochModTeam/DayZ-Epoch#1189]
Database trigger to automatically update CharacterID's on classname 'Plastic_Pole_EP1_DZ'

Would stop players having to deconstruct and rebuild plot-poles to maintain thier bases.

I know death is part of the game, but it's one of those niggly things that bugs me about the plot poles :)

Maybe add it as an optional SQL script?  As I understand some people like having to have to deconstruct/destroy plotpoles to be able to build again ;)

Code:

    DELIMITER ;
    DROP TRIGGER IF EXISTS dayz_epoch.`update_owner`;
    DELIMITER //
    CREATE TRIGGER dayz_epoch.`update_owner`
    AFTER INSERT ON dayz_epoch.character_data
    FOR EACH ROW
    BEGIN
    UPDATE dayz_epoch.object_data SET CharacterID= NEW.CharacterID WHERE CharacterID IN
    (SELECT CharacterID FROM player_login WHERE PlayerUID= NEW.PlayerUID)
    AND Classname = 'Plastic_Pole_EP1_DZ';
    END//
    DELIMITER ;

**Comment by icomrade** [comment]
Should be a non-issue now when using the Plot For Life mod now included with 1.0.6
