### ISSUE TITLE
Plot Pole - Plastic Poles posing a problem

### ISSUE THREAD

**Issue by noxsicarius** [EpochModTeam/DayZ-Epoch#1195]
The plastic poles that spawn when placing a plot pole are causing some problems. These poles are collidable so they make it hard to park vehicles. When landing an air vehicle on them it causes the vehicle to crash because they are solid objects.

Is there a way you can make them non-collidable?

I understand the need for them and they help out in some circumstances, but they cause problems in other circumstances. If these poles were non-collidable there would be no issue with them. The worst part is that they only impede the person tied to the plot pole, all other people are fine. If you are driving by your base while being pursued and you hit one of the poles it will slow you down, but the pursuer will be unaffected.

**Comment by Bruce-LXXVI** [comment]
What about "Plot for life"? It adds an option to show/hide the boundary and it uses road cones.

**Comment by icomrade** [comment]
If I understand the issue correctly this can be closed as it's fixed in 3c27f76c7c7aed932fd1fb5da69b1ff0ec0bfef2
