### ISSUE TITLE
Crafting a sledgehammer with one being in tool slots

### ISSUE THREAD

**Issue by VADemon** [EpochModTeam/DayZ-Epoch#1196]
Epoch 1.0.4.2

When you craft a sledgehammer while already having one in the tool slot then the crafted sledgehammer disappears.

Possible solutions:
* Show a message and cancel the action
* Put the new sledgehammer into the backpack (as done with keys)

**Comment by icomrade** [comment]
should be fixed as part of 1ade44eb
