### ISSUE TITLE
Toggle for damageHandler on aircraft to buildables

### ISSUE THREAD

**Issue by ZNUfisk** [EpochModTeam/DayZ-Epoch#1198]
Description: One common server-destroyer is aircraft kamikaze, some players spend a lot of time to locate or buy aircraft and then crash them into bases to ruin the enjoyment of the player experience, and causing a lot of work for admins to trace who did it, and to try and give back what was lost in work hours, and frustration. Unfortunately the longer it takes after someone has repeatedly crashed airplanes into a base and before it is reported or discovered the more the error is compounded by other players going into the base and taking stuff that aren't placed in vaults.

Faux solution:
The one available solution on the forums right now is some kind of trigger, that works by detecting approaching vehicles at certain heights and velocities. Unfortunately triggers are big resource hogs and the script available is not a very good solution since it makes every plot pole a teleportation station. 

Better solution:
Make a toggle that removes the damageHandler for collisions between buildables and aircraft. That way anyone can fly an aircraft into (for example) a wood door and feels the joy of watching explosions, but not cause the mayhem that normally occurs when such a thing happens.

**Comment by icomrade** [comment]
Now possible in 1.0.6 using DZE_NoVehicleExplosions = true; There will be no explosions from any vehicles using this fix, which is necessary unless someone knows of an explosion type that doesn't damage nearby objects.
