### ISSUE TITLE
Dynamic market

### ISSUE THREAD

**Issue by ZNUfisk** [EpochModTeam/DayZ-Epoch#1204]
Introduce a more living market.

Start by having all market items at 0 stock (configurable by server ofc), and allow for price ranges to be set depending on supply. 

So for example (something like):

If Sa58 ACOG = 0-10 units - sell price = 20 gold / buy price = 10 gold
If Sa58 ACOG = 11-55 units - sell price = 15 gold / buy price = 7 gold
If Sa58 ACOG = 56-255 units - sell price = 10 gold / buy price = 5 gold

**Comment by icomrade** [comment]
SQL traders and subsequently stock is no longer being supported since we are switching to Advanced trading which only supports the higher performance config based traders. As a result we won't be able to implement a stock-based discount.
