### ISSUE TITLE
Changing clothes issue

### ISSUE THREAD

**Issue by mathewjknott** [EpochModTeam/DayZ-Epoch#1210]
I know this has been looked at before and put down to infistar antihack. This however is not the case as to try and get to the bottom of it i have removed the antihack on my local test server and have still had the same issue.

It does not happen all the time so may take a while to happen. I changed clothes about 10 - 15 times and only had problems twice. I dont know what causes it or why its only random.

When it happens, you get a broken leg showing on the HUD and you are dead to look at. In the database you are still shown as being alive. When you log back in you are in the same location with the same gear as before you changed your clothes. Some times your other body is there, some times its not.

Another error that occurred, was the out of area sound (ticking) could be heard and i was shaking. Changing clothes again fixed this issue but it could be related to the previous.

Below is what the server RPT log shows, the first disconnect it when "killed" and the second is after changing clothes a few times and not being "killed". The only line that shows up for when your "killed" to when your not is "10:44:59 "nil player object attempting PV, :["UID","Mathew"]"" so this may be related to the problem.

10:43:37 SetFace error: class CfgFaces.GravesHead_EP1.Facegrover_EP1 not found
10:43:37 Error: Error during SetFace - class CfgFaces.GravesHead_EP1.Facegrover_EP1 not found
10:43:38 "ERROR: server_playerSync: Cannot Sync Player Mathew [26]. Position in debug! [12548,-5866.6,0.00149536]"
10:44:13 "ERROR: server_playerSync: Cannot Sync Player Mathew [26]. Position in debug! [12548,-5866.6,1.52588e-005]"
10:44:36 "ERROR: server_playerSync: Cannot Sync Player Mathew [26]. Position in debug! [12548,-5866.6,1.52588e-005]"
10:44:59 "nil player object attempting PV, :["UID","Mathew"]"
10:44:59 "get: STRING (UID), sent: STRING (UID)"
10:44:59 "DISCONNECT: Mathew (UID) Object: B 1-1-E:1 (Mathew) REMOTE, _characterID: 26 at loc [15260.8,18418.2,0.00144196]"
10:46:12 "ERROR: server_playerSync: Cannot Sync Player Mathew [26]. Position in debug! [12548,-5866.6,1.09799]"
10:46:39 SetFace error: class CfgFaces.GravesHead_EP1.Facegrover_EP1 not found
10:46:39 Error: Error during SetFace - class CfgFaces.GravesHead_EP1.Facegrover_EP1 not found
10:46:53 SetFace error: class CfgFaces.GravesHead_EP1.Facegrover_EP1 not found
10:46:53 Error: Error during SetFace - class CfgFaces.GravesHead_EP1.Facegrover_EP1 not found
10:47:03 SetFace error: class CfgFaces.GravesHead_EP1.Facegrover_EP1 not found
10:47:03 Error: Error during SetFace - class CfgFaces.GravesHead_EP1.Facegrover_EP1 not found
10:47:35 SetFace error: class CfgFaces.GravesHead_EP1.Facegrover_EP1 not found
10:47:35 Error: Error during SetFace - class CfgFaces.GravesHead_EP1.Facegrover_EP1 not found
10:47:58 SetFace error: class CfgFaces.GravesHead_EP1.Facegrover_EP1 not found
10:47:58 Error: Error during SetFace - class CfgFaces.GravesHead_EP1.Facegrover_EP1 not found
10:48:12 SetFace error: class CfgFaces.GravesHead_EP1.Facegrover_EP1 not found
10:48:12 Error: Error during SetFace - class CfgFaces.GravesHead_EP1.Facegrover_EP1 not found
10:48:28 "get: STRING (UID), sent: STRING (UID)"
10:48:28 "DISCONNECT: Mathew (UID) Object: B 1-2-A:1 (Mathew) REMOTE, _characterID: 26 at loc [15260.6,18419.9,0.00144196]"

**Comment by ebaydayz** [comment]
Similar to:
https://github.com/EpochModTeam/DayZ-Epoch/issues/1545

The "ticking" was due to radiation being activated in the debug zone. Fixed here:
https://github.com/EpochModTeam/DayZ-Epoch/commit/81262fbe1948cda391ed3346e34a9b2e85021abe

Adding a short cool down timer to change clothes might be a good idea due to the various glitches that can be generated by spamming it. I will check with razor and foxy about that.
