### ISSUE TITLE
Paint Cinder Walls

### ISSUE THREAD

**Issue by Blijfiguurpaul** [EpochModTeam/DayZ-Epoch#1314]
We all know what a cinder wall looks like, its an gray, maybe ugly, wall.
Perhaps, if there was something like paint...

My idea ie, you can buy 'paint' for a couple of gold at the trader, you go to your base and you scroll on your cinder wall, and you can upgrade it, for example, to a red cinder wall, or maybe green, ir even pink.

I think this delivers a better end game, and allows users to vustomize their bases even more.

**Comment by AirwavesMan** [comment]
I love the idea but unfortunately we need access to the p3ds to realize any of those ideas. It looks like hiddenselections are not actived on those models and do not work so far. I will close this for now and will reopen it later if we really can get into this.
