### ISSUE TITLE
Remove ammo from vehicles

### ISSUE THREAD

**Issue by Monegaskeren** [EpochModTeam/DayZ-Epoch#1322]
I was wondering if you could implement the possibility to remove ammo that you have added to vehicle's guns. I really like the vehicles with a special weapon that requires the rare ammo only found in black crates, especially the black hawk and the armored SUV, but when the weapons on these vehicles are used only as defence, it is hard to know when to load the ammo into the guns if you do not want to waste it without even firing a single round. I have read the issue about magazines filling at server restarts and understands that this is not fair either. A suggestion could be to allow unloading of ammo from a vehicle if the clip is still unused.

**Comment by AirwavesMan** [comment]
As Merlijn mentioned in discord this would need a DB call everytime the gun shots. This will not be added to save performace and the network traffic.
