### ISSUE TITLE
Add GDT_Misc

### ISSUE THREAD

**Issue by Wargog** [EpochModTeam/DayZ-Epoch#1330]
http://www.gdt-server.net/www/index.php?site=files&cat=9

I was looking at this and it brings some cool features to the game. Shoot for 1.6?

**Comment by ebaydayz** [comment]
The actual link is http://www.gdt-server.net/www/index.php?site=files&cat=9

> Heavy Machineguns and Sniper Rifles uses only primary weapon slot.

This is already the case in Epoch. 

Some of the other changes can be done in the Epoch weapon and vehicle config files if people agree on them. 

But most of the other addons in that pack are either not relevant for Epoch (commanding menu name, team leader change) or controversial (reduced grass, no environment, added thermal and NV to vehicles, NV and thermal on PSO, full screen NV, reduced sun glare, no reflection in scope, disabling guided missiles, etc.).

Specific things on that page may be useful, but definitely not the whole pack. Closing this for now, but feel free to make a more specific issue with exactly what you are requesting, so we can actually consider and discuss each change individually.
