### ISSUE TITLE
New Vehicle Addon Recommendations

### ISSUE THREAD

**Issue by Namindu** [EpochModTeam/DayZ-Epoch#1335]
These add different vehicles. These are what I would really like to see:
- German Armed Forces Pack: http://www.armaholic.com/page.php?id=16956
- USEC Bell 206B #1607 Made by Rocket: http://www.armaholic.com/page.php?id=13285
- M1161 Internally Transportable Vehicle: http://www.armaholic.com/page.php?id=15818

Just some fun addons:
- Bedford TM: http://www.armaholic.com/page.php?id=13375
- Land Rover 101 FC: http://www.armaholic.com/page.php?id=13472
- KAMAZ Civilian Pack: http://www.armaholic.com/page.php?id=16118
- UAZ 451 Pack (bukhanka) #1414: http://www.armaholic.com/page.php?id=17619

EDIT:
Suggestions from @Markokil321:
- MicroLight Powered Paragliding: http://www.armaholic.com/page.php?id=12562
- RACS UH-1H Huey Reskins: http://www.armaholic.com/page.php?id=11697
- CH-47 Reskins: http://www.armaholic.com/page.php?id=11202
- Coast Guard Helicopter and Air Rescue: http://www.armaholic.com/page.php?id=13947
- MH-6J Retex Pack: http://www.armaholic.com/page.php?id=15621
- SF/Contractor Mi-17 Pack: http://www.armaholic.com/page.php?id=18498
- SUV skin from Take on Helicopters: http://www.armaholic.com/page.php?id=26284

**Comment by AirwavesMan** [comment]
New vehicles will be added in the next weeks.
