### ISSUE TITLE
Custom player_onpause to help prevent duping.

### ISSUE THREAD

**Issue by RimBlock** [EpochModTeam/DayZ-Epoch#1340]
Can we get the player_onpause.sqf (dayzbpbo/compiles) customised to close display 46 (title menu) if the gear menu is open (display 106) 

or

Even better, use player_onpause as a reference rather than a hard coded file in  RscTitle.hpp so we can use a custom compiles to amend it ourselves.

**Comment by ebaydayz** [comment]
Done: https://github.com/EpochModTeam/DayZ-Epoch/commit/8028efbb69434088eef7aa243847f436c41c6e52

Spawn, execVM, loops and other scheduled scripts always have some delay when FPS is low, so if you need something to run immediately in the pause menu onLoad you can use the new unscheduled fn_pauseMenuChecks. 

I haven't seen any confirmed reproducible dupe that relies on the gear and pause menus open at the same time. If someone knows of one please comment here.
