### ISSUE TITLE
appeal: change type for object_data.CharacterID

### ISSUE THREAD

**Issue by ekroemer** [EpochModTeam/DayZ-Epoch#1371]
Would it be much trouble to expand the length of the CharacterID field of Object_Data from int(11) to something that could hold the SteamID?

This would make some modder's life easier and again allow for ID locking of safes and vehicles.

Yes, I know that the devs seem to have strong opinions on the question CharacterID vs. PlayerUID, but I'm still hoping I'm not triggering a negative response purely based on questions of principle, here.

**Comment by icomrade** [comment]
Completed with new HiveExt DLL
