### ISSUE TITLE
Abort timer strange behaviour.

### ISSUE THREAD

**Issue by RimBlock** [EpochModTeam/DayZ-Epoch#1379]
When accessing the game menu (from in-game pressing [ESC]) the menu appears as expected with the countdown on the abort button.

After the countdown finishes the player can click the abort button and a confirmation windows appears.  On the underlying menu the countdown appears again on the abort button.

I have also had the abort button disabled after the countdown has completed but the abort button was not pressed soon after (i.e. pull up the menu, abort countdown starts, go and grab a drink, come back, abort countdown seems to have finished, abort button not clickable).  I will try to get more specifics on this one.

Neither are game breakers.

**Comment by ebaydayz** [comment]
Confirmed fixed with new player_onPause
