### ISSUE TITLE
Client crashing when accessing body

### ISSUE THREAD

**Issue by BetterDeadThanZed** [EpochModTeam/DayZ-Epoch#1381]
Running 1.0.5.1 and the latest Arma 2 beta.

I've had several players reporting that while accessing a dead player's body, their client crashes to desktop. Several people just tried accessing a player's dead body and crashed. Once the body changed to a skull and crossbones, the problem no longer existed. Unfortunately I do not have a client RPT file from a player that crashed.

In case it makes a difference, here's the inventory from the dead body they tried accessing:

[["ItemMap","ItemWatch","Binocular_Vector","ItemKnife","ItemHatchet_DZE","ItemCrowbar","ItemMatchbox_DZE","ItemCompass","M9SD","ItemGPS","ItemToolbox","ItemKeyBlue2168","M40A3"],["5Rnd_762x51_M24","5Rnd_762x51_M24","5Rnd_762x51_M24","5Rnd_762x51_M24","5Rnd_762x51_M24","5Rnd_762x51_M24","5Rnd_762x51_M24","5Rnd_762x51_M24","5Rnd_762x51_M24","ItemBandage","ItemBandage","ItemBandage","ItemBandage",["15Rnd_9x19_M9SD",11],["15Rnd_9x19_M9SD",9],["15Rnd_9x19_M9SD",3],["15Rnd_9x19_M9SD",14]]]

["DZ_LargeGunBag_EP1",[[],[]],[["PartGlass","ItemBriefcaseS50oz","TrashJackDaniels","ItemPainkiller","ItemMorphine","ItemBloodbag","ItemBandage","15Rnd_9x19_M9SD","ItemSodaCoke","PartWheel"],[1,1,2,2,2,1,1,1,1,1]]]

**Comment by ebaydayz** [comment]
I can not reproduce this with the current files. I think it was an issue with A2OA beta 112555 which should have been fixed by the recent patches.
