### ISSUE TITLE
Undefined variable in fn_findsafepos.sqf

### ISSUE THREAD

**Issue by RimBlock** [EpochModTeam/DayZ-Epoch#1393]
My serverlog became spam-tastic last night with 

21:38:32 File ca\modules\functions\misc\fn_findSafePos.sqf, line 90
21:38:32 Error in expression < "_newY", "_testPos"];
_newX = _posX + (_maxDist - (random (_maxDist \* 2)));
_ne>
21:38:32   Error position: <_maxDist - (random (_maxDist \* 2)));
_ne>
21:38:32   Error Undefined variable in expression: _maxdist

**Comment by JerryAtricks** [comment]
I just got this error spamming my RPT today too. Only problem is ca\modules\functions\misc\fn_findSafePos.sqf doesn't exist. How is it reporting an error in a script that doesn't exist?

**Comment by RimBlock** [comment]
Maybe you would be better off reporting this to sheep.  His server pack changes most the mods he includes and none 9f these mods are supported by the Epoch Team (quite rightly so). The error is not the Sqf indicated but the fact that the information passed to that function is incorrect.   You need to look at what is calling it and track the data through the code with diag _ log lines.

**Comment by JerryAtricks** [comment]
Hey RimBlock. Unfortunately Sheep no longer supports the pack. I've been asking around but no one seems to have the answer. It doesn't seem to be affecting gameplay so it's not a major priority, but I like to keep my server error free. Just another puzzle in the long line of DayZ code issues. Thanks for the info.

**Comment by RimBlock** [comment]
I would suggest using the Git search or wingrep (if you have a local copy of the sqf code base) to find out where ca\modules\functions\misc\fn_findSafePos.sqf is called and put in diag_log lines before the call to see what values are being passed to it.  It is also quite possible that the objects DB record may be corrupted / incorrect so the actual SQF code is fine but just getting data from the DB which it is not expecting and has no error handlers to cope with.

Good luck with finding the source.

**Comment by ebaydayz** [comment]
It is an error in the WAI scripts. Replied to your forum post:
http://epochmod.com/forum/index.php?/topic/16538-file-camodulesfunctionsmiscfn-findsafepossqf-line-90/?p=212407
