### ISSUE TITLE
Issue with server_playerSync.sqf

### ISSUE THREAD

**Issue by f3cuk** [EpochModTeam/DayZ-Epoch#1395]
Getting a weird RPT error since 1.0.5.1. Not sure it does any harm, just wanted to let you guys know. Seems to happen on new players spawning.
```
14:54:54 Error in expression <er getVariable["lastPos",_charPos];
if (count _lastPos > 2 && count _charPos > 2>
14:54:54   Error position: <count _lastPos > 2 && count _charPos > 2>
14:54:54   Error count: Type Number, expected Array,Config entry
14:54:54 File z\addons\dayz_server\compile\server_playerSync.sqf, line 70
```

**Comment by ebaydayz** [comment]
It looks like somewhere the "lastPos" variable was being set to a number instead of an array as it should be. I quickly searched the Epoch files and did not see that happening anywhere. My guess is some custom script or mod was at fault.
