### ISSUE TITLE
Add UAZ 451 (bukhanka) addon

### ISSUE THREAD

**Issue by WeteRan** [EpochModTeam/DayZ-Epoch#1414]
I think that this mod must be in Epoch.
http://www.armaholic.com/page.php?id=17619

**Comment by ebaydayz** [comment]
Similar to #1607 it has no license specified by the author. 

It also has some bugs:
- [FPS drop](https://forums.bistudio.com/topic/114486-skoda-octavia-addon/?p=1903426)
- [RPT/config error spam from HitEngine class](https://forums.bistudio.com/topic/114486-skoda-octavia-addon/#entry1908172) (also breaks repairing)
- [Visible model glitch](https://forums.bistudio.com/topic/114486-skoda-octavia-addon/?p=2189423)

Shinkicker fixed the HitEngine problem, but it's not clear if he released it or has permission to do so. 

Again it is up to @vbawol

**Comment by ebaydayz** [comment]
Added to https://github.com/EpochModTeam/DayZ-Epoch/issues/1335 for consolidation of the new vehicle addon recommendations to one issue.
