### ISSUE TITLE
Zombies hardly hit players who are not there owners.

### ISSUE THREAD

**Issue by TayTayTheKiller** [EpochModTeam/DayZ-Epoch#1415]
Zombies hardly hit players if they are not the owners like in this video.
https://www.youtube.com/watch?v=2ibssJb8jiQ

I think its related to player_zombieAttack.sqf as for a quick and dirty test I just used dayz 1.8.1's version and it fixed it 100%
This video was tested with stock mission and server + AH with 2 players online.

With 1.8.1's
https://www.youtube.com/watch?v=aoQeXf5_dUU (Headless Client is the owner of all the zombies in this video)

**Comment by ebaydayz** [comment]
Fixed for 1.0.6 with 1.8.7 zombie code.
