### ISSUE TITLE
Scan inventory prior to trading for Weapons/vehicles

### ISSUE THREAD

**Issue by Markokil321** [EpochModTeam/DayZ-Epoch#1419]
Hello,

Currently, your inventory will be scanned PRIOR to starting the trading animation and it will say:
"Need X more Gold" 

However, this is only working for Items (Magazines).. Weapons and vehicles will still make you do the animation and will tell you what you are missing AFTER it has completed.

@4d6055af8b73600ba96ed22c8a2eb5e426de478f

Would it be possible for it to scan your inventory and tell you whats missing prior, for everything? 

I have this happen with both .sql and config based traders.

**Comment by icomrade** [comment]
Closing because this is now handled in advanced trading.
