### ISSUE TITLE
M113 Ambulance not firing smoke

### ISSUE THREAD

**Issue by Markokil321** [EpochModTeam/DayZ-Epoch#1440]
Hello,

We used to be able to fire smoke with the m113 ambulances by pressing R whilst in the driver seat. This no longer works, it still makes the firing noise (same noise when launching flares from a heli) But no smoke appears. This was working until the 1.0.5.1/112555 update. I thought it may have something to do with an edit on our server, but it doesn't work with default epoch files either. Could this be another issue with 112555?

Effecting all: 

M113_
M113Ambul_
++ any land vehicle that is able to fire smoke

vehicles

**Comment by ebaydayz** [comment]
Works great now, thanks.
