### ISSUE TITLE
Gear menu instantly closing.

### ISSUE THREAD

**Issue by RimBlock** [EpochModTeam/DayZ-Epoch#1443]
I have noticed for a while (since 1.0.5.1 (possibly since 1.0.5) that sometimes when accessing the gear menu ("G" by default) it opens and then instantly closes. 

Moving around sometimes fixes it but logging off and back in again clears it although it is likely to return.

Two threads on it in the forum
http://epochmod.com/forum/index.php?/topic/14459-gear-menu-instantly-closing/
http://epochmod.com/forum/index.php?/topic/14491-players-inventory-close-when-they-try-to-access-it-something-to-do-with-infistar/

It feels like something put in to stop duping which is not quite working correctly.  I have found no pattern as to when it occurs (one time when I was accessing a Chinooks gear, after clearing the bug it didn't occur at the same Chinook a few minutes later).

I only have the following installed.

ARMA II
ARMA II OA - 1.63.125548 build 323114
Epoch client 1.0.5.1
Epoch Server 1.0.5.1
A Plot for life v2.2.4 (does not touch the gear menu.  Someone else confirmed not having this installed but still seeing the issue).
Snap Build Pro.
 
I have no extra antihack.  I have nothing in the server or client RPT files indicating an error or issue.  My server only has myself playing on it.

**Comment by Windmolders** [comment]
@RimBlock Can i close this issue?

**Comment by ebaydayz** [comment]
I can not reproduce this. @Rob2222 The VON and toggle VON keys do not cause it for me either. 

We are in the process of updating to the new DayZ Mod gear dialog and scripts anyway. That should hopefully resolve the problem if it still exists.
