### ISSUE TITLE
ACR

### ISSUE THREAD

**Issue by Namindu** [EpochModTeam/DayZ-Epoch#1458]
I think it would be best to add ACR to Epoch.

Pros:
 More Guns
 More Cars
 More Skin

The only down side is it requires the ACR DLC. But the recent patchs added the lite version of acr into arma 2 oa. If not its a 113MB, download for the lite version. 

http://www.arma2.com/download

**Comment by slunski** [comment]
ACR weapons are main reason why I prefered Overpoch/Overwatch over Vanilla - they are interesting, middle power guns.

But if we talking "additions" here are few more (or should I put few more issues?):
- zombies are too stupid: eg. when you head into frontal collision they shouldn't stop 2m before you...
- I would realy appreciate if legs will breaks more often  ;)
- head-shoot-only zombies as DZE_HS_ZEDS

**Comment by AirwavesMan** [comment]
This is out of our hands. We will see if the EOL patch will add those weapons again. If yes, they will be added to Epoch Mod. I close this for now.
