### ISSUE TITLE
Loot RE-spawn is bugged (spawns only once per building and client connect)

### ISSUE THREAD

**Issue by Rob2222** [EpochModTeam/DayZ-Epoch#1470]
Hello,

In building_spawnloot you are working with:
_obj setVariable ["looted",diag_tickTime + dayz_tickTimeOffset];

In player_spawncheck you are working with:
_dateNow = (DateToNumber date);
_x setVariable ["looted",_dateNow,true];

It is a different time metric. Cause of that it is messing up the age variable in player_spawncheck:
_age = (_dateNow - _looted) * 525948;

And we have no more loot-respawn until server restart in this building, cause the age is negative.
At least if I understand it correct.

Diag Log example:
"SPAWN LOOT: Land_telek1 Building is 8.02533 old"
"SPAWN LOOT: Land_Misc_Cargo1Bo Building is 8.02533 old"
"SPAWN LOOT: Land_budova4_in Building is -3.7898e+009 old"
"SPAWN LOOT: Land_Mil_Barracks Building is -3.78988e+009 old"
"SPAWN LOOT: Land_budova4_in Building is -3.7899e+009 old"

Is this intended?

When you go to a base, loot spawns. You leave it, it despawns. You go again there after a while, nothing happens. The buildings have a wrong(?) looted value, the age is negative and the IF's in player_spawncheck ( "(_age > DZE_LootSpawnTimer) &&..." ) will never get true until/if the building_monitor sets "looted" to a correct "datetonumber date" value anywhen. I don't know, when/if building_monitor is called.

But the 10 minute respawn timer does not work atm.

After removing "_obj setVariable ["looted",diag_tickTime + dayz_tickTimeOffset];" in building_spawnloot, loot spawning is working and after cleanup it will respawn when the 10 minutes are over.

For me it looks like it is not intended to set "looted" in building_spawnloot, cause it is already set in player_spawncheck when building_spawnloot is called.

(The cleared variable is never set to false, also. I think.)

However, I don't know which loot behaviour you guys intend.

BR
Rob

**Comment by mikeloeven** [comment]
This issue seems to still be open and i can confirm that loot is not properly regenerating or being cleaned up in the most recent edition of epoch i would like to give a bit of a Bump to this issue since it is seriously detrimental to gameplay.

**Comment by slunski** [comment]
Loot spawn should be trigged by  player_monitor.fsm  but this looks to be un-used in dayz_code.
So:

 "dayz_spawnCheck = [] spawn {" \n
       "	while {true} do {" \n
       "		[""both""] call player_spawnCheck;" \n
       "		sleep 8;" \n
       "	};" \n
       "};" \n

is never executed. First call for player_spawnCheck is in  player_spawn_1.sqf  so loot spawns once.

building_monitor.sqf looks to be unused too.

Also:
spawnCheck have:

_nearby = _position nearObjects ["building",_radius];

so iterates buildings:

{
    ...
    _x setVariable ["looted",_dateNow,true];
    _x call building_spawnLoot;
    ...
} forEach _nearby;

But building_spawnLoot have:

_pos = [] + getArray (_config >> "lootPos");
_positions = _pos call _ShuffleArray;
{
   ...
   [_itemType select 0, _itemType select 1 , _iPos, 0.0] call spawn_loot;
   dayz_currentWeaponHolders = dayz_currentWeaponHolders +1;
   _obj setVariable ["looted",diag_tickTime + dayz_tickTimeOffset];   // RAPORTED ABOVE
} count _positions;

so iterates and setVarible on loot positions...

Also: dayz_currentWeaponHolders never decrases.

In the meantime  server_spawnCleanLoot  delete all loot on entire map :)

Testing...

**Comment by mikeloeven** [comment]
wow pain in the sides of epoch players for years finally pinned down

**Comment by Windmolders** [comment]
@slunski 
Will you be making a merge request for this, or am i going to need to code this?

**Comment by Rob-2** [comment]
Hello,
I dont have the time to investigate the last few posts in the second.


But it's totally OK to remove the two "_obj setVariable ["looted",diag_tickTime + dayz_tickTimeOffset];" as posted and the loot respawns as it should. I have that running working on my server since I opened this ticket.

BR
Rob

**Comment by Rob-2** [comment]
Hello Slunski,
it's cool, that some one looked over the spawn code, also. :)
I am trying to understand and Re-check your thoughts...

>Loot spawn should be trigged by player_monitor.fsm but this looks to be un-used in dayz_code.
>is never executed. First call for player_spawnCheck is in player_spawn_1.sqf so loot spawns once.

Stop. "building_spawnLoot" is called by "player_spawnCheck" which is called _regulary_ by "player_spawn_1" in a "while true loop". So this is not only called once.


>building_monitor.sqf looks to be unused too.
Indeed. However, this is no problem.

>Also: spawnCheck have: ...
>so iterates buildings...
>But building_spawnLoot have...
>so iterates and setVarible on loot positions...
Yes. But why is this a problem? (Apart from the reported setVariable problem)


>Also: dayz_currentWeaponHolders never decrases.
Stop. It is updated regulary in the continous while loop in player_spawn_1
"dayz_currentWeaponHolders = count (_position nearObjects ["ReammoBox",100]);"



I still think, one only needs to remove the two "_obj setVariable ["looted",diag_tickTime + dayz_tickTimeOffset];" for the loot system to work as intended.
However, I have not yet ever done a merge request on github yet... ^^ 

Will there be any version 1052 or 1060 from ePoch?

BR
Rob

**Comment by Rob2222** [comment]
Hello Slunski,
it's cool, that some one looked over the spawn code, also. :)
I am trying to understand and re-check your thoughts...

    Loot spawn should be trigged by player_monitor.fsm but this looks to be un-used in dayz_code.
    is never executed. First call for player_spawnCheck is in player_spawn_1.sqf so loot spawns once.

Stop. "building_spawnLoot" is called by "player_spawnCheck" which is called regulary by "player_spawn_1" in a "while true loop". So this is not only called once.

    building_monitor.sqf looks to be unused too.

Indeed. However, this is no problem.

    Also: spawnCheck have: ...
    so iterates buildings...
    But building_spawnLoot have...
    so iterates and setVarible on loot positions...

Yes. But why is this a problem? (Apart from the reported setVariable problem)

    Also: dayz_currentWeaponHolders never decrases.

Stop. It is updated regulary in the continous while loop in player_spawn_1
"dayz_currentWeaponHolders = count (_position nearObjects ["ReammoBox",100]);"

I still think, one only needs to remove the two "_obj setVariable ["looted",diag_tickTime + dayz_tickTimeOffset];" for the loot system to work as intended.
However, I have not yet ever done a merge request on github yet... ^^ Maybe I should learn this.

Will there be any version 1052 or 1060 from ePoch?

BR
Rob

**Comment by slunski** [comment]
Yes, I messed a bit with: unused/unupdated thingies.

But after testing I got loot to respawning.

What I did:
1) in player_monitor.fsm removed spawn loop player_lootCheck.sqf. It is called from
   player_spawn_1.sqf few lines above.
2) added
_item setVariable ["looted",(DateToNumber date),true];
_item setVariable["buildingLoot",true, true];
to spawn_loot.sqf and spawn_loot_small.sqf, before last line
3) added
_keep = _x getVariable["buildingLoot",_keep];
after _keep assignment to server_spawnCleanLoot function in
dayz_server/init/server_functions.sqf file

Looks like working !

**Comment by Rob2222** [comment]
But why so complicated? What you want to achieve?

Just remove the two "_obj setVariable ["looted",diag_tickTime + dayz_tickTimeOffset];" as stated in the first post and you also get loot (re)spawn (after the timer run down).

If I remember correct, after 20 minutes with no player near loot is getting cleared and each 10 minute is a chance to (re)spawn loot.

**Comment by mikeloeven** [comment]
Actually if there are 2 or more people at a site there is no 20 min cool down and loot constantly re spawns on the 10min timer so basically the bug only really hits solo players.

**Comment by Rob2222** [comment]
Hello Mike,

iirc the loot gets cleared after 20 minutes if no one is near... in server_functions.sqf, function server_spawnCleanLoot ... "if (_age > 20) then ... delete".

>Actually if there are 2 or more people at a site there is no 20 min cool down and loot constantly re spawns on the 10min timer so basically the bug only really hits solo players.

Really? Was there something changed since 1051? Cause the ground for me to start investigate that was, that on a 20-30 player chernarus server was regulary _absolutely_ no loot in the airfield barracks after a while.

If, with 1051, you have for example 5 people on the airfield... each player can loot the airfield one time. After that, the looted variables are buggeg, like in the first post described. After all player were on the airfield then, nobody can re-spawn loot at the airfield. On a 6h restart schedule, this can be a real problem.

You can see it yourself... make a custom player_spawnCheck.sqf... then below "_age = (_dateNow - _looted) * 525948;" add:
diag_log ("SPAWN LOOT: looted:" + str(_looted) + " Building is " + str(_age) + " old, name: " + _type);
And then observe the variables after the 10 minute intervals.

BR
Rob

**Comment by Rob2222** [comment]
The problem in more detail is:

Epoch is working with DATE in player_spawnCheck.sqf:

_looted = (_x getVariable ["looted",-0.1]);
_dateNow = (DateToNumber date);
_age = (_dateNow - _looted) * 525948;
if ((_age > DZE_LootSpawnTimer) && (!_cleared)) then
_x setVariable ["looted",_dateNow,true];
"spawnloot".

This checks, if the building can be looted again (timer) and then spawns loot and is setting the time in the looted variable in the "date" format.

However, as the devs were migrating the DayZ 1.8.1 Loot System, to Epoch 1.0.5.1, they took over these two lines "_obj setVariable ["looted",diag_tickTime + dayz_tickTimeOffset];" in building_spawnLoot.sqf from DayZ 1.8.1. You can find these lines in the DayZ code. They are from the DayZ code and they are unnecessary in Epoch, cause the timers are handled already by player_spawnCheck.sqf in Epoch.
However, these lines are there, working with the "diagticktime" format, get executed and overwrite the epoch "date" looted variable with a dayz 1.8.1 "diagticktime" value.

As a result of that in the next turn of Epoch player_spawnCheck.sqf the "_age = (_dateNow - _looted) * 525948;" gets a negative value ("SPAWN LOOT: Land_Mil_Barracks Building is -3.78988e+009 old") and the "if ((_age > DZE_LootSpawnTimer)..." will never be executed again. So no loot RE-spawn.

BR
Rob

**Comment by ebaydayz** [comment]
Fixed for 1.0.6 with update to 1.8.7 loot code.
