### ISSUE TITLE
A Plot for Life build for core Epoch - Updates.

### ISSUE THREAD

**Issue by RimBlock** [EpochModTeam/DayZ-Epoch#1536]
Just putting this up as a record of progress for the dev team so they know it is progressing.

Current state: Alpha-0.2.1 build.

This is being build on 1.0.5.2-RC files.
If is also incorporating Raymixs modular build system as well as the original build system.

Latest build
Incorporated Epoch 1.5.0.2. s FNC_GetPlayerUID.
Merged with the modular building system.
Number of bug fixes.

How it works.
The buildables playerUID us saved as an extra field in the worldspace filed (lots of room available).

On server start, a new variable is added to objects (ownerPUID) which is populated with the characterID (A Plot for life turned off) or value stored int he worldspace extra array (A Plot for life turned on).  Ownership comparisons then compare with the players PUID or CharacterID depending if APfL is on or off.

On saving, the DB save sets the worldspace extra array to the player PUID but sets the in game object variable to either PUID or CharacterID depending on whether APfL is on or off.

This should make it possible to turn APfL on and off as desired and it working for either for anything build after the release with APfL included.  Some SQL code or sqf function may be needed to realign historical buildables without a playerUID assigned.

Tested so far.
APfL: false, modular build: True & False, Snapbuild: false.
 - Plot pole build / remove: ok
 - Modular item build / remove: ok
 - Safe build / unlock / remove: ok
 - Tent build / remove: ok
 - Modular up/downgrade: Not yet tested.

**Comment by RimBlock** [comment]
If I re-engineer A Plot for Life for inclusion with Epoch, will anyone have the time to test and merge ?.  

I am ok to spend the time to make it compatible with 1.0.5.2 again but only if it is going to get looked at.

**Comment by SplenectomY** [comment]
Yes. I am messaging VBawol now to set up a proper test server, as I am already testing some of the files (such as the new GUI). Please message me.

**Comment by RimBlock** [comment]
Ok, will take a week or two for me to take a look and get it recoded and merged in to the Epoch 1.0.5.2 RC files but will post here when available.

Thanks

**Comment by ebaydayz** [comment]
I've also messaged vbawol that I am available for testing. I have a dedicated test server setup and ready to go. He has not replied yet.

**Comment by RimBlock** [comment]
Ok, will try to take a look at this during this week.  Mikeeeyy has also kindly agreed to allow his Precise Base Building mod be included as well so I will add them both together.

**Comment by ebaydayz** [comment]
Awesome, it looks like vbawol will be getting a test build ready for everyone:
https://github.com/vbawol/DayZ-Epoch/issues/1623

**Comment by RimBlock** [comment]
Ok, have updated my fork with the latest updates from the DayZ Epoch Master and have created an A Plot for Life branch.  The files are merged there but i have not tested them yet.  I have spotter a couple of improvements and have made some light changes from the current released version.

Fileve from A Plot for Life merged are v2.35 and the extras added in v2.4 and v2.5 (some extra code tuning, repeated code block for finding poles put in to a new function and inclusion of Precise Base Building with Mikeeeyys permission). 

If anyone wants to take a look and help with the testing then come grab a copy (https://github.com/RimBlock/DayZ-Epoch/tree/A_Plot_for_life).

Once I have tested on my own fork I will put in a pull request to merge them back in with the Master branch here.

**Comment by RimBlock** [comment]
New "Take Ownership" function now seems to be working after porting it over to server side to reduce network traffic.

Working on plot markers to add height as well (with help from F3CUKs implementation).  My geometry sucks after 20 years with no particular practice :-).

Precise Base Building seems to be working as does the updated Modular Build code and Snap Build is also still ok.

I will sort the plot markers, test the build combos and then push to the Epoch Master Git.

**Comment by Windmolders** [comment]
@RimBlock any updates on this?

**Comment by icomrade** [comment]
Closing because plot for life is now part of Epoch base. see 575682b7c8de8826671c4e1e14d194ef20526c30 and the next couple of commits.
