### ISSUE TITLE
Characters stop updating after Skin Change

### ISSUE THREAD

**Issue by Uro1** [EpochModTeam/DayZ-Epoch#1545]
Sometimes after a skin change a players characters stop updating, they relog and are back where they were when they changed skin.

There are a lot of people suffering from Skin Changes and Characters not updating afterwards, Thought I'd open an issue as there's becoming quite a large forum thread on the issue:

http://epochmod.com/forum/index.php?/topic/14296-sometimes-character-stops-updating-after-skin-change/

**Comment by ebaydayz** [comment]
I tested and it appears to be fixed now with the new switch_model and player_sync.
