### ISSUE TITLE
warehouse deleted content error on load in

### ISSUE THREAD

**Issue by DarthRogue** [EpochModTeam/DayZ-Epoch#1546]
When loading into  a server players are getting an error message.  "You cannot edit/play this mission that depends on downloadable content 'warehouse' that has been deleted".  To fix this, you need to add "warehouse" to the list of addons included in the mission.sqm file.  See forum post here:

 http://epochmod.com/forum/index.php?/topic/6486-warehouse/

The mission.sqm file needs updated accordingly in the repo for future updates.

**Comment by ebaydayz** [comment]
It is best practice to use only the addons you need to improve loading times. If admins want to add custom map content that relies on other addons it is their responsibility to load them in mission.sqm.
