### ISSUE TITLE
Unpacking supply crate over water, content is spiled deep underwater.

### ISSUE THREAD

**Issue by pj999** [EpochModTeam/DayZ-Epoch#1558]
If you have base over water, when unpacking supply crate content gets unpacked underwater at the same height from bottom of the ocean as is it from sea level.

**Comment by Windmolders** [comment]
You could place a placeholder in the air in front of the user.

**Comment by ebaydayz** [comment]
@icomrade I tested your commit and it spawned the items directly on the surface of the water. That is problematic for floors raised a few meters above the water.

I changed it so it spawns directly on the player's feet. I did the same with the sledgehammer fix. Tested both over water, on flat ground and raised above ground. Confirmed working in all cases.

https://github.com/EpochModTeam/DayZ-Epoch/commit/65c2a7e6b44cb0da35a3cf9afc70b83e5db4e9a8

**Comment by icomrade** [comment]
Awesome, thanks!
