### ISSUE TITLE
Can't forge metal floors over water with fire barrels

### ISSUE THREAD

**Issue by pj999** [EpochModTeam/DayZ-Epoch#1559]
If you try to craft metal floors where fire barrels are over deep ocean water you get "you need fire withing 3m"

**Comment by ebaydayz** [comment]
Tested and confirmed fixed.
![2016-02-18_00001](https://cloud.githubusercontent.com/assets/7761693/13157242/bb877724-d654-11e5-86a6-6d23cc30b1c5.jpg)
