### ISSUE TITLE
Restrict wearable skins

### ISSUE THREAD

**Issue by BetterDeadThanZed** [EpochModTeam/DayZ-Epoch#1560]
A suggestion, not an issue, but could a variable be added to the init.sqf that will prohibit specified skins from being put on by the players? See this thread: http://epochmod.com/forum/index.php?/topic/16381-stop-certain-skins-from-being-worn

**Comment by Windmolders** [comment]
@BetterDeadThanZed I'll make it happen : )

**Comment by ebaydayz** [comment]
Added, tested and confirmed working. https://github.com/EpochModTeam/DayZ-Epoch/commit/0075b44c0e8d146e1d2d9238f253ddbecc17e95d
