### ISSUE TITLE
Update Sauerland V1.90

### ISSUE THREAD

**Issue by vbawol** [EpochModTeam/DayZ-Epoch#1565]
Sauerland V1.90 By falconsan
http://www.s6computer.de/Downloads.html

**Comment by icomrade** [comment]
Can't get a copy of the summer version of the map, but I have Sauerland Winter version 1.90.03, what needed to be updated anyway?

**Comment by Adaptivity** [comment]
Is it possible to contact falconsan somehow? To get latest 1.90.04 version. He still visiting epochmod.com.

**Comment by icomrade** [comment]
I sent him a private message a while ago, he never responded. He posted a download to the winter version of the map - 1.90.03 is the latest according to his post and his website. here's a link to his latest post with a DL link:
http://epochmod.com/forum/index.php?/topic/18959-summer-or-winter/&page=3#comment-272503

However, I'm not sure replacing the summer version with the winter version is the best solution, ideally both would be included but that would make the package very large. Perhaps @falconsan would be able to upload the latest summer version, unless we all agree that the best course would be to use the more up to date and polished winter version. Still I'd personally like to see both versions included in the mod but that may not be realistic.

**Comment by Adaptivity** [comment]
@icomrade http://epochmod.com/forum/topic/18959-summer-or-winter/?do=findComment&comment=275344 I guess you just have to wait until 2.00 version will be released.

**Comment by icomrade** [comment]
Yeah I saw that too, thanks for posting it here for others. When he releases it I'll test the map with epoch. Ultimately updating Sauerland is kind of low on my priority list.

**Comment by falconsan** [comment]
wtf. i forget i was registered at Github. Sorry for no response.

A new Sauerlandversion will be released in the next four weeks. Sauerland is no longer at my priority list. I will release Updates sporadic. My priority is my new Map "Dayz Rügen".

i will patch all changes of the Wintermap into the Summerversion, so that both maps at a indentic Patchstatus.

regards

**Comment by icomrade** [comment]
@falconsan any updates?

**Comment by AirwavesMan** [comment]
It looks like Sauerland will not become a new update. Closed for future respond from @falconsan or any new updates.
