### ISSUE TITLE
Glitch through locked metal gates with suvs

### ISSUE THREAD

**Issue by StiflersM0M** [EpochModTeam/DayZ-Epoch#1576]
Hey hey,

Hope i can report it here, als tried to write a dirty fix which worked, but not so as i want it too work.

anyway, you can glitch with a suv through locked metal gates (only metal), Just drive backwards against the gate, it takes 3-6 seconds and you are in the base.

I think its easy to fix, cause in wooden gates it do not work.

**Comment by ndavalos** [comment]
One of my players reported this is still an issue and sent me video demonstrating backing through a garage door.

**Comment by AirwavesMan** [comment]
Fixed by @Helion4  in Epoch 1.0.7
