### ISSUE TITLE
1.8.2 Stuff + Some Addons

### ISSUE THREAD

**Issue by Markokil321** [EpochModTeam/DayZ-Epoch#1577]
What are the possibilities of adding some of the cool stuff from Vanilla DayZMod to Epoch?

Things like the:

- Regular / nailed and Spiked MeleeBaseBallBat.
- CCO / scoped crossbows w the explosive ammo/ tranquiliser bolts.
- ItemTrapBearTrapFlare / Smoke
- ItemTrapTripWireCans / Flare / Smoke / Grenade
- ItemCarBomb
etc.etc.

Also found these awesome looking addons on armaholic: (guess this is more complicated to add and would also require permission from the creators?)

MicroLight - Powered Paragliding
- http://www.armaholic.com/page.php?id=12562

RACS UH-1H Huey Reskins
- http://www.armaholic.com/page.php?id=11697

CH-47 Reskins
- http://www.armaholic.com/page.php?id=11202

Coast Guard Helicopter and Air Rescue
- http://www.armaholic.com/page.php?id=13947

MH-6J Retex Pack
- http://www.armaholic.com/page.php?id=15621

SF/Contractor Mi-17 Pack
- http://www.armaholic.com/page.php?id=18498

SUV skin from Take on Helicopters
- http://www.armaholic.com/page.php?id=26284

UAZ 451 Pack
- http://www.armaholic.com/page.php?id=17619

Not trying to make this exactly like overwatch... but it does look awesome.
Willing to help with anything if needed.

Thoughts?

**Comment by Windmolders** [comment]
Porting Epoch to newest dayz 1,8,* wil be alot of work since the core code has changed alot.

Taking out single resources is not allowed i think.

External addons may be considered, i'll talk to awol about that.

**Comment by ebaydayz** [comment]
The 1.8.7 stuff is in now. I added your other addon recommendations to the vehicle addon recommendations issue, since some were duplicates: #1335
