### ISSUE TITLE
Request: Custom key names, or derive from vehicle object name.

### ISSUE THREAD

**Issue by NessInOnett** [EpochModTeam/DayZ-Epoch#1585]
This could work two ways:

1) Custom names for keys.  Right click a key -> Name Key -> text edit dialog opens -> Key's name could appear as: Key (e8b1 - Bob's Red SUV)

2) Easier to code, but not quite as useful.  Name key based on the vehicle object name.  Key names could appear as: Key (e8b1 - ArmoredSUV_PMC_DZE)

It can be extremely frustrating trying to keep track of vehicle keys, key copies, etc.  One of these options would help a ton, and reduce the need to constantly write everything down.

**Comment by FARTBOXGAMING** [comment]
Just a thought... I'm not much of an SQL expert but if we are allowing users to put their own descriptions on the keys would we have to worry about SQL injection?

**Comment by icomrade** [comment]
So long as you sanitize and properly escape the string you'll be fine. That being said, I don't think that this is going to be implemented since there's already very easy to implement mods that don't require DB access or server/hive modifications.

**Comment by Namindu** [comment]
Is it possable we can add another column in the vehicle table for key ids?

**Comment by AirwavesMan** [comment]
I do not see any way to realize naming keys without creating keys as an acutal object. So I close this here.
