### ISSUE TITLE
player_dumpBackpack issue

### ISSUE THREAD

**Issue by Markokil321** [EpochModTeam/DayZ-Epoch#1591]
Why is this not included in the 1.0.5.1 files? I thought this would fix the ol dropped backpack vanishing issue. It seems like it was included in the 1.0.4.1 files, but i could not find it in the downloaded dayz_code\compile\player_dumpbackpack.sqf on 1.0.5.1.

https://github.com/vbawol/DayZ-Epoch/commit/bf189761ad0090e05725474ee4d66b54aa982988

Will add the fix manually to our server, but was just wondering :8ball: 
Or am i just very high?

**Comment by ebaydayz** [comment]
Player_dumpBackpack is no longer used in the new dayz_code:
https://github.com/EpochModTeam/DayZ-Epoch/commit/ef873c2340572e9c09b8b024075d670ef944eec4
