### ISSUE TITLE
no player sync after unconsciousness

### ISSUE THREAD

**Issue by hipp-e** [EpochModTeam/DayZ-Epoch#1603]
if you're wounded, or overburdened till becoming unconscious, when you wake up ANY add-on ai doesn't see your current location - ai thinks that you're standing right where you were down, even if you're shooting thair backs with m9 already. They can kill you, if they shoot at the correct spot - but if you become unconscious far from mission (1.5-2 km) - you can easily farm the missions. You become sorta invulnerable for ai,  till you enter some vehicle. if you relog in that condition - you spawn right where you've became unconscious (but your gear is ok),  which also could be used as kinda teleport.
Some using that mtb work-around that is available @ official forums, but that's not an option.

**Comment by ebaydayz** [comment]
Duplicate of https://github.com/EpochModTeam/DayZ-Epoch/issues/1522
