### ISSUE TITLE
Amphibious pook/cessna server FPS Issues! 

### ISSUE THREAD

**Issue by Markokil321** [EpochModTeam/DayZ-Epoch#1612]
Opening this as the previous issue is very old, closed and not many people knew about it.

The use or presence of any amphibious pook or amphibious cessna on your server will have a negative impact on server FPS and with the amphibious cessna's willl cause a significant increase in out traffic until the vehicle is deleted.

WITHOUT AMPHIBIOUS CESSNA (1 player ingame no ai): http://i.imgur.com/KWgxFbi.png
WITH AMPHIBIOUS CESSNA + me in it (1 player ingame no ai): http://i.imgur.com/YhWD7Xo.png

Same thing with amphibious pooks (FPS wise) except then there is no major increase in the out traffic. Neither problems occur when spawning in any other (non modded) vehicle.

Please refer to this old thread for more info: #969
I would advise removing these amphibious vehicles from your server / notifying the mod creator of the issue. 

EFFECTED: (pook_h13_amphib, pook_h13_amphib_, GNT_C185E, GNT_C185F)

**Comment by Windmolders** [comment]
Noted. But they will probably stay in configs. I'm not really sure i can make this call.

**Comment by ebaydayz** [comment]
Will just leave this here as info. As vbawol said in the other issue:
<pre>Ok, thanks for confirming this. Nothing we can really do but tell ppl not to use them. I will make a note in the changelog about this.</pre>

**Comment by ebaydayz** [comment]
These are already removed from dynamic_vehicle.sqf and the info is added in the change log.
