### ISSUE TITLE
Server RPT Spam

### ISSUE THREAD

**Issue by Markokil321** [EpochModTeam/DayZ-Epoch#1628]
Frequently getting these messages at random spammed throughout the server RPT during a session - i doubt anything is being broken however it would still be nice if they didn't come up. (why are so many of the dayzmod 1.8 drinks causing these?)  (gave up with github code tags as it just wouldn't look right)

19:16:06 Warning: z\addons\dayz_communityassets\models\soda_lvg_clean_full.p3d:0 Error while trying to generate ST for points: 139, 141, 174
19:16:06 Warning: z\addons\dayz_communityassets\models\soda_lvg_clean_full.p3d:0 Error while trying to generate ST for points: 139, 174, 173
19:16:06 Warning: z\addons\dayz_communityassets\models\soda_lvg_clean_full.p3d:0 Error while trying to generate ST for points: 137, 139, 173
8:08:10 Warnings in z\addons\dayz_communityassets\models\soda_lvg_clean_full.p3d:shadow(1000)

 8:08:11 Warning: z\addons\dayz_communityassets\models\soda_rabbit_clean_full.p3d:0 Error while trying to generate ST for points: 143, 145, 176
 8:08:11 Warning: z\addons\dayz_communityassets\models\soda_rabbit_clean_full.p3d:0 Error while trying to generate ST for points: 143, 176, 175
 8:08:11 Warnings in z\addons\dayz_communityassets\models\soda_rabbit_clean_full.p3d:shadow(1000)

17:21:07 Warning: z\addons\dayz_communityassets\models\soda_rabbit_clean_empty.p3d:0 Error while trying to generate ST for points: 147, 149, 182
17:21:07 Warning: z\addons\dayz_communityassets\models\soda_rabbit_clean_empty.p3d:0 Error while trying to generate ST for points: 147, 182, 181
17:21:07 Warning: z\addons\dayz_communityassets\models\soda_rabbit_clean_empty.p3d:0 Error while trying to generate ST for points: 145, 147, 181

18:07:42 Warning: z\addons\dayz_communityassets\models\soda_lemonade_clean_full.p3d:0 Error while trying to generate ST for points: 143, 145, 176
18:07:42 Warning: z\addons\dayz_communityassets\models\soda_lemonade_clean_full.p3d:0 Error while trying to generate ST for points: 143, 176, 175
18:07:42 Warnings in z\addons\dayz_communityassets\models\soda_lemonade_clean_full.p3d:shadow(1000)

15:45:57 Warning: z\addons\dayz_communityassets\models\soda_smasht_clean_full.p3d:0 Error while trying to generate ST for points: 139, 141, 174
15:45:57 Warning: z\addons\dayz_communityassets\models\soda_smasht_clean_full.p3d:0 Error while trying to generate ST for points: 139, 174, 173
15:45:57 Warning: z\addons\dayz_communityassets\models\soda_smasht_clean_full.p3d:0 Error while trying to generate ST for points: 137, 139, 173

17:00:44 Warning: z\addons\dayz_communityassets\models\compass.p3d:0 Error while trying to generate ST for points: 863, 853, 852

17:08:01 Warning: z\addons\dayz_communityassets\models\razor.p3d:0 Error while trying to generate ST for points: 214, 349, 208

17:47:20 SetFace error: class CfgFaces.OharaHead.Face04_EP1 not found
17:47:20 Error: Error during SetFace - class CfgFaces.OharaHead.Face04_EP1 not found
 1:19:11 SetFace error: class CfgFaces.RodriguezHead.Face78 not found
 1:19:11 Error: Error during SetFace - class CfgFaces.RodriguezHead.Face78 not found

**Comment by deannreid** [comment]
This is just errors from DayZ code, not epoch related as far as I know

**Comment by Markokil321** [comment]
Yeah that's clear. There were however many changes/updates to the dayz_communityassets.pbo in dayz 1.8.X (These errors are non existent in vanilla afaik)

If it is allowed it could be recommended to see what could be updated from the vanilla dayz_communityassets.pbo.

**Comment by icomrade** [comment]
Yeah this was fixed quite a while ago. I assume it's as simple as asking to use the new community assets pbo, if Awol doesn't have permission. Either way, it doesn't really effect performance at all and is just a warning.

**Comment by Namindu** [comment]
He should be allowed. Under the copyright of Dayz Mod. He should be able to just uses them with credit.

**Comment by Markokil321** [comment]
If it would be possible to use the new dayz_communityassets that really would be great. These messages make up the majority of our .rpt related spam.

@vbawol

**Comment by deannreid** [comment]
You can just use the new one but you will need to disable verifysignatures on your server

**Comment by Windmolders** [comment]
Will look at it

**Comment by ebaydayz** [comment]
Done for 1.0.6.
