### ISSUE TITLE
fn_damageHandler.sqf humanity bug? 

### ISSUE THREAD

**Issue by Markokil321** [EpochModTeam/DayZ-Epoch#1645]
http://epochmod.com/forum/index.php?/topic/33045-releasefix-bugs-unconscious-and-invisible-for-ai-humanity-boost/

Can anyone confirm or deny that this is an actual present issue (not been able to test yet)

**Comment by ebaydayz** [comment]
Fixed with https://github.com/EpochModTeam/DayZ-Epoch/commit/8158245b83698d39f744d2d315ad2d68296a631a
