### ISSUE TITLE
Warning messages - wood_wreck_half

### ISSUE THREAD

**Issue by Markokil321** [EpochModTeam/DayZ-Epoch#1646]
I understand these don't actually break anything, but can something be done to prevent these from showing.

20:46:29 Strange convex component03 in z\addons\dayz_epoch\models\wood_wreck_half.p3d:geometry
20:46:29 Strange convex component07 in z\addons\dayz_epoch\models\wood_wreck_half.p3d:geometry
20:46:29 Strange convex component57 in z\addons\dayz_epoch\models\wood_wreck_half.p3d:geometry
20:46:29 Strange convex component61 in z\addons\dayz_epoch\models\wood_wreck_half.p3d:geometry
20:46:29 Strange convex component03 in z\addons\dayz_epoch\models\wood_wreck_half.p3d:geometryFire
20:46:29 Strange convex component07 in z\addons\dayz_epoch\models\wood_wreck_half.p3d:geometryFire
20:46:29 Strange convex component57 in z\addons\dayz_epoch\models\wood_wreck_half.p3d:geometryFire
20:46:29 Strange convex component61 in z\addons\dayz_epoch\models\wood_wreck_half.p3d:geometryFire
20:46:29 Strange convex component03 in z\addons\dayz_epoch\models\wood_wreck_half.p3d:geometryView
20:46:29 Strange convex component07 in z\addons\dayz_epoch\models\wood_wreck_half.p3d:geometryView
20:46:29 Strange convex component57 in z\addons\dayz_epoch\models\wood_wreck_half.p3d:geometryView

**Comment by Windmolders** [comment]
Out of my field. This is moddeling. I'm pretty sure it's going to get ignored for end-life-patch

**Comment by AirwavesMan** [comment]
Not a serious problem, closed for now.

**Comment by AirwavesMan** [comment]
Fixed by Helion4 in Epoch 1.0.7
