### ISSUE TITLE
m240_nest_kit >> M240Nest_DZ is lockable

### ISSUE THREAD

**Issue by Markokil321** [EpochModTeam/DayZ-Epoch#1650]
The above item when built by a player, (sandbag nest with m240) is lock/unlockable just like a regular vehicle. 

This results in an error in the .RPT (ofcourse), i believe this object should not have options to lock/unlock.

```
Error in expression <xt [format["%1 used to unlock vehicle.",_key], "PLAIN"];
};

s_player_lockUnlock>
  Error position: <_key], "PLAIN"];
};

s_player_lockUnlock>
  Error Undefined variable in expression: _key
File z\addons\dayz_code\actions\unlock_veh.sqf, line 19 
```

**Comment by icomrade** [comment]
I can't reproduce this, is the server running any mods? The stock fn_selfActions.sqf filters out any vehicles without keys so you shouldn't get a lock option at all.

**Comment by ebaydayz** [comment]
It is not lockable for me either. My guess is this is the result of some custom scripts or mods on your server. You may also have accidentally generated a key in your inventory for it with infistar or similar admin script hotkey.
