### ISSUE TITLE
"This server is running an incorrect version of the server side application."

### ISSUE THREAD

**Issue by ajbboy123** [EpochModTeam/DayZ-Epoch#1671]
I posted this on the epochmod forums, but I want to post it here as well, because that doesn't seem to get much attention, or answers...

Basically, title explains what's happening. I have a Linux Dedicated Server Box, and I am trying to run a ArmA 2 DayZ Overpoch Server. I've gotten everything working (that I know of), and I can finally join the game, and load into the loading screen, but after 10 seconds of loading it kicks me and says "This server is running an incorrect version of the server side application. You cannot play on this server. If you are the server admin please contact DayZ Epoch staff." I've already tried many times to fix this, and have done my fair share of research. I've updated the ArmA 2 OA Server files (just the server side files, not the entire ArmA 2 Game files). I've corrected and mostly fixed my MySQL, and connectivity (can't actually tell if it's connecting or not). Any suggestions would be greatly appreciated.

My Server is a Linux, Debian 7.8 (Stable), I run a few other Servers on this Machine, including TeamSpeak, Minecraft, and GMod sometimes. I've hosted Vanilla and Semi-Modded ArmA 2 OA Servers before on this Server, and it's worked fine, so I want to host a ArmA 2 DayZ Overpoch for me and my friends, and finally got it mostly working, except for this problem. Thanks in Advance!

I've looked for Hive logs, and couldn't find any.
I did however find my Client RPT logs if it's useful, here is some stuff I found interesting (btw, I just tryed to join the server and it popped up with the message, then went to check the rpt logs):

`"DayZ Epoch: PRELOAD Functions\init [[L 1-1-A:1 REMOTE],any]"
"DayZ Epoch: MPframework inited"
"DEBUG: loadscreen guard started."
Warning: z\addons\dayz_communityassets\models\compass.p3d:0 Error while trying to generate ST for points: 863, 853, 852
"Res3tting B!S effects..."
"\z\addons\dayz_code\system\REsec.sqf:Monitoring Remote Exe..."
"z\addons\dayz_code\system\antihack.sqf: Plants libs tests done!"
Fresnel k must be >0, given n=0.8,k=0
Fresnel k must be >0, given n=0.8,k=0
"PLAYER RESULT: false"
"PLOGIN: Model was empty, loading as survivor"
"End Mission"
"DayZ Epoch: PRELOAD Functions\init [[<No group>:0 (FunctionsManager)],any]"
"DayZ Epoch: MPframework inited"
Error in expression <;
_recompile = (count _this) > 0;

if (BIS_fnc_init && !_recompile) exitwith {t>
  Error position: <BIS_fnc_init && !_recompile) exitwith {t>
  Error Undefined variable in expression: bis_fnc_init
File ca\Modules\Functions\init.sqf, line 28
"DayZ Epoch: PRELOAD Functions\init [[L 1-1-A:1 REMOTE],any]"
"DayZ Epoch: MPframework inited"
"DEBUG: loadscreen guard started."
"Res3tting B!S effects..."
"\z\addons\dayz_code\system\REsec.sqf:Monitoring Remote Exe..."
"z\addons\dayz_code\system\antihack.sqf: Plants libs tests done!"
"PLAYER RESULT: false"
"PLOGIN: Model was empty, loading as survivor"
"End Mission"
"DayZ Epoch: PRELOAD Functions\init [[L 1-1-A:1 REMOTE],any]"
"DayZ Epoch: MPframework inited"
"DEBUG: loadscreen guard started."
"Res3tting B!S effects..."
"\z\addons\dayz_code\system\REsec.sqf:Monitoring Remote Exe..."
"z\addons\dayz_code\system\antihack.sqf: Plants libs tests done!"
"PLAYER RESULT: false"
"PLOGIN: Model was empty, loading as survivor"
"End Mission"`

**Comment by Evocation** [comment]
hey..

check this:


https://github.com/vbawol/DayZ-Epoch/issues/1399

**Comment by ajbboy123** [comment]
I do have that file tho, it's quite empty tho, with only 1 line:
#include "\z\addons\dayz_code\system\ca\functions\init.sqf"

Also the link in that post "https://github.com/vbawol/DayZ-Epoch/blob/master/SQF/dayz_code/system/ca/functions/init.sqf" doesn't work.

**Comment by Evocation** [comment]
this line is correct i think...

you got this at the top of your server_functions.sqf?:

```
waituntil {!isnil "bis_fnc_init"};

BIS_MPF_remoteExecutionServer = {
	if ((_this select 1) select 2 == "JIPrequest") then {
		[nil,(_this select 1) select 0,"loc",rJIPEXEC,[any,any,"per","execVM","ca\Modules\Functions\init.sqf"]] call RE;
	};
};
```

**Comment by Evocation** [comment]
ohh
ive also seen, that the line 28 is wrong in your ca\Modules\Functions\init.sqf...

it should look like this:


`if ((!isNil "BIS_fnc_init") && !_recompile) exitwith {textLogFormat["PRELOAD_ Functions already running."];};`

**Comment by ajbboy123** [comment]
> 

this line is correct i think...

you got this at the top of your server_functions.sqf?:

waituntil {!isnil "bis_fnc_init"};

BIS_MPF_remoteExecutionServer = {
    if ((_this select 1) select 2 == "JIPrequest") then {
        [nil,(_this select 1) select 0,"loc",rJIPEXEC,[any,any,"per","execVM","ca\Modules\Functions\init.sqf"]] call RE;
    };
};

Yes I do have that at the top of server_functions.sqf.

However, my ca/Modules/Functions/init.sqf only has a single line in that files which is this:
#include "\z\addons\dayz_code\system\ca\functions\init.sqf"

**Comment by ajbboy123** [comment]
I've added the hive.dll into @dayz_epoch_server folder, no idea why it wasn't in there to begin with, but now it doesn't kick me, however it just sits on the DayZ Epoch image loading screen, and in the bottom right it counts up.

**Comment by ajbboy123** [comment]
Nevermind, it just kicked me as I was typing that message, that's odd because before when I tested it, it just counted up like it was frozen.

**Comment by ajbboy123** [comment]
Hi, so I went to my server log, and found this when I got kicked:
`
if (_status == "Objec>
15:53:57   Error Undefined variable in expression: _result
15:53:57 File z\addons\dayz_server\system\server_monitor.sqf, line 280
15:53:57 "HIVE: Spawning # of Debris: 500"
15:53:57 "HIVE: Spawning # of Ammo Boxes: 3"
15:53:57 "HIVE: Spawning # of Veins: 50"
15:53:57 "Total Number of spawn locations 5"
15:53:58 "EPOCH EVENTS INIT"
15:53:58 Error in expression <ray = call compile format ["%1",_data];
_resultArray
};

server_hiveReadWriteLar>
15:53:58   Error position: <_resultArray
};

server_hiveReadWriteLar>
15:53:58   Error Undefined variable in expression: _resultarray
15:53:58 File z\addons\dayz_server\init\server_functions.sqf, line 166
15:53:58 Error in expression <y call server_hiveReadWrite;
_outcome = _result select 0;
if(_outcome == "PASS")>
15:53:58   Error position: <_result select 0;
if(_outcome == "PASS")>
15:53:58   Error Undefined variable in expression: _result
15:53:58 File z\addons\dayz_server\compile\server_spawnEvent.sqf, line 39
15:54:03 Error in expression <ray = call compile format ["%1",_data];
_resultArray
};

server_hiveReadWriteLar>
15:54:03   Error position: <_resultArray
};

server_hiveReadWriteLar>
15:54:03   Error Undefined variable in expression: _resultarray
15:54:03 File z\addons\dayz_server\init\server_functions.sqf, line 166
15:54:03 Error in expression <ey call server_hiveReadWrite;
if (count _primary > 0) then {
if ((_primary selec>
15:54:03   Error position: <_primary > 0) then {
if ((_primary selec>
15:54:03   Error Undefined variable in expression: _primary
15:54:03 File z\addons\dayz_server\compile\server_playerLogin.sqf, line 41
15:54:03 Error in expression <ray = call compile format ["%1",_data];
_resultArray
};

server_hiveReadWriteLar>
15:54:03   Error position: <_resultArray
};

server_hiveReadWriteLar>
15:54:03   Error Undefined variable in expression: _resultarray
15:54:03 File z\addons\dayz_server\init\server_functions.sqf, line 166
15:54:03 Error in expression <ey call server_hiveReadWrite;
if (count _primary > 0) then {
if ((_primary selec>
15:54:03   Error position: <_primary > 0) then {
if ((_primary selec>
15:54:03   Error Undefined variable in expression: _primary
15:54:03 File z\addons\dayz_server\compile\server_playerLogin.sqf, line 41
15:54:03 Error in expression <ray = call compile format ["%1",_data];
_resultArray
};

server_hiveReadWriteLar>
15:54:03   Error position: <_resultArray
};

server_hiveReadWriteLar>
15:54:03   Error Undefined variable in expression: _resultarray
15:54:03 File z\addons\dayz_server\init\server_functions.sqf, line 166
15:54:03 Error in expression <ey call server_hiveReadWrite;
if (count _primary > 0) then {
if ((_primary selec>
15:54:03   Error position: <_primary > 0) then {
if ((_primary selec>
15:54:03   Error Undefined variable in expression: _primary
15:54:03 File z\addons\dayz_server\compile\server_playerLogin.sqf, line 41
15:54:03 Error in expression <ray = call compile format ["%1",_data];
_resultArray
};

server_hiveReadWriteLar>
15:54:03   Error position: <_resultArray
};

server_hiveReadWriteLar>
15:54:03   Error Undefined variable in expression: _resultarray
15:54:03 File z\addons\dayz_server\init\server_functions.sqf, line 166
15:54:03 Error in expression <ey call server_hiveReadWrite;
if (count _primary > 0) then {
if ((_primary selec>
15:54:03   Error position: <_primary > 0) then {
if ((_primary selec>
15:54:03   Error Undefined variable in expression: _primary
15:54:03 File z\addons\dayz_server\compile\server_playerLogin.sqf, line 41
15:54:03 Error in expression <ray = call compile format ["%1",_data];
_resultArray
};

server_hiveReadWriteLar>
15:54:03   Error position: <_resultArray
};

server_hiveReadWriteLar>
15:54:03   Error Undefined variable in expression: _resultarray
15:54:03 File z\addons\dayz_server\init\server_functions.sqf, line 166
15:54:03 Error in expression <ey call server_hiveReadWrite;
if (count _primary > 0) then {
if ((_primary selec>
15:54:03   Error position: <_primary > 0) then {
if ((_primary selec>
15:54:03   Error Undefined variable in expression: _primary
15:54:03 File z\addons\dayz_server\compile\server_playerLogin.sqf, line 41
15:54:03 Error in expression <Player _playerObj) exitWith {

};

if ((_primary select 0) == "ERROR") exitWith >
15:54:03   Error position: <_primary select 0) == "ERROR") exitWith >
15:54:03   Error Undefined variable in expression: _primary
15:54:03 File z\addons\dayz_server\compile\server_playerLogin.sqf, line 53
15:54:03 "DEBUG VEIN: Too many objects at [5330.88,8283.38]"
15:54:03 "DEBUG VEIN: Too many objects at [3074.85,6901.72]"
15:54:03 "DEBUG VEIN: Too many objects at [2945.76,10912.4]"
15:54:10 Error in expression <ray = call compile format ["%1",_data];
_resultArray
};

server_hiveReadWriteLar>
15:54:10   Error position: <_resultArray
};

server_hiveReadWriteLar>
15:54:10   Error Undefined variable in expression: _resultarray
15:54:10 File z\addons\dayz_server\init\server_functions.sqf, line 166
15:54:10 Error in expression <y call server_hiveReadWrite;
_outcome = _result select 0;
if(_outcome == "PASS")>
15:54:10   Error position: <_result select 0;
if(_outcome == "PASS")>
15:54:10   Error Undefined variable in expression: _result
15:54:10 File z\addons\dayz_server\compile\server_spawnEvent.sqf, line 39
15:54:13 "get: STRING (76561131238077384), sent: STRING (76561131238077384)"
15:54:13 "DISCONNECT: Ajb (76561131238077384) Object: B 1-1-A:1 (Ajb) REMOTE, _characterID: 0 at loc [-7244.94,19534.5,-1.21587e-05]"
15:54:13 "ERROR: Cannot Sync Character Ajb as no characterID"
15:54:13 Client: Remote object 2:9 not found
15:54:13 Client: Remote object 2:10 not found
15:54:13 Client: Remote object 2:11 not found
15:54:15 Player Ajb disconnected.
15:54:15 BattlEye Server: Player #0 Ajb disconnected
15:54:15 Warning: Cleanup player - person 2:0 not found`

**Comment by ajbboy123** [comment]
And it spammed this for a while:
if (_status == "Objec>
15:53:57   Error Undefined variable in expression: _result
15:53:57 File z\addons\dayz_server\system\server_monitor.sqf, line 280
15:53:57 Error in expression < compile format ["%1",_data];
_status = _result select 0;

**Comment by Evocation** [comment]
you should try another hiveext.dll.... it cant call it to recive data from the sql server... also check your sql tables for correct installed shemas

**Comment by ajbboy123** [comment]
but it's the one that came with the Server Zip, the Epoch_Server zip file.

**Comment by ajbboy123** [comment]
Could you possibly link me to one that works, or a normal one or something? And what do you mean by shemas?

**Comment by Evocation** [comment]
im using this hiveext.ini:

https://github.com/NPG-Soul/Dayz-Epoch_SC999HiveExt

with shemas i mean the different data shemas in mysql for tables

**Comment by ebaydayz** [comment]
The problem you are having is the Hive .dlls do not work on Linux. User @denisio (devd on the Epoch forums) made a creative work around for it which can be found here:
https://github.com/denisio/Dayz-Epoch-Linux-Server

There is also a sub-forum dedicated to it:
http://epochmod.com/forum/index.php?/forum/50-epoch-linux-server/

If you still need help after reading through all that you should ask there or message devd. It would be nice to have Linux database support included one day, but right now it is more of a workaround. The files for it are not even hosted in this repo.
