### ISSUE TITLE
Code Review Needed

### ISSUE THREAD

**Issue by ebaydayz** [EpochModTeam/DayZ-Epoch#1676]
Some significant commits I've recently done need code review. I've checked and tested them pretty thoroughly, but better safe than sorry.

- <s>Add waitUntil in lockVault and unlockVault: https://github.com/EpochModTeam/DayZ-Epoch/commit/9311ac44796ffbd084cb777c168b6373fa98e03a</s>
- <s>Prevent duplicate objectUIDs: https://github.com/EpochModTeam/DayZ-Epoch/commit/ff4a227a1de6f4235122d5220b1f5d68430ab037</s>

I will update this as reviews are done and new commits added.

**Comment by LunaCB** [comment]
Hey, just for testing i implemented https://github.com/EpochModTeam/DayZ-Epoch/commit/9311ac44796ffbd084cb777c168b6373fa98e03a on my test and later on my live 1.0.5.1 server, so far i got no more reports of empty safes or stuff in safes like keys missing, before implementing this i got plenty a day.

**Comment by ebaydayz** [comment]
@LunaCB - Thanks. Testing on live servers is just as important as review, because it can reveal other issues we overlook. Any RPT errors or irregularities you notice are also helpful.

Glad to see some admins still alive here. :+1:
