### ISSUE TITLE
Request: Please add fishing option to lakes of chernarus

### ISSUE THREAD

**Issue by Shinesso** [EpochModTeam/DayZ-Epoch#1678]
Right now you can only fishing at ocean, could you maybe add option to fishing at lakes of chernarus like : black lake or willow lake.
Regards :)

**Comment by ebaydayz** [comment]
Yes, this is a bug with the updated vanilla player_goFishing too. I was planning to fix it soon. The pond check is currently not working. It should be simple to port the check from the water bottle fill script.

**Comment by ebaydayz** [comment]
Done:
https://github.com/EpochModTeam/DayZ-Epoch/commit/d63f48af85a5608d65b87245d25b1e6d0f476d9d
