### ISSUE TITLE
Request: Vehical Salvage % of damage

### ISSUE THREAD

**Issue by FARTBOXGAMING** [EpochModTeam/DayZ-Epoch#1720]
Hi there. I have limited knowledge of what is possible. 

To make salvage of parts more predictable, can i suggest that the Percent that the part is broken is the percent chance that the part will break when a salvage attempt is made.

EG.
If part is 10% damaged it has a 10% chance of destroying

If part is 90% damaged it has 90 % chance of destroying

I know in the SQL table it does record % damage but dont know if it would be easily called to calculate breakage percent. 

Only if somebody has time to look at it.

I don't know how the current calculation works for item being destroyed. but the above would make sense.

**Comment by ebaydayz** [comment]
This is the calculation currently:
https://github.com/EpochModTeam/DayZ-Epoch/blob/master/SQF/dayz_code/actions/salvage.sqf#L53

(random number between 0 and 1)  >  (damage * 0.9)
Example:
.5  >  (0.1 * 0.9)
.5  >  0.09
false

10% damage has 10% chance to break, 90% damage has 90% chance to break and so on.

It already works as you are requesting.
