### ISSUE TITLE
Request: AI built into mod posible?

### ISSUE THREAD

**Issue by FARTBOXGAMING** [EpochModTeam/DayZ-Epoch#1721]
I was wondering if it was posible to build AI into the mod.

If it was going to happen it would have to be 100% server side spawn I think most are anyway.

Then perhaps have a section that admins can dictate static spawn locations or if random spawns are on and off. 

Maybe even missions?

Obviously this would have to be fully customization for admins as that is a huge part of servers these dayz.

Sorry i can not offer to much technical assistance but if I dont raise the ideas they may not be thought of.

**Comment by AirwavesMan** [comment]
If I remember @ebaydayz comments correctly, we add no AI cause of the server performance. Every server admin is still able to add AI for their own.
