### ISSUE TITLE
Request: Auto ear plugs?

### ISSUE THREAD

**Issue by FARTBOXGAMING** [EpochModTeam/DayZ-Epoch#1722]
Thought it would be cool to give the admin option to have auto ear plugs.
as part of the switches that the admin can set.

Have it so when a player gets into a vehicl the earplugs apply automaticly. 

Alternatively have it as a scroll wheel so the player can decide to have auto earplugs when they get in the vehicle for the first time they get in the vehicle for that login.

still have them so they automatically remove when you get out of the vehicle. 

Lets be honest who does not use ear plugs when they get in the chopper. still have it so they hit F1 to turn on and off manually though.

**Comment by AirwavesMan** [comment]
I get your point but I think it is just pressing one simple button. to turn off or on. We dont need something automatical here. If there are enough comments for a that, Im fine with your idea but at the moment I think it is not necessary.
