### ISSUE TITLE
Request: Revise Whole Saler Building creates

### ISSUE THREAD

**Issue by FARTBOXGAMING** [EpochModTeam/DayZ-Epoch#1723]
Not sure if its posible. Thought it would be cool if there was whole sale building creates with already constructed walls. expand whats available in general
Obviously make the creates expensive  because people are paying extra because they dont have to spend the time constructing them. but an option for this would be good. you could do full walls and half walls.
Maybe call them Pallets rather than creates...

Not sure if this had been thought of or not or even mentioned b4

Thanks.

**Comment by AirwavesMan** [comment]
I think we could add a few more crates with different ammo types and perhaps weapon attachments as well. But Im not fine with full or half cinder walls or something like that. 
Every server admin is able to add new items to the trader, of course they can add the full cinder wall too. And cause of advanced trading you can buy everthing with one click, so basically we dont need the wholersaler crates any longer.

**Comment by oiad** [comment]
Wholesalers provide cheaper products with out a safezone, so theres risk vs reward.
