### ISSUE TITLE
Request: Variable to set remove Destroy plot poles on scroll wheel

### ISSUE THREAD

**Issue by FARTBOXGAMING** [EpochModTeam/DayZ-Epoch#1726]
A number of servers I have played on have removed the option to destroy  plot poles via scroll wheel all together or just by those that do not own them.

However leave the option for plot poles to take damage. 

In my experience this is a nice balance between being able to keep your plot pole safe and being vulnerable to raiders that have time to destroy it with fire power.

IF this is possible already please let me know how... I have setup a server for my friends to play on but we would like this option. 

I had a look through the code but could not see how to do it. 

Would be nice in my opinion to have the option on final release. 

Thanks in advance.

**Comment by FARTBOXGAMING** [comment]
Somthing like the last post on this page. I guess at the end of the day most people are going to have a custom self action anyway.....
http://epochmod.com/forum/topic/35332-anti-stealing-script-for-plot-poles-need-help/

My other thought was just to have a variable that the admin can choose to remove the plot pole from the deconstruct-able items. 

somthing similar to this in the above link posted by Antichrist 3rd post down


n your selfactions file change this (assuming you're using P4L)

///Allow owners to delete modulars
if(_isModular) then {

to this

///Allow owners to delete modulars dayz_allowedObjects
if(_isModular || _typeOfCursorTarget in dayz_allowedObjects) then {

And that should allow the owner and added friends to remove it, if you want just the owner to remove it you can simply look at default function in selfactions sqf and make your own thingie

**Comment by FARTBOXGAMING** [comment]
Ok did a quick and dirty on my server.

Copied the variables.sqf from dayz_code.pbo to my mission folder.

In the copie of the variables file i found this line DZE_isRemovable =

Then scrolled accross to find the plastic plot pole and removed it.

Updated my mission folder init to call the custom variables file in my mission folder instead of the dayz_code one

I know this isnt the place to post this but it is frustrating when people say found the answer and give you no clue on how they did it when you are googling for a problem.

**Comment by icomrade** [comment]
As mentioned by @FARTBOXGAMING you can remove the plot pole (Plastic_Pole_EP1_DZ) from the DZE_isRemovable array https://github.com/EpochModTeam/DayZ-Epoch/blob/master/SQF/dayz_code/init/variables.sqf#L509
