### ISSUE TITLE
Craft Lumber from woodpiles always states "Crafting in progress"

### ISSUE THREAD

**Issue by nigeyuk** [EpochModTeam/DayZ-Epoch#1727]
With the latest update i get this message when trying to Craft Lumber from woodpiles "Crafting in progress"

**Comment by ebaydayz** [comment]
Thanks, already aware of this one. Just waiting for @icomrade to fix as mentioned here:

https://github.com/EpochModTeam/DayZ-Epoch/commit/60c37e8b768b9054cef80bb6bba0b7a8d15013a5#commitcomment-18548987

**Comment by nigeyuk** [comment]
Ah sorry didn't see that, Thanks :)
