### ISSUE TITLE
Same weapon typs use different mags

### ISSUE THREAD

**Issue by AirwavesMan** [EpochModTeam/DayZ-Epoch#1738]
Since epoch has the dayz 1.8.7. base we have an weapon attachment system. It works good and I like it. But we have in epoch a lot more and different weapons than in dayz 1.8.7. 

I noticed that weapons from the same base typ uses different kind of mags. For example:

G36C_DZ - uses  G36 and G36SD mags
G36C_camo - uses G36, G36SD, 30Stang, 30Stang SD, 20 Stang and MG36 mags

Of course we can convert with right click the Stang or G36mags into each other but what about the MG36 maga? It is to unbalanced right now and all the same with most of the Stang or G36 weapons. The M8 and L85 weapons have the same problem. 

I think we should change the weapons that all types uses the same mags. What do you think?

**Comment by ebaydayz** [comment]
This is pretty easy to do for most of the new vanilla _DZ weapons. Just comment out the magazines[]={}; arrays in the configs and they will go back to inheriting the parent class magazines. Example:

https://github.com/EpochModTeam/DayZ-Epoch/blob/master/SQF/dayz_code/Configs/CfgWeapons/Rifles/G36C.hpp#L45-L49

I don't think that will cause any issues, but you might want to test some of the custom attachment versions to make sure they still fire okay with the other magazine types after the change. Also some magazine names have been changed, so make sure not to remove those. (Winchester, Enfield, shotguns, etc.)

**Comment by AirwavesMan** [comment]
Ive test that and it works pretty good. No problems found.
