### ISSUE TITLE
Small bugs

### ISSUE THREAD

**Issue by Alexandr116ru** [EpochModTeam/DayZ-Epoch#1753]
1) keyboard.sqf
need to add for check interrupt:
```
[actionKeys "TurnLeft", _interrupt] call _addArray;
[actionKeys "TurnRight", _interrupt] call _addArray;
```

2) server_onPlayerDisconnect.sqf
`diag_log format["ERROR: Cannot Sync Character [%1,%2] Still processing login",_name,_playerUID];` 
Undefined variable _name

3) setup_functions_med.sqf and player_monitor.fsm:
`playActionNow "Die"`
should be replaced for:
`switchMove "AmovPpneMrunSnonWnonDfr"`
Because AI will not attack. Sry for bad eng.

**Comment by ebaydayz** [comment]
1. Fixed. 

2. Fixed, thanks.

3. Already fixed with a better method. See the discussion here: https://github.com/DayZMod/DayZ/commit/9edca67425fac6e27f171265acd67d5071100150
