### ISSUE TITLE
Incorrect version of an server side application

### ISSUE THREAD

**Issue by Joltee** [EpochModTeam/DayZ-Epoch#1754]
I have tried everything to install a test server and connect with a client, but it's freaking impossible.

I know i'm not stupid or anything when it comes to arma servers. I have followed everything and unblocked all *dll files. 

the one thing i'm unsure of is the @Client-1.8.8-d9b2d6a-FullDevelopment folder and EpochTest-106-RC1
folder. Should i paste them in at @DayZ_Epoch_Server? so it rewrites the Addons folder?
Or should it be @DayZ_Epoch_Server\@dayz

In the description it says to rewrite so i have copied the addons folder and all files to overwrite the original 1.0.5.1 addons folder.

Please look this over and help me out and many others with same problem

**Comment by oiad** [comment]
You need to copy your original 1051 folder to a new folder called @DayZ_Epoch106
Copy all the files in @Client-1.8.8-d9b2d6a-FullDevelopment\@Dayz\Addons\ to the @DayZ_Epoch106\Addons folder and overwrite any files that you are prompted to
Copy all the files in EpochTest-106-RC1\addons\ to the @DayZ_Epoch106\Addons folder and again overwrite files when prompted.

**Comment by Joltee** [comment]
I have copied 1051 folder and renamed it to @DayZ_Epoch106.

And i have copied all the files from @Client-1.8.8-d9b2d6a-FullDevelopment\@Dayz\Addons\
and i overwrited all the older files.

Then i copied all the files from  EpochTest-106-RC1\addons to @DayZ_Epoch106\Addons folder and overwrited all files again.

Still same problem.

And yes i have changed my config to valdiate "0"

Tried on different computer as well, same problem there.

 I also tried to clear all old cache mp files. Still the same.

**Comment by Joltee** [comment]
if i check my log RPT log. it seems to be problems. I think it has to do with database.

12:33:20 "z\addons\dayz_code\system\REsec.sqf:Monitoring Remote Exe..."
12:33:22 "HIVE: Starting"
12:34:31 Error in expression <ray = call compile format ["%1",_data];
_resultArray
};

onPlayerDisconnected "[>
12:34:31   Error position: <_resultArray
};

onPlayerDisconnected "[>
12:34:31   Error Undefined variable in expression: _resultarray
12:34:31 File z\addons\dayz_server\init\server_functions.sqf, line 138
12:34:32 Error in expression <y call server_hiveReadWrite;
_outcome = _result select 0;
if (_outcome == "PASS">
12:34:32   Error position: <_result select 0;
if (_outcome == "PASS">
12:34:32   Error Undefined variable in expression: _result
12:34:32 File z\addons\dayz_server\system\server_monitor.sqf, line 24
12:34:32 "SERVER FPS: 0.22695  PLAYERS: 1"
12:34:32 Error in expression <ray = call compile format ["%1",_data];
_resultArray
};

**Comment by vbawol** [comment]
did you install the c++ 2015 for vs redistributable? and make sure the zip file was not blocked before extracting?
https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by Joltee** [comment]
lol omg, the zip was blocked :dancer:

**Comment by Joltee** [comment]
Still same problem tho :( Tried to re-install on both server & client, problem still remains.

**Comment by icomrade** [comment]
make sure you unblocked the dll and installed VCC redist 2015 as well as a fresh DB from the SQL folder. https://raw.githubusercontent.com/EpochModTeam/DayZ-Epoch/master/Server%20Files/SQL/epoch.sql You may convert an existing DB, but I would recommend against it, unless you know how to troubleshoot, for a test server.

**Comment by Joltee** [comment]
Going to try more later. I removed 1.0.6 and tried 1.0.5 again and that is working like a charm. So i don't know whats wrong, have you guys actually tested the latest files from here?

**Comment by icomrade** [comment]
Yes, it works...

**Comment by ebaydayz** [comment]
It looks like you either aren't using the new HiveExt.dll or don't have the new Microsoft Visual C++ Redistributable installed. I had to install the x86 version. It didn't work with the x64 for me. @icomrade if it does require the x86 one we should probably mention that in the instructions. A lot of people probably assume x64 since that's what their OS is.

**Comment by Joltee** [comment]
Problem solved, thanks @ebaydayz. The problem was not having x86 version of Visual C++ redist.
