### ISSUE TITLE
partly filled waterbottle refill not working

### ISSUE THREAD

**Issue by nidico100** [EpochModTeam/DayZ-Epoch#1765]
I didn't find anything about that bug, so I just want to say it exists. When you have f.e. a waterbottle 5oz you can't fill it up.
And what about using an Outhouse as water source, so you can have a water source in your base.
I added both things to the water_fill.sqf (my skills in programming are not that best so it's not optimised, just programmed that it works)
Here's the file:
[water_fill.zip](https://github.com/EpochModTeam/DayZ-Epoch/files/478222/water_fill.zip)

**Comment by icomrade** [comment]
Outhouses aren't water sources they are just boxes over a hole in the ground.

Water bottle filling was fixed for 1.0.6 here: https://github.com/EpochModTeam/DayZ-Epoch/commit/88c7d7d28beafd089e783459339ed4012b4a29d0
