### ISSUE TITLE
Error while buying vehicles!

### ISSUE THREAD

**Issue by higgibaby** [EpochModTeam/DayZ-Epoch#1800]
Nice work! Server is working perfectly!

The RPT is almost clean! I found a problem:

Have a look!

`"Trader Menu: Lenny (76561198067477778) purchased 1x SUV_Camo into Gear at trader city Stary for 2 10oz Gold"
Server: Object 3:271 not found (message 94)
Error in expression < _array select 5;
			_pos = _worldspace select 1;
			_txt = getText (configFile >
  Error position: <select 1;
			_txt = getText (configFile >
  Error select: Type String, expected Array,Config entry`

Thx - have fun!

**Comment by higgibaby** [comment]
Delete, please!

**Comment by ebaydayz** [comment]
That code does not exist in the 106 files, so I'm guessing it is due to some third party script you added. Again, please do not report issues with third party scripts here.
