### ISSUE TITLE
Hunter Zombie Texture Issue

### ISSUE THREAD

**Issue by schwanzkopfhegel** [EpochModTeam/DayZ-Epoch#1805]
For me the hunter zombie texture seems to be mixed up.

![hunterz23wphx](https://cloud.githubusercontent.com/assets/24301205/20806433/2fe2a368-b7fb-11e6-88ab-6645a16a6c6c.jpg)

![hunterz1sxoq2](https://cloud.githubusercontent.com/assets/24301205/20806438/34faa328-b7fb-11e6-8c61-714f29bbfb81.jpg)

**Comment by DeVloek** [comment]
I've seen this issue on another server too, which had additional mods such as Overwatch and Namalsk but there shouldn't be a conflict.

**Comment by ebayShopper** [comment]
This was a bug with the updated vanilla zombie configs which is why you see it in Overwatch too (they use 1.8 configs).

Fixed eacc362
![20161202104756_1](https://cloud.githubusercontent.com/assets/7761693/20840184/5d4ff7ce-b87d-11e6-8981-338c72f89b07.jpg)
