### ISSUE TITLE
Refuel from gas stations w/generator

### ISSUE THREAD

**Issue by Helios27** [EpochModTeam/DayZ-Epoch#1806]
Hi,

Not sure if this is still the place to post bugs, but if it is....

:Vanilla files - 
When placing a fueled and started generator at a Gas Station fuel pump and selecting 'Fill Vehicle' all that happens is an infinite action loop with no change to vehicle fuel.
I get the rolling message 'filling Hilux etc' and the character animation, but no change in the vehicles fuel amount.

**Comment by ebayShopper** [comment]
Yes, this is the place to post bugs. It is easiest to keep track when each bug is a separate git issue, thanks.

This was a mistake in e398250

Fixed with 5d1a693.

Tested both refuel at gas station with generator and refuel with engine on using fuel truck. Both working as intended now.
