### ISSUE TITLE
Epoch 1.0.6a Bug

### ISSUE THREAD

**Issue by schwanzkopfhegel** [EpochModTeam/DayZ-Epoch#1808]
A lot of players replied, that if they place a Vault too near to a Tree they aren't able to acces it anymore.
If they cut the tree, they are able again, until the tree is there again (after a restart).
I'm not sure whether this bug was there before the update 106a came...

**Comment by ebayShopper** [comment]
Neither the safe model nor anything in the addAction code for safes or trees has changed. This is just the normal Arma cursorTarget problem. `CursorTarget` registers null when it shouldn't.

**Comment by oiad** [comment]
This has always been a problem, not something that 106 has introduced

**Comment by schwanzkopfhegel** [comment]
Couldn't remember that it was this extreme.. Sorry then for wasting your time..
