### ISSUE TITLE
1.0.6 spawning with no parachute occasionally

### ISSUE THREAD

**Issue by oiad** [EpochModTeam/DayZ-Epoch#1809]
Hey, a few of my players (and my self) have spawned occasionally without a parachute and plummeted to our death. No .RPT issues that I can see on my end when it happened to me. 

These are the related settings to this, NO ess spawn menu (ebay plz!) just the defaults.

```
dayz_spawnselection = 1;
dayz_paraSpawn = true;
DZE_HaloAltitudeMeter = true;
```

**Comment by ebayShopper** [comment]
I've halo spawned probably a hundred times in the test build and never had my chute deleted.

Most likely infistar or a third party script is responsible. I would check your RPT for any cleanup or delete messages for parachutes. Also check for any killing a hacker messages which may be doing setDamage on the parachute.

The default halo function always creates "ParachuteWest" so it shouldn't be an issue with the class. 
https://github.com/EpochModTeam/DayZ-Epoch/blob/master/SQF/dayz_code/compile/BIS_fnc/fn_halo.sqf#L253

**Comment by oiad** [comment]
I checked server RPT, No mention of anything being removed or hacker messages.

Infistar is VERY good at telling you when it doesn't like something so it deletes it.

When it happened to me, I didn't see the parachute at all, I loaded in and started falling
