### ISSUE TITLE
Full Cinderwall snap/vector bug

### ISSUE THREAD

**Issue by DeVloek** [EpochModTeam/DayZ-Epoch#1813]
When building a snapped & pitched/banked full cinderwall, it appears in a wrong position (after pressing space to build). Server restart doesn't fix it. All other building parts work fine as far as we've tested them.

Steps to reproduce:

1. Build a full cinderwall
2. snap another full cinderwall to the first one
3. pitch or bank the 2nd wall in any direction
4. press space to build -> it will spawn in wrong position

Screenshots:

snapped and pitched:
![fullcinderwall1](https://cloud.githubusercontent.com/assets/24300064/21023124/81f4c06c-bd7f-11e6-845c-26012dd5c004.jpg)

after pressing space:
![fullcinderwall2](https://cloud.githubusercontent.com/assets/24300064/21023126/81fc3c20-bd7f-11e6-8df8-34cdda47e22d.jpg)

after restart:
![fullcinderwall3](https://cloud.githubusercontent.com/assets/24300064/21023125/81fbb002-bd7f-11e6-9984-98f89abf5a60.jpg)

**Comment by icomrade** [comment]
Just so happened I am currently testing snap building. I can reproduce this, so i'll work on fixing. Thanks
