### ISSUE TITLE
crossbow crafting, arrow & quiver combining bugs

### ISSUE THREAD

**Issue by DeVloek** [EpochModTeam/DayZ-Epoch#1814]
I found 3 bugs with crossbows, arrows and quivers:

1. J crafting menu: crafting a compound crossbow doesn't work. Required items are equip_Crossbow_Kit + equip_crossbow_stock, but even if you got those items it doesn't start crafting, no error message given.
Tested without any weapon in my inventory and with a weapon on back but hands free.
Btw, equip_crossbow_stock doesn't seem to be in any of the loot tables, only equip_Crossbow_Kit is. Is there another item that looks like the stock but has a different classname? If so I couldn't find it anywhere.

2. Making a quiver from 4, 5 or 6 arrows gives you a full quiver with 12 arrows. When you try to combine 7 arrows or more, only 6 of those arrows are combined, again to a full 12-arrow quiver.

3. When you combine only 3 arrows or less, you get a quiver with the correct amount of arrows. But when you use "fill quiver" while you have another partly filled quiver but no single arrows, it happens that either one quiver duplicates, or the other quiver loses arrows. Either way, you don't end up with the correct amount of arrows (which should be the same as before).

None of these errors show anything in the RPT log.

**Comment by ebayShopper** [comment]
1. A lot of vanilla crafting recipes in the configs are not functional yet. Either the models, pictures or textures for them are not complete, so they have been disabled or parts removed from the loot tables. The crossbow kit should not be in the loot tables. I went ahead and commented it out where it was.

2. I tested combining 4, 5 and 6 1Rnd_Arrow_Wood. They all gave me a partially filled quiver with the correct amount of arrows. When creating a quiver from 7 arrows it gives me a quiver with 6 arrows and 1 separate arrow remains. You can combine two 6 rnd quivers into a 12 rnd quiver.

3. Using "fill quiver" with two partly filled quivers and no loose arrows in my inventory does nothing, just says "you have added 0 arrows to the quiver".

Not sure how you are reproducing the last two unless you modified `player_fillquiver` or `player_createquiver`. If someone else can reproduce those on a stock server feel free to reopen.
