### ISSUE TITLE
Arrows stuck floating in air

### ISSUE THREAD

**Issue by DeVloek** [EpochModTeam/DayZ-Epoch#1815]
Sometimes arrows get stuck in the air if you keep shooting at the same spot.
![arrowsonfire1](https://cloud.githubusercontent.com/assets/24300064/21035892/8e858b20-bdc2-11e6-8fba-a43b4c2fd852.jpg)

**Comment by ebayShopper** [comment]
Fixed the destruction effect, but the arrows stuck floating in the air near the school has been a bug in vanilla for a while. It is some issue with the setPos, attachTo or memoryPoint.

https://github.com/EpochModTeam/DayZ-Epoch/blob/master/SQF/dayz_code/compile/player_crossbowBolt.sqf#L27

![20161209142724_1](https://cloud.githubusercontent.com/assets/7761693/21061843/1d73f976-be1c-11e6-9a79-9c75942bf862.jpg)
