### ISSUE TITLE
Server sync problem

### ISSUE THREAD

**Issue by AirwavesMan** [EpochModTeam/DayZ-Epoch#1822]
Ive found a major bug in the server syncing object after restart when a player disconnects while the rtp shows Server error: Player without identity A Man. After disconnecting Ive got a lot Ref to nonnetwork object errors and while joining again the server I got this error and the server stopped syncing any object:

`"HIVE: Starting"
["TIME SYNC: Local Time set to:",[2016,12,14,11,3],"Fullmoon:",false,"Date given by HiveExt.dll:",[2016,12,14,11,3]]
Error in expression <ll compile str formatText["%1", _data];
_resultArray
};

onPlayerDisconnected "[>
  Error position: <_resultArray
};

onPlayerDisconnected "[>
  Error Undefined variable in expression: _resultarray
File z\addons\dayz_server\init\server_functions.sqf, line 153
"HIVE: Request sent"
Error in expression <t _myArray,_result];
};
};
} else {
if (_val > 0) then {
_fileName = _key call s>
  Error position: <_val > 0) then {
_fileName = _key call s>
  Error Undefined variable in expression: _val
File z\addons\dayz_server\system\server_monitor.sqf, line 63
Error in expression <nt";
_myArray = [];
_val = 0;
_status = _result select 0; 
_val = _result select>
  Error position: <_result select 0; 
_val = _result select>
  Error Undefined variable in expression: _result
File z\addons\dayz_server\system\server_monitor.sqf, line 49
"HIVE: BENCHMARK - Server_monitor.sqf finished streaming any objects in 0.0190125 seconds (unscheduled)"
"Total Number of spawn locations 6"
Error in expression <;
};

diag_log ("HIVE: Streamed " + str(_val) + " objects");

{
private ["_objec>
  Error position: <_val) + " objects");

{
private ["_objec>
  Error Undefined variable in expression: _val
File z\addons\dayz_server\system\server_monitor.sqf, line 81
"0:0 Debug: Starting script WeatherEffects.sqf..."
"SERVER FPS: 45  PLAYERS: 1"
"Spawning an infected camp (Camp2_Small) at [8193.6,22014.6,0]"
"Spawning an infected camp (Camp1_Small) at [6939.76,10084.4,0]"
"Spawning an infected camp (Camp3_Small) at [10455.4,12262.7,0]"
"DEBUG: Spawning a care package (Misc_cargo_cont_net3) at [5476.64,6895.59,0] with 11 items."`

Tested with and without infistar. Can anyone confirm that?

Steps to reproduce:

- Restart the server
- After restart joining as player
- when the rpt shows these lines : Player without identity A Man, close the game
- rejoing the server
- the rtp shows this line again: Player without identity A Man
- the error mentioned above occurs

**Comment by oiad** [comment]
I got this tonight as well, I assumed I disconnected from database during object stream, it looks like the hive was unresponsive on my end. 

Maybe we need a retry/reconnect?

I didn't try and reproduce it but I can give it a go tomorrow

**Comment by AirwavesMan** [comment]
I can reproduce it at any time I restart the server with a complete clear vanillia 1.0.6 version.

**Comment by ndavalos** [comment]
"Server error: Player without identity" messages are normal on restart.

What version of MySQL are you using?

**Comment by AirwavesMan** [comment]
I know that "Server error: Player without identity" messages are normal, but when a player disconnected while he got this message, the server stops syncing the objects. If the player just log in and what until the server is loaded everything is fine.
Where can I find what my hoster is using for a  MySQL version?

**Comment by ndavalos** [comment]
Just execute this query:
SELECT VERSION();

You may have to turn off SSL to keep connections. Although that shouldn't be a problem if you're using a version prior to 5.7.

**Comment by AirwavesMan** [comment]
Im using version 5.6.35. How can I turn of SSL?

**Comment by ndavalos** [comment]
5.6 shouldn't have it enabled. It was turned on by default in 5.7
Have you turned on the informational messages in hive and taken a look at that yet?

**Comment by oiad** [comment]
I'm running mysql57-server-5.7.15_1 and I had this problem so I don't think it's related to SSL or not

**Comment by ndavalos** [comment]
I'm getting this on a fresh setup on my laptop. From looking at the full rpt I believe it's missing c++ runtimes. It doesn't appear that hive is initializing at all. I'll investigate further when I get a chance and report back.

**Comment by ndavalos** [comment]
@icomrade I know you messaged me a month or two ago about the c++ runtimes, do you remember exactly which ones you ended up installing?

**Comment by oiad** [comment]
On a fresh install I installed 2008-current x86 and x64 to let me connect to get the hive.

I believe the links for the runtimes are in one of the readmes. Possibly test server dir

**Comment by icomrade** [comment]
info is here https://github.com/EpochModTeam/DayZ-Epoch/blob/master/Server%20Files/Readme.md

**Comment by ndavalos** [comment]
Yeah I probably missed one of those.

**Comment by LWBUK** [comment]
I also had this issue yesterday. The first player to join disconnected before fully loading in.  I had lots of non ref to network errors and this

`18:51:45 Error in expression <ll compile str formatText["%1", _data];
_resultArray
};

onPlayerDisconnected "[>
18:51:45   Error position: <_resultArray
};

onPlayerDisconnected "[>
18:51:45   Error Undefined variable in expression: _resultarray
18:51:45 File z\addons\dayz_server\init\server_functions.sqf, line 153
18:51:45 "HIVE: Request sent"
18:51:45 Error in expression <t _myArray,_result];
};
};
} else {
if (_val > 0) then {
_fileName = _key call s>
18:51:45   Error position: <_val > 0) then {
_fileName = _key call s>
18:51:45   Error Undefined variable in expression: _val
18:51:45 File z\addons\dayz_server\system\server_monitor.sqf, line 63`

The result was the server loaded, but minus any  buildables, vehicles either sever spawned or player owned or storage objects.  Everything else seem to function as normal. 
I restarted the server, logged in myself first and everything was fine.

**Comment by ndavalos** [comment]
You need to install all the runtimes icomrade linked. All of them...the 2008, 2010, 2012, 2013 and 2015 runtimes. Some of the things in the link won't install because you need visual studio installed, so skip the ones that complain.

**Comment by oiad** [comment]
This is the same error that myself and airwaves man has gotten. (I am running all the runtimes)

I've switched back to _legacystreamingmethod = true till a fix can be found.

It seems like the hive stream with the new method either disconnects before or during a stream, I put in some checking and _val can become null, maybe we need a simple reconnect to the hive if this occurs

**Comment by ndavalos** [comment]
Sounds like file permissions then, the new method writes one file that gets loaded and executed all at once if I'm not mistaken. My problem with it was missing runtimes on my laptop, once I installed those it started working.

If you are able to grant "everyone" write access to the server's install directory see if that corrects the problem.

**Comment by oiad** [comment]
The problem is, this doesn't happen every single time, maybe 1 out of 20 restarts this will happen to me, or you can force it to do it like @AirwavesMan mentioned in the start of the post

**Comment by ndavalos** [comment]
I wonder if hive is stepping on itself. I wrote my own dll for it and write the whole file at once instead of like by line

**Comment by Clanwarfare** [comment]
I had this happen to me yesterday. Twice in a row, unfortunately. I've been running 106 for about a week now. Running all run times. I too had to switch to _legacystreamingmethod = true until a fix can be found. I have my server on a 2 hour restart cycle. So that would be 2 out of 84 restarts so far? Didn't wan't players to freak out, hence why I switched to Legacystreamingmethod. 

 0:37:20 Error in expression <ll compile str formatText["%1", _data];
_resultArray
};

onPlayerDisconnected "[>
 0:37:20   Error position: <_resultArray
};

onPlayerDisconnected "[>
 0:37:20   Error Undefined variable in expression: _resultarray
 0:37:20 File z\addons\dayz_server\init\server_functions.sqf, line 153
 0:37:20 "HIVE: Request sent"
 0:37:20 Error in expression <t _myArray,_result];
};
};
} else {
if (_val > 0) then {
_fileName = _key call s>
 0:37:20   Error position: <_val > 0) then {
_fileName = _key call s>
 0:37:20   Error Undefined variable in expression: _val
 0:37:20 File z\addons\dayz_server\system\server_monitor.sqf, line 63
 0:37:20 "HIVE: BENCHMARK - Server_monitor.sqf finished streaming any objects in 0 seconds (unscheduled)"
 0:37:20 "Total Number of spawn locations 10"
 0:37:20 Error in expression <nt";
_myArray = [];
_val = 0;
_status = _result select 0; 
_val = _result select>
 0:37:20   Error position: <_result select 0; 
_val = _result select>
 0:37:20   Error Undefined variable in expression: _result
 0:37:20 File z\addons\dayz_server\system\server_monitor.sqf, line 49

**Comment by ebayShopper** [comment]
I am able to reproduce it consistently by myself both with legacy streaming on and off.
1. Start server.
2. Connect, click OK button in lobby to start loading screen.
3. Wait a couple seconds for the hive stream to start, then force kill your client.

The server continues trying to spawn objects after the only player has disconnected, but the RPT is immediately spammed with `Ref to nonnetwork object` for every object it attempts to spawn. Example log:
```
17:11:08 "HIVE: Starting"
17:11:08 ["TIME SYNC: Local Time set to:",[2012,8,2,12,11],"Fullmoon:",true,"Date given by HiveExt.dll:",[2016,12,23,12,11]]
17:11:08 "HIVE: Request sent"
17:11:08 "HIVE: Streamed 309 objects"
17:11:09 Ref to nonnetwork object 20ca6080# 1055363: hilux_dshk.p3d
17:11:09 Ref to nonnetwork object 20c010c0# 1055364: skodovka_red.p3d
17:11:09 Ref to nonnetwork object 20bc10c0# 1055365: uaz.p3d
17:11:09 Ref to nonnetwork object 20b990c0# 1055366: gnt_c185.p3d
17:11:09 Ref to nonnetwork object 23ff4100# 1055367: jetskiyanahui.p3d
17:11:09 Ref to nonnetwork object 23fd5600# 1055368: backpack_acr_small.p3d
17:11:09 Ref to nonnetwork object 23f90100# 1055369: uh1h.p3d
17:11:09 Ref to nonnetwork object 23f590c0# 1055370: v3s_open.p3d
17:11:09 Ref to nonnetwork object 23ec90c0# 1055371: hilux1_civil_3_open.p3d
17:11:10 Ref to nonnetwork object 23e7d0c0# 1055372: skodovka.p3d
17:11:10 Ref to nonnetwork object 23e2c100# 1055373: m1151_m2_gpk.p3d
17:11:10 Ref to nonnetwork object 23dde080# 1055374: tt650.p3d
17:11:10 "SERVER FPS: 21  PLAYERS: 0"
17:11:10 Ref to nonnetwork object 23dc7040# 1055375: jetskiyanahui.p3d
17:11:10 Ref to nonnetwork object 23daeb00# 1055376: backpack_us_auv.p3d
17:11:10 Ref to nonnetwork object 248f3040# 1055377: atv.p3d
17:11:10 Ref to nonnetwork object 24856080# 1055378: mi_8amt.p3d
17:11:10 Ref to nonnetwork object 24853040# 1055379: jetskiyanahui.p3d
17:11:10 Ref to nonnetwork object 248410c0# 1055380: ikarus.p3d
17:11:10 Ref to nonnetwork object 24850100# 1055381: gnt_c185.p3d
17:11:10 Ref to nonnetwork object 247b6080# 1055382: smallboat_1.p3d
17:11:10 Ref to nonnetwork object 2477d0c0# 1055383: uaz_mg.p3d
17:11:10 Ref to nonnetwork object 2477c100# 1055384: jetskiyanahui.p3d
17:11:10 Ref to nonnetwork object 24714100# 1055385: uh1y.p3d
17:11:10 Ref to nonnetwork object 246710c0# 1055386: ural.p3d
17:11:10 Ref to nonnetwork object 245b8100# 1055387: kamaz.p3d
17:11:10 Ref to nonnetwork object 245df040# 1055388: v3s_open.p3d
17:11:11 Ref to nonnetwork object 243c5600# 1055395: backpack_tk_alice.p3d
17:11:11 Ref to nonnetwork object 243fb040# 1055394: suv.p3d
17:11:11 Ref to nonnetwork object 243af040# 1055397: usec_ch53_e.p3d
17:11:23 Ref to nonnetwork object 263f1600# 1055688: metal_floor.p3d
17:11:23 Ref to nonnetwork object 26404100# 1055689: ah6x.p3d
17:11:23 Ref to nonnetwork object 263f0100# 1055690: safe.p3d
< truncated >
17:11:23 "HIVE: BENCHMARK - Server_monitor.sqf finished streaming 309 objects in 15.08 seconds (unscheduled)"
17:11:23 "Total Number of spawn locations 6"
17:11:24 "DEBUG: Spawning an infected camp (Camp2_Small) at [3590.79,12988.6,0]"
17:11:24 Ref to nonnetwork object 20d05600# 1055692: a_tent.p3d
17:11:28 "CRASHSPAWNER: Starting crash site spawner. Frequency: 25±20 min. Spawn chance: 0.75"
17:11:28 "CRASHSPAWNER: Spawning crash site (CrashSite_UN) at [2884.97,6755.87,0] with 6 items."
17:11:28 Ref to nonnetwork object 26f06400# 1055791: mi8_un.p3d
17:11:28 Ref to nonnetwork object 26f05d00# 1055792: dummyweapon.p3d
17:11:28 Ref to nonnetwork object 26f04800# 1055793: medical_freezbox.p3d
17:11:52 "HIVE: Vehicle Spawn limit reached!"
17:11:52 "HIVE: Spawning # of Debris: 500"
17:11:53 Ref to nonnetwork object 30d3eb00# 1055798: skodovka_wrecked.p3d
17:11:56 Ref to nonnetwork object 30d3e400# 1055799: datsun01t.p3d
17:11:56 Ref to nonnetwork object 30d3dd00# 1055800: datsun02t.p3d
17:11:56 Ref to nonnetwork object 30d3d600# 1055801: datsun01t.p3d
17:11:56 Ref to nonnetwork object 30d3cf00# 1055802: garbage_misc.p3d
17:11:57 Ref to nonnetwork object 30d3c800# 1055803: garbage_misc.p3d
17:11:57 Ref to nonnetwork object 30d27200# 1055804: uaz_wrecked.p3d
17:11:57 Ref to nonnetwork object 30d26b00# 1055805: hmmwv_wrecked.p3d
17:11:57 Ref to nonnetwork object 30d24100# 1055806: ural_wrecked.p3d
17:11:58 Ref to nonnetwork object 30d09d00# 1055807: fort_barricade_ep1.p3d
17:11:58 Ref to nonnetwork object 30d09600# 1055808: ural_wrecked.p3d
```

Now when a player reconnects we get:
```
17:12:16 Server error: Player without identity steve (id 1782574744)
17:12:19 "PRELOAD_ Functions\init [[<No group>:0 (FunctionsManager)],any]"
17:12:19 "MPframework inited"
17:12:19 "dayz_preloadFinished reset"
17:12:21 "Res3tting B!S effects..."
17:12:21 "HIVE: Starting"
17:12:21 ["TIME SYNC: Local Time set to:",[2012,8,2,12,12],"Fullmoon:",true,"Date given by HiveExt.dll:",[2016,12,23,12,12]]
17:12:21 Error in expression <ll compile str formatText["%1", _data];
_resultArray
};

onPlayerDisconnected "[>
17:12:21   Error position: <_resultArray
};

onPlayerDisconnected "[>
17:12:21   Error Undefined variable in expression: _resultarray
17:12:21 File z\addons\dayz_server\init\server_functions.sqf, line 152
17:12:21 "HIVE: Request sent"
17:12:21 Error in expression <t _myArray,_result];
};
};
} else {
if (_val > 0) then {
_fileName = _key call s>
17:12:21   Error position: <_val > 0) then {
_fileName = _key call s>
17:12:21   Error Undefined variable in expression: _val
17:12:21 File z\addons\dayz_server\system\server_monitor.sqf, line 63
17:12:21 "HIVE: BENCHMARK - Server_monitor.sqf finished streaming any objects in 0.000991821 seconds (unscheduled)"
17:12:21 "Total Number of spawn locations 6"
17:12:21 Error in expression <nt";
_myArray = [];
_val = 0;
_status = _result select 0; 
_val = _result select>
17:12:21   Error position: <_result select 0; 
_val = _result select>
17:12:21   Error Undefined variable in expression: _result
17:12:21 File z\addons\dayz_server\system\server_monitor.sqf, line 49
17:12:21 "z\addons\dayz_code\system\REsec.sqf:Monitoring Remote Exe..."
17:12:21 "SERVER FPS: 49  PLAYERS: 1"
17:12:22 "DEBUG: Spawning an infected camp (Camp3_Small) at [3251.15,12719.8,0]"
17:12:22 "DEBUG: Spawning an infected camp (Camp2_Small) at [9186.03,6446.16,0]"
17:12:23 "DEBUG: Spawning an infected camp (Camp1_Small) at [9661.04,7792.86,0]"
17:12:23 "DEBUG: Spawning a care package (Misc_cargo_cont_net1) at [4101.55,6757.93,0] with 4 items."
17:12:23 "DEBUG: Spawning a care package (Misc_cargo_cont_net1) at [12601.3,10779.7,0] with 6 items."
17:12:23 "DEBUG: Spawning a care package (Misc_cargo_cont_net1) at [2181.11,8925.17,0] with 4 items."
17:12:23 "DEBUG: Spawning a care package (Misc_cargo_cont_net2) at [2598.83,7105.91,0] with 7 items."
17:12:24 "DEBUG: Spawning a care package (Misc_cargo_cont_net3) at [6450.18,6990.32,0] with 6 items."
17:12:24 "DEBUG: Spawning a care package (Misc_cargo_cont_net1) at [4221.31,9746.11,0] with 4 items."
17:12:24 "CRASHSPAWNER: Starting crash site spawner. Frequency: 25±20 min. Spawn chance: 0.75"
17:12:24 "CRASHSPAWNER: Spawning crash site (CrashSite_RU) at [6706.48,9360.82,0] with 7 items."
```
Notice the objects are spawning okay without ref to nonnetwork object now. So server_monitor is definitely having issues. You can see from my logs the "HIVE: Starting" appears twice, so server_monitor is running twice, and this line is not exiting when it should:
```sqf
if (!isNil "sm_done") exitWith {}; // prevent server_monitor be called twice (bug during login of the first player)
```

I'll look into it if @icomrade doesn't know the issue.

**Comment by icomrade** [comment]
I'll have to re-add and test, but I won't be able to do it before Christmas is over with, most likely

**Comment by ebayShopper** [comment]
Adding back the child 400 call from 1051 to kill the HIVE when the 302 call fails fixed it for me. Now after reconnecting all objects are spawned normally and saving again.

I also added an exit in server_monitor, so the RPT doesn't get spammed with all objects when this happens:
7e34173

Please leave a comment if you are able to reproduce it again after applying that commit. Note you still get the agent creation failed message for the traders, but they spawn normally after a player reconnects.
