### ISSUE TITLE
Generator Item saving issue

### ISSUE THREAD

**Issue by schwanzkopfhegel** [EpochModTeam/DayZ-Epoch#1831]
Hey,

we have found out that Generators have the same Problem as storage units, like  I have descriped in:
https://epochmod.com/forum/topic/42891-epoch-106-bugs/#comment-282835

Steps to reproduce:

1. start server
2. connect
3. build Generator
4. place item into it
5. restart server
repeat steps 1-5 until bug happens..

As always, tested on vanilla server.

**Comment by icomrade** [comment]
are there any errors, or does gear just not save?

**Comment by schwanzkopfhegel** [comment]
No Errors. The items just do not safe in the Generator after a Server restart.
I was able to reproduce this **everytime**, but there are no Errors in any log.
