### ISSUE TITLE
Death Message

### ISSUE THREAD

**Issue by schwanzkopfhegel** [EpochModTeam/DayZ-Epoch#1833]
Hey,

I have found out that if you die by a Zombie you get a kill message like this
"playerxy" crowbar-symbol "unknown" (0m)

The playerxy got killed by a zombie but the Message says that it was unknown player with a crowbar with a distance of 0m.

my settings:
```
DZE_DeathMsgChat = "none"; //"none","global","side","system" Display death messages in selected chat channel.
DZE_DeathMsgDynamicText = true; // Display death messages as dynamicText in the top left with weapon icons.
DZE_DeathMsgRolling = false; // Display death messages as rolling messages in bottom center of screen.
DZE_DeathScreen = true; // True=Use Epoch death screen (Trade city obituaries have been amended) False=Use DayZ death screen (You are dead)
```

**Comment by oiad** [comment]
`
client log:
"Player_Death: Body:B 1-1-B:1 (salival) BodyName:salival Infected:0 SourceName:unknown SourceWeapon: Distance:0 Method:zombie"
"DeathMessage: salival died from the infected."

server log:
11:17:24 "salival (player uid redacted) salival died from the infected. @108029 [10838.9,12412.8,0] nearby: None"
`

**Comment by ebayShopper** [comment]
It would be helpful if you had the server death message RPT log or client Player_Death RPT log. But I did just fix two issues that were causing death messages to show incorrectly sometimes:
2c8f236
d509c15
