### ISSUE TITLE
Fuelbarrel

### ISSUE THREAD

**Issue by schwanzkopfhegel** [EpochModTeam/DayZ-Epoch#1834]
Hey,

- The German translation of Fuelbarrel when fuelling it is missing. It says Kraftstoffkanister instead of Kraftstofffass. @AirwavesMan said that this failure also happens in the english version (Fuelbarrel <->fuelcan)

- If you fill up the fuelbarrel it only takes 40 litres out of the fueltank..

**Comment by oiad** [comment]
You are right on both of these, just tested. I will do some fixes for these.

It looks like the code defaults to ItemJerrycan for everything in that script text wise.
