### ISSUE TITLE
Waterbottle

### ISSUE THREAD

**Issue by schwanzkopfhegel** [EpochModTeam/DayZ-Epoch#1835]
Hey,

when fuelling a waterbottle via right click option theres a huge delay (arround 5-15 seconds) until it starts with the animation and filling process..
It seems like its depending on Server FPS and Player count.

**Comment by oiad** [comment]
Hi,

I tried to reproduce this, I loaded down the server and client (rar'd up a 22gb movie on both in background) to simulate lag and tried filling a water bottle at prud, it happens instantly for me.

You do the "put down" animation which lasts till you move. You get the "You have filled...." text instantly even with lag (about 20 fps client)

**Comment by schwanzkopfhegel** [comment]
Weird..
@AirwavesMan was able to reproduce this.. 
I'll try it again on a vanilla server. Will report later.

**Comment by AirwavesMan** [comment]
I was not able to reproduce that large lag time but about 1,5s. It takes more time as water filling from other sources.

**Comment by schwanzkopfhegel** [comment]
Okay.. I can reproduce this issue everytime at this lake marked on the map:
![20161227231758_1](https://cloud.githubusercontent.com/assets/24301205/21509710/dc8fea54-cc8b-11e6-8622-02315562ffb9.jpg)
Its better at other lakes like the one at Pobeda.

**Comment by oiad** [comment]
I was able to reproduce this with more testing as @schwanzkopfhegel suggested.

The problem I see is we are using a null array to search nearestObjects with and from what @ebayShopper has told me in the past that is very intensive. My testing showed that I was seeing about 5-10 seconds for a search for water holes with the epoch script as is.

My version took this down to < 0.2 ms average with my system being lagged down so it's a huge improvement.

**Comment by oiad** [comment]
Just a note for this. After talking to @ebayShopper my fix will only work for Chernarus since it's the only map that has been manually edited to have waterholeproxy (which my fix relies on) so unfortunately unless we get other people fixing other maps (tavi etc) then my fix won't make it into Epoch.
