### ISSUE TITLE
Waterbottle crafting

### ISSUE THREAD

**Issue by schwanzkopfhegel** [EpochModTeam/DayZ-Epoch#1838]
Hey,
I have found out that if you are using a fully filled boiled waterbottle for crafting, you do not get boiled water back. You only get back a x*oz filled water bottle.

AND: (I do not know if this is wanted)
You can use right click option to drink out of a empty soda can (you need a watersource, like a lake to drink).
This is not very realistic I think. But I don't know wether this also got fixed with https://github.com/EpochModTeam/DayZ-Epoch/commit/4d3f707417c1d69f81625c35a2db2beb8199e957

**Comment by oiad** [comment]
With the first part, what are you using the boiled water for crafting? (I haven't done any crafting)

i.e how would I reproduce it properly

**Comment by schwanzkopfhegel** [comment]
You are not forced to use boiled water for it.
For example: You want to get goldbars out of goldore. You take a waterbottle and the goldore and right click on the goldore to craft it into goldbars

**Comment by oiad** [comment]
I can't find that translation in any of the english texts, is it in german and you translated to english?

**Comment by oiad** [comment]
`		<Key ID="STR_EPOCH_PLAYER_58">
			<English>Key crafting needs a fire within 3 meters.</English>
			<German>Kopieren eines Schlüssels ist nur innerhalb 3 Meter eines Feuers möglich.</German>`

Is this the string you are referring to @schwanzkopfhegel ?

**Comment by schwanzkopfhegel** [comment]
Nope. I was talking about the crafting of goldbars out of Goldore.

**Comment by oiad** [comment]
That is the string that returns when you craft from ore to bars and not near a fire

**Comment by schwanzkopfhegel** [comment]
no. its the string that returns when you craft a key..

> Key crafting

**Comment by oiad** [comment]
Yeah, I realise that, but it's the only string in the epoch stringtable that matches that

**Comment by schwanzkopfhegel** [comment]
<Key ID="STR_EPOCH_PLAYER_149">
			<English>Crafting needs a %1 within %2 meters</English>
			<German>Zur Herstellung wird ein(e) %1 innerhalb von %2 benötigt.</German>

**Comment by oiad** [comment]
Okay, that works. So what should the german string for that be, then?

**Comment by schwanzkopfhegel** [comment]
<German>Zur Herstellung wird ein(e) %1 innerhalb von %2 meter(n) benötigt.</German>
I do not know how other stuff got solved, but I would translate it like that. Maybe @AirwavesMan could help here?

**Comment by oiad** [comment]
It's hard to know, so many people have done translations and some have been copied over from other translations so the context may be wrong.

I'll push changes for that localization anyway.

**Comment by AirwavesMan** [comment]
The translation above is correct. I will do a separate german translation for all new commits.

**Comment by schwanzkopfhegel** [comment]
Oh.. you was a bit too fast. I edited my post.
https://github.com/EpochModTeam/DayZ-Epoch/commit/989c50b

**Comment by oiad** [comment]
@AirwavesMan If you could check my pull request and give me the updated translations for the ones I have updated?

**Comment by AirwavesMan** [comment]
Ive added the needed changes for the german strings

**Comment by oiad** [comment]
Thanks @AirwavesMan

**Comment by schwanzkopfhegel** [comment]
> I have found out that if you are using a fully filled boiled waterbottle for crafting, you do not get boiled water back. You only get back a x*oz filled water bottle.

Just a small Addition/Correction:
Seems like the description for a boiled x*oz waterbottle is missing.

**Comment by oiad** [comment]
I just spawned a water bottle (boiled) in my inventory, it has the long and short description properly showing it's boiled (there's only an ItemWaterBoiled)

**Comment by schwanzkopfhegel** [comment]
I think I did not explain it as extensivly as I should I have..
Now after you got the boiled water bottle, you need to start crafting with it. (For example craft gold ore to gold bars). After crafting you get back a 9oz waterbottle.
This waterbottle isnt descriped as boiled. The crafting process destroys the boiling of the water bottle. (Atleast in the description of the waterbottle)
