### ISSUE TITLE
Pain

### ISSUE THREAD

**Issue by schwanzkopfhegel** [EpochModTeam/DayZ-Epoch#1839]
Hey,
it seems like there is no way to get in pain. 
For me it showed that the only way to get in pain, is getting overbudened.

Did someone get in pain? I haven't handled to get in pain.

**Comment by icomrade** [comment]
I don't see an issue with the code. It may be more rare than before to be put into pain, however. https://github.com/EpochModTeam/DayZ-Epoch/blob/d509c15c829b19b97685d747bbbd58f2cc6ea8dc/SQF/dayz_code/compile/fn_damageHandler.sqf#L269-L281

**Comment by schwanzkopfhegel** [comment]
Rare seems to mean no pain at all. Asked my hole community: No one needed Painkillers until now.

**Comment by AirwavesMan** [comment]
I know and we had that problem a few months before. Ive changed the fn_damageHandler.sq to increased the in pain chance but nothing happend at all. No in pain whatever or what kind of damage Ive got. Painkiller are right now absolutely useless. Perhaps you can test it for yourself

**Comment by icomrade** [comment]
Okay, so somewhere along the line, probably in 1.8.8, the pain effect was changed. it is still there, but it's now a form of severe weapon sway as opposed to shaking. like I said, it's been made more intermittent, but players should still experience its effects fairly noticeably

**Comment by AirwavesMan** [comment]
As you said, players should, but they reporting that they dont use painkillers at all because of no in pain effect. Ive tested being shoot from different weapons and getting damage from almost all sources. I cant trigger it. I'm a bit confused, is it only me with this issue?

**Comment by DeVloek** [comment]
There is definetely a pain effect, just like icomrade said.

In old Epoch, you had a "shaking" effect every few seconds. This is still there, but only for pain that comes from being overburdened and very low blood. For the normal pain, a "weapon swaying" effect is now displayed but it only happens every few minutes, so someone might not even notice it if they aren't playing in 1st person all the time (I do). Taking a painkiller removes this effect.

It seems like the swaying happens more frequently when low on blood, and it's conflicting with the old shaking effect, which results in some glitchy combination of sway and shake.

To be honest, I and some other players don't like this new swaying effect at all, we'd rather have the old pain effect back, as it gives the player better feedback on his medical condition. Also when both effects conflict it just looks weird.

**Comment by oiad** [comment]
I think it should be a config option personally so admins can change it instead of a distribution set change

**Comment by ebayShopper** [comment]
Same issue @bchawke reported here:
https://github.com/DayZMod/DayZ/issues/786

Here is the commit where it was changed:
https://github.com/DayZMod/DayZ/commit/a42427f0b38d1128ebb0285690bf71c2babceecb

It's probably best to use the original, since that's what everyone knows. I agree with @bchawke the sway should maybe be reserved for dehydration or something. It is too subtle, so it mostly just confuses players that have no idea they are in pain.

**Comment by ebayShopper** [comment]
I asked R4Z0R and he is good with reverting it, so I'll make the change in vanilla too. 

You can always overwrite the file if you want to change it by replicating the scheduler folder structure in your mission as icomrade explained before. But it looks like most people are confused by the sway effect and want the old one back.

**Comment by AirwavesMan** [comment]
After testing, Im not sure it works as it should. Im definitely in pain. In the DB medical table inpain is true and I got a message when I suffering pain(the message was only for testing) but the cam shake effect is not there. Im not sure a shake effect for infection is still there but if yes, this cam shake is not there too. Can someone please test it. I know you changed it back to normal but it looks like there is a problem with camshake or something like that.

**Comment by ebayShopper** [comment]
Works fine for me. Just set `r_player_inpain = true;` and you will see it shake every two seconds. It's only visible in first person, same as 1051 and old dayz. You have to remove the scheduler code as shown in e4d48cb or it will get overwritten with those values.

**Comment by AirwavesMan** [comment]
@ebayShopper thx for your answer. I dont know how but in the arma profile settings the entry cameraShake=1; change from to 1 to 0. After changing it back I have the cam shake effect finally. 

So if anyone else have the same issue like me, be sure that in the arma profile class Difficulties, camera shake is set to 1, cameraShake=1;
