### ISSUE TITLE
Spamming "Drink" addAction at waterholes/sources lags server/client

### ISSUE THREAD

**Issue by clontarfx** [EpochModTeam/DayZ-Epoch#1840]
When spamming the Drink addAction at waterholes/sources, the client seems to "queue" all the commands, resulting in huge delays in the action being performed by the player.

It also seems to create a processing delay on the server which seems to increase/worsen as the drink addAction continues to be spammed. Multiple players spamming this command at once can cause game-breaking delays in server-side processing and client response.

**Comment by icomrade** [comment]
This is very similar to the findings in https://github.com/EpochModTeam/DayZ-Epoch/issues/1835 we are looking at it already
