### ISSUE TITLE
Filling up ammo

### ISSUE THREAD

**Issue by schwanzkopfhegel** [EpochModTeam/DayZ-Epoch#1842]
1
You are able to fill up your ammo with the help of a vault.
Steps to reproduce:

1. get some not fully filled ammo
2. put it into a vault
3. close vault
4. open vault
5. ammo is filled up again
___________________________________
2
You are able to fill up your ammo with the help of a backpack.
Steps to reproduce:
1. get some not fully filled ammo
2. put it into your backpack
3. log off
4. log in
5. ammo is filled up again

**Comment by icomrade** [comment]
Known issue, we cannot fix this since there is no command to return magazine count inside of containers. In ArmA 3 such a command exists, but we are helpless in A2 OA
