### ISSUE TITLE
Full cinder wall vector issues

### ISSUE THREAD

**Issue by oiad** [EpochModTeam/DayZ-Epoch#1846]
Hey,

Further to this commit: https://github.com/EpochModTeam/DayZ-Epoch/commit/f34d1820bb1d6109e79237eec3a64070f5949dd0 I'm still having issues with full cinder walls and vectoring.

This ONLY happens to full cinder walls, none of the other cinder products do this, very definitely a terrain issue.

When you vector on flat ground, the wall vectors perfectly: http://images.akamai.steamusercontent.com/ugc/199681384957973853/806A011B2339DB6E2BD5754690C3B5E9FC7DC5B3/

When you vector on not flat ground it gets a gap: 

Ghost is fine: http://images.akamai.steamusercontent.com/ugc/199681384957974147/2B16EAA785565A094096C8A09918C432D3504791/
when placed: http://images.akamai.steamusercontent.com/ugc/199681384957974551/24077B3105F5423B002193BD9AA4D842A04F96BC/

**Comment by Clanwarfare** [comment]
Oh, good. I'm not the only one with this issue. Players on my taviana server are reporting the same exact thing. I was able to replicate it and only seems to happen with full walls as well. Taviana has almost no flat ground and mostly build on mountain sides. It's sucks because most of my players are OCD with building and I just cant seem to sort it even when applying some alterations to 
case "CinderWall_DZ": { _buildOffset = [(_vUp select 0) * 1.686, (_vUp select 1) * 1.686,0]; };

**Comment by icomrade** [comment]
The offset system is annoying, you are correct about issues on non-flat surfaces. I'm not entirely sure how to set this variable reliably. it's also interesting that the wooden full wall does not have this issue despite the dimensions being the same...

**Comment by icomrade** [comment]
Not sure if this is an issue with the snap points offset configs, or the offset in the .sqf we are referencing. setting the value to something static, like 0.27, works in some cases, but doesn't in others.  Building perpendicularly to the slope of the terrain below the object results in the object building normally with Z offset of 0, however building parallel to the terrain causes the vectored object to be shunted in the direction of the slope.

Considering we don't use GetPos or SetPos, the two commands that compensate for slope, I am kind of stuck here.

**Comment by oiad** [comment]
@icomrade I tested this quite a bit, works great on flat, massively sloped or a small slope. 

Good fix.

**Comment by icomrade** [comment]
Closing, thanks.
