### ISSUE TITLE
Minus in advanced trading exploid!

### ISSUE THREAD

**Issue by stijngun12** [EpochModTeam/DayZ-Epoch#1862]
Whenever you want to buy something in the trader. Try to buy -50.

The worth of the item selling price is getting copieed into your inventory -50x times.

For example: -50 for buying a safe grants me 50 briefcases.

**Comment by LunaCB** [comment]
https://github.com/EpochModTeam/DayZ-Epoch/commit/5cb485ccfbaa9a32716e857fea6626977ba49c6b

**Comment by stijngun12** [comment]
thanks @LunaCB
