### ISSUE TITLE
how to remove gems when trading?

### ISSUE THREAD

**Issue by stijngun12** [EpochModTeam/DayZ-Epoch#1864]
Hello dayz-epoch team,

I want to remove the function of gems. I use them in a different way on my server.
Currently when i'm trading i gain instead of 2 briefcases i gain 1 gem..  
Could you show me how i can reset it back to the older versions?

- Chargedlight1

**Comment by ebayShopper** [comment]
Set DZE_GemWorthArray=[]; in mission\init.sqf to disable return change in gems.
https://github.com/EpochModTeam/DayZ-Epoch/blob/master/SQF/dayz_code/configVariables.sqf#L62
