### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by stijngun12** [EpochModTeam/DayZ-Epoch#1868]
Is the coin currency already added into the newest patch? 

I cant find any plugin that update their code. is it just as simple to adjust Z_SingleCurrency from false to true?

Ofcourse ill have to update my selling prices etc...

**Comment by ebayShopper** [comment]
No. The framework is there to support database saving of single currency, but it is not fully implemented.

For help and support questions please use the forum. This Github is more for reporting bugs, issues and suggestions. 
https://epochmod.com/forum/forum/1-arma-2/
