### ISSUE TITLE
SUV_Camo not upgradeable?

### ISSUE THREAD

**Issue by coresync2k** [EpochModTeam/DayZ-Epoch#1869]
Hi,

i test it on my Live and Testserver, Camo SUV should not be upraded? All others works with Offroad Perfomance etc. but on Camo SUV "you must sit in driver seat first" everytime,

**Comment by ebayShopper** [comment]
Yes, it is upgradeable. You need to get in the driver seat first for the locality to change. This is how it has always worked:
https://github.com/EpochModTeam/DayZ-Epoch/blob/master/SQF/dayz_code/compile/player_upgradeVehicle.sqf#L31

I just checked and the camo SUV does upgrade after I get in the driver seat.
