### ISSUE TITLE
Cars cant unlock from inside

### ISSUE THREAD

**Issue by coresync2k** [EpochModTeam/DayZ-Epoch#1872]
Hi,

i test it on a few Cars, always if im "unlock" my vehicle, go into it, and "lock it from inside" i cant unlock it from inside?
anyone else have this problem?

it is a standart fn_selfactions.sqf nothing changed

**Comment by coresync2k** [comment]
hm now it works with changing variables
"s_player_lockUnlockInside_cursorTargetrl" to -> s_player_lockUnlockInside_ctrl
now it works from inside O_o

**Comment by oiad** [comment]
Hello, there is no such variable in this github repo called: ```s_player_lockUnlockInside_cursorTargetrl```

**Comment by coresync2k** [comment]
what? oO wait ^^

**Comment by coresync2k** [comment]
i checked the repo again, and you are right, wtf Oo close
