### ISSUE TITLE
Error in zombie_findOwner.sqf

### ISSUE THREAD

**Issue by AirwavesMan** [EpochModTeam/DayZ-Epoch#1877]
After log out I got these error. Im using the current dayz_code build not only 1.0.6

Error in expression <= 	_this select 0;
_position = 		_agent modelToWorld [0,0,0];
_secondHand = fals>
  Error position: <modelToWorld [0,0,0];
_secondHand = fals>
  Error modeltoworld: Type Array, expected Object
Error in expression <server\compile\zombie_findOwner.sqf"

deleteVehicle _unit;
>
  Error position: <deleteVehicle _unit;
>
  Error deletevehicle: Type Array, expected Object
File z\addons\dayz_server\compile\zombie_findOwner.sqf, line 6

**Comment by AirwavesMan** [comment]
Unfortunately, this is not fixed. I still have that error with the currenty day_code. Only when logging out or dying next to zombies.

**Comment by ebayShopper** [comment]
What is the exact error you are getting? If it is the same one you posted above then your dayz_code is not up to date on the client or server.

**Comment by AirwavesMan** [comment]
I tested some things and found out that the Namalsk mod is the problem when it is load with epoch 1.0.6.1.

I used for that test on a non modded server the newest dayz_code and server files without infistar. When you load your server with Namalsk you will get that error from above from my first post. Loading with overwatch and origins 1.7.9.5. is fine. It is only Namalsk.

**Comment by ebayShopper** [comment]
Are you loading Namalsk before Epoch in the -mod order? It should be like it shows in the example .bat:
`"-mod=@namalsk;@DayZ_Epoch;@DayZ_Epoch_Server;"`
https://github.com/EpochModTeam/DayZ-Epoch/blob/master/Server%20Files/Config-Examples/DayZ_Epoch_instance_15_namalsk.bat

**Comment by AirwavesMan** [comment]
Im loading it in your order you mentioned. Namalks has it's own zombies besides the normal epoch zombies, perhaps that could be the problem?

**Comment by ebayShopper** [comment]
I searched the Namalsk addons and the only place I see Namalsk calling zombie_agent.fsm is in its zombie_generate.sqf in dayz_code. That should be overwritten by the 1.0.6.1 zombie_generate if it is loaded in the correct order. You can run `diag_log (zombie_generate);` to make sure.

I don't see zombie_agent.fsm hardcoded anywhere in their configs. Make sure you aren't calling zombie_agent.fsm in any of your other files.

**Comment by AirwavesMan** [comment]
Which version of namalsk did you use? Im using the one from the dayz lauchner. I will test it again but I have not used any side script only the vanilla server build and dayz code.

**Comment by AirwavesMan** [comment]
So the client rpt shows me that:

{#line 1 "z\addons\dayz_code\compile\zombie_generate.sqf"
#line 1 "z\addons\dayz_code\loot\Loot.hpp"

#line 1 "z\addons\dayz_code\Configs\CfgLoot\LootDefines.hpp"

#line 4 "z\addons\dayz_code\loot\Loot.hpp"

#line 1 "z\addons\dayz_code\compile\zombie_generate.sqf"


private ["_bypass","_position","_unitTypes","_radius","_method","_agent","_maxlocalspawned","_doLoiter","_wildspawns","_maxControlledZombies",
"_cantSee","_isOk","_zPos","__FILE__","_fov","_safeDistance","_farDistance","_xasl","_eye","_ed","_deg","_skipFOV","_wildSpawns","_tooClose",
"_type","_loot","_array","_rnd","_lootType","_index","_weights","_loot_count","_favStance","_lootGroup"];

_position = _this select 0;
_doLoiter = _this select 1; 
_unitTypes = _this select 2; 

_bypass = _this select 3;

_maxlocalspawned = round(dayz_spawnZombies);

if (r_player_divideinvehicle > 0) then {
_maxlocalspawned = round(dayz_spawnZombies / r_player_divi
{#line 1 "z\addons\dayz_code\compile\zombie_generate.sqf"
#line 1 "z\addons\dayz_code\loot\Loot.hpp"

#line 1 "z\addons\dayz_code\Configs\CfgLoot\LootDefines.hpp"

**Comment by ebayShopper** [comment]
Yes, that is the correct version.

So somewhere else zombie_agent.fsm or zombie_findOwner is being called with `[position, object]` when it should just be called with `[object]` (same as passing `_this` from init event handler). I checked the Namalsk files from dayz_launcher and I do not see that happening anywhere.

**Comment by AirwavesMan** [comment]
The Namalsk config.cpp has it twice.

		class Eventhandlers
		{
			init = "_this call zombie_initialize;";
			local = "if(_this select 1) then {[(position (_this select 0)),(_this select 0),true] execFSM '\z\AddOns\dayz_code\system\zombie_agent.fsm'};";
		};

**Comment by ebayShopper** [comment]
Ok, in the version I'm looking at all the custom namalsk zombies and mutants have this:
```sqf
class eventHandlers {
    init = "_this execVM ""\nst\ns_modules\mutants\scripts\mut_follow.sqf""; _this execVM ""\nst\ns_modules\mutants\scripts\zomb_sounds.sqf"";";
};
```
But I'll add back zombie_initialize and make it handle both types. I was going to do that anyway so zombie_agent.fsm can be easily overwritten by admins.

**Comment by ebayShopper** [comment]
Done with 097a02b.
