### ISSUE TITLE
Convert Ammo

### ISSUE THREAD

**Issue by schwanzkopfhegel** [EpochModTeam/DayZ-Epoch#1878]
The mags of the FAL, DMR and MK17 in the game are the same size and caliber (7.62x51mm NATO), so shouldn't we add the possibility to convert them into each other, like M4 and G36 mags too. (20rnd FAL mag to 20rnd DMR mag etc.)

info:
https://en.wikipedia.org/wiki/M14_rifle
https://en.wikipedia.org/wiki/FN_SCAR
https://en.wikipedia.org/wiki/FN_FAL

**Comment by AirwavesMan** [comment]
I think we should leave it as it is. The 7.62x51mm is a powerful ammo and if we allow to convert in every magazine typ that uses 7.62x51mm, it is not that good for the server balance. There is no need to get an FN Fal mag if I have an DMR mag. I had that feature on my server a year ago with all overwatch weapons, it was good for a fast pvp server but not good for the server balance at all.
I like the idea but only as toggleable feature.

**Comment by Basti890** [comment]
If you want to have it realistic, the best way would be to allow fill up DMR Magazines with other Magazines of the same caliber (7.62x51 NATO) In real you would also empty found magazines with ur caliber to refill your own magazines.

**Comment by AirwavesMan** [comment]
I do not think this is a good idea to add this as I answered before. Server admins can add this on their own if they want.
