### ISSUE TITLE
Side chat 106

### ISSUE THREAD

**Issue by looonytoonz** [EpochModTeam/DayZ-Epoch#1879]
In 105 server admins were allowed to use side chat and in 106 are not... is there a way to change this?

**Comment by oiad** [comment]
How do you mean allowed to use side chat? You mean for voice?

**Comment by looonytoonz** [comment]
yes

**Comment by oiad** [comment]
Anyone could use side chat (blue) for voice in 1.0.5.1 not just admins, we added disabling certain channels.

See this configVariables line for info on how to disable/enable channels for voice chat: https://github.com/EpochModTeam/DayZ-Epoch/blob/master/SQF/dayz_code/configVariables.sqf#L35

**Comment by looter809** [comment]
I believe what you are thinking of is what infiSTAR had in it's code. Epoch is not using infiSTAR so it is not detecting the admins defined in infiSTAR...

**Comment by looonytoonz** [comment]
on my 1.0.5.1 server side chat was disabled but admins could still talk over side chat... maybe that did have something to do with infistar as i did have that installed 

is there a way to enable it for just admins ?

**Comment by oiad** [comment]
Not as it stands, you would need to modify it, it's not hard but I don't think it would be something that would be added

**Comment by looonytoonz** [comment]
fair enough....

**Comment by oiad** [comment]
@looonytoonz I have messaged you on epochmod with a howto on how to make it work for admins, you can close this issue

**Comment by ebayShopper** [comment]
The variable `DZE_DisabledChannels` is per client, so all you need to do is run a script that removes side chat from it on your client.
