### ISSUE TITLE
gem to gold conversion...

### ISSUE THREAD

**Issue by looonytoonz** [EpochModTeam/DayZ-Epoch#1881]
FOR the 106 update...

i cant seem to find a list of prices for the gems to add to the trader in order to allow conversion back to gold.. so far i have manually managed to get the following information to which i am not even 100% sure of:

2 gold briefs = 1 obsidian
3 gold briefs = 1 amethyst
4 gold briefs = 1 citrine
?? = 1 topaz
?? = 1 ruby
?? = 1 sapphire

**Comment by oiad** [comment]
https://github.com/EpochModTeam/DayZ-Epoch/blob/master/SQF/dayz_code/configVariables.sqf#L63
