### ISSUE TITLE
Whole sky is fire after a chopper sometimes crashes

### ISSUE THREAD

**Issue by oiad** [EpochModTeam/DayZ-Epoch#1883]
This has been an issue for quite a few years, is this anything we can fix? It dissapears when you deleteVehicle the crashed chopper, seems to mainly show up after you log in so I guess it's JIP based

http://images.akamai.steamusercontent.com/ugc/182794383468640339/CA880D1D138B41A1FFCF070288110838B0E9AFC4/

**Comment by icomrade** [comment]
This was fixed, hence the BIS_effects folder (which contained the fix), however one of the patches re-broke it, even with the fixed files.

**Comment by oiad** [comment]
I thought I remembered it being fixed before, Oh well, "Just arma things"

**Comment by oiad** [comment]
https://forums.bistudio.com/topic/188702-a2a2oa-beta-corepatch-01032016/?do=findComment&comment=3152373

@icomrade Fixed correctly in next corepatch

**Comment by icomrade** [comment]
If the fix in epoch 1.0.6.1 works (I've tested it repeatedly in a local
server without issue), then I see no need to remove it, even if it's fixed
properly with the corepatch. the included bis_effects folder and files
fixed the issue for years, but the recent versions of the corepatch broke
it again. If/when the time comes for the corepatch to be pushed to stable,
we can consider removing the epoch fix.

**Comment by icomrade** [comment]
Actually, some of the changes I made like no explosion, eject/kill on vehicle destroy, and fixing combat actually rely on a custom bis_effects file. So I'll just merge the fixes in
