### ISSUE TITLE
Option to disallow remove plot pole

### ISSUE THREAD

**Issue by AirwavesMan** [EpochModTeam/DayZ-Epoch#1886]
I would like to add the feature, that disallows the option to remove the plot pole if it is not the owner or in the plot friend list. Im not sure it is already included but I think it is not.

**Comment by looter809** [comment]
That would be nice. The new selfActions is a bit complicated for doing that.

**Comment by oiad** [comment]
I have this on my server, it's pretty easy to implement, I'm just not sure if @ebayshopper or @icomrade want it merged in.

Am happy to show how I did it, though.

I basically moved all buildables to be only able to be removed if you're on the plot

**Comment by ebayShopper** [comment]
The default is only the object owner (player who built the object), plot owner (player who build the plot pole) or a plot friend can remove any object on the plot. So it sounds like it already works the way you are asking for @AirwavesMan . If not, all you need to do is change this line to how want it:

https://github.com/EpochModTeam/DayZ-Epoch/blob/master/SQF/dayz_code/compile/fn_selfActions.sqf#L403
https://github.com/EpochModTeam/DayZ-Epoch/blob/master/SQF/dayz_code/compile/fn_check_access.sqf#L136-L145

**Comment by oiad** [comment]
From memory it's not a permissions thing, plot pole class is in builtitems config class which means anyone can remove it. I.e same with sandbags etc (see the block above your first link @ebayshopper _isdestructable)

I had to change that block and i made a new variable of items that can't be removed from memory

**Comment by icomrade** [comment]
Plot pole removal is an essential game play feature for base takeovers. This way, when you remove the pole all of the previous plot users and owner are deleted, then you can claim ownership, which converts the surrounding objects to be owned by you.
It is not similar in any way to the removal of another base piece 

I know some servers don't allow base takeover, so adding a toggle is a good option. However, base takeover/plot removal should be enabled by default

**Comment by oiad** [comment]
https://github.com/EpochModTeam/DayZ-Epoch/blob/master/SQF/dayz_code/init/variables.sqf#L530

https://github.com/EpochModTeam/DayZ-Epoch/blob/master/SQF/dayz_code/compile/fn_selfActions.sqf#L394

Plot pole is part of dze_isremoveable which is not in the fn_check_acess code block

**Comment by ebayShopper** [comment]
My mistake, you are correct @oiad. Plot poles do not inherit from ModularItems, so `_isModular` is false for them:
https://github.com/EpochModTeam/DayZ-Epoch/blob/master/SQF/dayz_code/Configs/CfgVehicles/DZE/Prop_Defs.hpp#L446-L447

But they are in `DZE_isRemovable` by default, so they can be removed by anyone with a crowbar:
https://github.com/EpochModTeam/DayZ-Epoch/blob/master/SQF/dayz_code/init/variables.sqf#L530
https://github.com/EpochModTeam/DayZ-Epoch/blob/master/SQF/dayz_code/compile/fn_selfActions.sqf#L394-L395

So a setting to enable plot poles and other classes in DZE_isRemovable be treated the same as ModularItems is a good idea.

**Comment by ebayShopper** [comment]
Done with 6aa5c9b.

If I missed something or this is not doing everything you want please leave a comment.
