### ISSUE TITLE
1.0.6.1 RC1 Testing Bugs/Issues

### ISSUE THREAD

**Issue by ebayShopper** [EpochModTeam/DayZ-Epoch#1891]
The **[[1.0.6.1 RC1 test build]](https://github.com/EpochModTeam/DayZ-Epoch/tree/master/Test%20Build)** is now available. Please report any bugs or issues here.

For the list of changes that need testing see:
- **[1.0.6.1 Change Log](https://github.com/EpochModTeam/DayZ-Epoch/blob/master/CHANGE%20LOG%201.0.6.1.txt)**
- **[Full list of commits since 1.0.6 release (November 30th, 2016)](https://github.com/EpochModTeam/DayZ-Epoch/compare/Release_1.0.6...master)**

Please do not post issues with third party scripts here. Include relevant errors from client or server RPT:

```
Client RPT: C:\Users\YourName\AppData\Local\ArmA 2 OA\arma2oa.RPT (enable show hidden files in Windows to see it)
Server RPT: FTP\server config directory\arma2oaserver.RPT

Make sure client is not started with -noLogs param (Settings > uncheck -noLogs and check -showScriptErrors in DayZLauncher).
```

I made a basic user interface for quickly testing most things without worrying about compatibility conflicts: 
**[[You can get it here]](https://github.com/ebaydayz/TestKit).**

**Comment by oiad** [comment]
Hi,
This is for my current 1.0.6 production server, players have reported that vehicles have been resetting to character ID 0, purchased vehicles or claimed (I run vehicle key claiming/changing).

No external scripts mess with changing to char ID 0 apart from the mysql function/event to unlock key'd vehicles that no longer have a key (which is enabled). Players still have had the key on them when the vehicle resets.

Sounds very much like this one: https://epochmod.com/forum/topic/9596-bought-vehicles-losing-keys/#comment-66399

**Comment by icomrade** [comment]
are you running this event? https://github.com/EpochModTeam/DayZ-Epoch/blob/8ace89ff4d3a62aadf401ed6b1a6bc2f86a5931f/Server%20Files/SQL/add_recommended_mysql_events.sql#L107-L129

**Comment by oiad** [comment]
Yeah, it is enabled and running.

Users are reporting that it happens to vehicles they have just purchased and still have the key for so I don't know how that would be triggering that.

(but it's the only thing I can think of that would be doing it) I log vehicle hotwiring and deaths and they aren't showing up there either

**Comment by icomrade** [comment]
I wonder if there is a limitation in FindVehicleKeysCount that is causing this behavior

**Comment by ndavalos** [comment]
That was an issue with the scripts for the DB in 105 for the first servers I admin'd. It after I looked, the scripts that were zeroing out safes and doors on the database were also hitting vehicles. Maybe look at your other scripts.

**Comment by oiad** [comment]
I have not noticed the safes/doors zeroing, I run the normal 0000 safe and red 00 lockbox one, that seems to be running normally

**Comment by oiad** [comment]
https://epochmod.com/forum/topic/43270-wierd-database-objectuid-behavior/#comment-286505 this problem looks the same as my problem, @ebayShopper chimed in on this, too

**Comment by oiad** [comment]
Found this bug, too: 
`20:29:30 Error in expression <,rSAY,["trap_bear_0",60]] call RE;

if (_entity isKindOf "Animal") then {
_entit>
20:29:30   Error position: <_entity isKindOf "Animal") then {
_entit>
20:29:30   Error Undefined variable in expression: _entity
20:29:30 File z\addons\dayz_code\traps\beartrap.sqf, line 61

`

**Comment by AirwavesMan** [comment]
I get this client error somertimes. I cannot reproduce it.

`Error in expression <0) == 		1} do
{
_sub = dz_loot_weighted select (_def select 1);
_def = dz_loot_d>
  Error position: <select (_def select 1);
_def = dz_loot_d>
  Error Zero divisor
File z\addons\dayz_code\loot\select.sqf, line 32
Error in expression <floor random count _weighted);

while {(_def select 0) == 		1} do
{
_sub = dz_lo>
  Error position: <_def select 0) == 		1} do
{
_sub = dz_lo>
  Error Undefined variable in expression: _def
File z\addons\dayz_code\loot\select.sqf, line 30
Error in expression <andom count _sub);
};

_result set [_i, _def];
};

_result>
  Error position: <_def];
};

_result>
  Error Undefined variable in expression: _def
File z\addons\dayz_code\loot\select.sqf, line 36
Error in expression <select 0;
_vehicle = objNull;


switch (_lootInfo select 0) do
{

case 		2:
{
_v>
  Error position: <_lootInfo select 0) do
{

case 		2:
{
_v>
  Error Undefined variable in expression: _lootinfo
File z\addons\dayz_code\loot\spawn.sqf, line 32`

Im not sure it is an epoch bug without extra mods like overwatch or origins. Some ideas?

**Comment by icomrade** [comment]
Do you have anyour improperly defined or empty loot groups? The variable should be defined every run. You can use diag-log to get the loot groups and other info in the scripts mentioned

**Comment by ebayShopper** [comment]
@AirwavesMan did you add any custom loot groups or building pos on the server? If not it may be a missing comma somewhere in one of the new building loot positions added in 7857272.

**Comment by AirwavesMan** [comment]
@ebayShopper Ive added both, custom loot groups and building pos, to my server. I think it could be the loot pos then. I tried to work with the diag_log but currently without success. I will look into my loot pos now.

**Comment by AirwavesMan** [comment]
The study body action is visible when the players are alive. Not sure I missed something from the last commit with that but it looks like it needs the alive check?

**Comment by icomrade** [comment]
Bodyname, the variable checked is only set in player-death.sqf. live players should not have it set

**Comment by ebayShopper** [comment]
Make sure some third party script you are running does not `setVariable "bodyName"` on live players. The only place it is set in the default files is in server_playerDied on corpses.

This change was made after the test build d416ae8.
