### ISSUE TITLE
Vehicle(Tank) Gunner Seat Radar doesn't  work

### ISSUE THREAD

**Issue by ANDREJJJ** [EpochModTeam/DayZ-Epoch#1899]
I have notice that in this new version 1.0.6 of epoch some tanks at gunners seat doesn't  have radar why is that is it some bug or is it disabled somewhere so i can enable it?
Example i tried FV510 Warrior in epoch 1.0.5.2 radar in gunner seat works perfect, epoch 1.0.6 radar doesn't work.
If you know anything about it please inform me about it because i could find anything about it.
Thank you

**Comment by icomrade** [comment]
This is most likely because the command has radar, not the gunner. this is the same behavior for a lot of the tanks and IFVs in ArmA

**Comment by icomrade** [comment]
I apologize, I was mistaken, this is now fixed in the commit: https://github.com/EpochModTeam/DayZ-Epoch/commit/cf661380b67ff57ed1efbc8bb761c4b0fe205671

**Comment by ANDREJJJ** [comment]
I have tested this new code and still radar isnt working for FV510 Warrior and tried BMP2 same as warrior.

**Comment by icomrade** [comment]
this is a config change, not code, and as such it cannot be used as a drop in fix. You'll have to wait until release for this to work, as it requires a rebuild of the DayZ_Code.pbo. here is a photo showing radar works as gunner in a BAF_FV510_W
http://i.imgur.com/roNLhB9.jpg

**Comment by ANDREJJJ** [comment]
ok good well at less one bug less :)
