### ISSUE TITLE
Trying to install for my 1.0.5.1 server.

### ISSUE THREAD

**Issue by Neurok** [EpochModTeam/DayZ-Epoch#1901]
Hello I'm trying to install this on my 1.0.5.1 Overpoch server. The installation for 1.0.5.1 is removed though how do I go about installing this on my server?

**Comment by ebayShopper** [comment]
1.0.5.1 is no longer being supported. Here are instructions to update:
https://github.com/EpochModTeam/DayZ-Epoch/tree/master/Server%20Files
