### ISSUE TITLE
[1.0.6.1] Teleported To Debug On Death

### ISSUE THREAD

**Issue by clontarfx** [EpochModTeam/DayZ-Epoch#1903]
When a player is killed, they are sometimes teleported to debug. All input is disabled.

RPT

21:54:50 Error in expression <died set [count dayz_died, _playerID];

_newObject setVariable ["bodyName",_play>
21:54:50   Error position: <_newObject setVariable ["bodyName",_play>
21:54:50   Error Undefined variable in expression: _newobject
21:54:50 File z\addons\dayz_server\compile\server_playerDied.sqf, line 20

**Comment by ebayShopper** [comment]
That means player_death did not send the corpse object correctly from the client. The current infistar has conflicts with 1.0.6.1 player death as I described here:
https://epochmod.com/forum/topic/43412-1061-issues-so-far/#comment-287740
