### ISSUE TITLE
Death message problems

### ISSUE THREAD

**Issue by eikas** [EpochModTeam/DayZ-Epoch#1907]
says player suicided when they were actually killed by another player.
sometimes shows the first attacker name and distance from victim, not the killer name and killer distance.

**Comment by ndavalos** [comment]
Messages were working well until the 1.0.6.1 update. Been getting reports of people showing as being run over after being shot out of helis etc too.

**Comment by oiad** [comment]
There's a problem with infistar manhandling the death messages, need to wait for a fix for that or change some stuff your self

**Comment by ndavalos** [comment]
It was working perfectly until things were changed in 1.0.6.1, I don't think infistar has anything to do with it. It needs to stop being a convientent excuse to blame everything on infistar. I'll have to revert all the death message crap to pre 1.0.6.1 and see if it really is infistar. As far as I can see infistar isn't going to do anything to the death messages. The logic is just screwed.

**Comment by oiad** [comment]
Well if you hang out on discord you will see the talk of it, with the changes that have been discussed and done by many admins the problems have gone away.

**Comment by oiad** [comment]
Here's some of the changes you need to do:
Remove this code block completely
`				_this call fnc_usec_damageHandler;
				if(str fnc_usec_damageHandler != '{}')then
				{
					if((_damage > 0.4) && (player == vehicle player))then
					{
						if(isNil 'DMG"+_randvar5+"')then
						{
							DMG"+_randvar5+" = true;
							if(isNil 'r_player_blood')then{ r_player_blood = -500; } else { if(typeName r_player_blood != 'SCALAR')then{ r_player_blood = -500;YOLO = true; }; };
							if(r_player_blood == 12000)then
							{
								[] spawn {
									uiSleep 2;
									if(isNil 'r_player_blood')then{ r_player_blood = -500; } else { if(typeName r_player_blood != 'SCALAR')then{ r_player_blood = -500;YOLO = true; }; };
									if(r_player_blood == 12000)then
									{
										_log = format['No Blood loss! %1',r_player_blood];
										_name = 'DEAD';if((alive player)&&(getPlayerUID player != ''))then{_name = name player;};
										[_name,getPlayerUID player,'SLOG',toArray (_log)] call "+_randvar340137+";
										if(isNil 'LASTDAMAGESOURCE')then{LASTDAMAGESOURCE = player;} else {if(isNull LASTDAMAGESOURCE)then{LASTDAMAGESOURCE = player;};};
										[LASTDAMAGESOURCE,'shotheavy'] spawn player_death;
										player setHit['Body',1];
									};
									DMG"+_randvar5+" = nil;
								};
							}
							else
							{
								[r_player_blood] spawn {
									_tempBlood = _this select 0;
									uiSleep 1;
									if(isNil 'r_player_blood')then{ r_player_blood = -500; } else { if(typeName r_player_blood != 'SCALAR')then{ r_player_blood = -500;YOLO = true; }; };
									if(((r_player_blood == _tempBlood) || (r_player_blood > _tempBlood)) && (r_player_blood > 3000))then
									{
										r_player_blood = r_player_blood - ((random 800) + (random 800) + 500);
										_tmp = r_player_blood;
										uiSleep 0.5;
										if(isNil 'r_player_blood')then{ r_player_blood = -500; } else { if(typeName r_player_blood != 'SCALAR')then{ r_player_blood = -500;YOLO = true; }; };
										if(r_player_blood - _tmp > 10)then
										{
											_log = format['Blood should be %1 but is %2..',_tmp,r_player_blood];
											_name = 'DEAD';if((alive player)&&(getPlayerUID player != ''))then{_name = name player;};
											[_name,getPlayerUID player,'SLOG',toArray (_log)] call "+_randvar340137+";
										};
									};
									DMG"+_randvar5+" = nil;
								};
							};
						};
					};
				};`

**Comment by oiad** [comment]
Here's the changes so far that I have been told we need to do to get kill messages working properly: https://github.com/oiad/infistar_changes

Mine seem to be working great now.

**Comment by ndavalos** [comment]
Yeah those removed code blocks are not going to screw with the death messages, it's fairly random when the method is incorrect. I've already fixed all the spawn calls and sethit for player_death, that is what fixes an incorrect source, not completely removing damage handling and player death handling in infistar. The logic changed inside player_death enough that it is getting the method confused at times. Source is usually correct, method however is not. The other issue with 1.0.6.1 death messages is setting respawndelay = 0, that screwed the distance displayed since it picks up the distance of the respawned player in debug and not the original death location. Setting it back to 5 fixes the distance problem with death messages. Fixing prematurely despawning bodies in a different way in server_playerDeath is better than just messing with respawndelay.

I'm just going to revert to the working 1.0.6 player_death and server_playerdeath logic for damage method determination since those worked perfectly and tweak the code from there.

**Comment by ebayShopper** [comment]
Any custom suicide scripts should be updated to use `[player,'suicide'] call player_death;` with no additional setHit or setDamage. As I explained in [[my post](https://epochmod.com/forum/topic/43412-1061-issues-so-far/#comment-287740)] these other problems are with infistar not being up to date for 1.0.6.1 yet, not Epoch.

You can easily confirm that by testing on a stock server without infistar installed. Oiad and I already tested all death message types on a stock server and everything works as intended.

We have no control over infistar, so issues with his script should reported to him, not here. He just messaged me again this morning and said he is updating now.
