### ISSUE TITLE
No entry "bin\config.bin/CfgVehicles/*skinclassname*.Simulation

### ISSUE THREAD

**Issue by kingpapawawa** [EpochModTeam/DayZ-Epoch#1908]
This is a new random error since the hotfix.

![arma2oa 2017-03-14 15-38-25-27](https://cloud.githubusercontent.com/assets/24888827/23922331/4bd91cea-08d8-11e7-80b2-c4bd0cf89b88.png)

[ArmA2OA.txt](https://github.com/EpochModTeam/DayZ-Epoch/files/842677/ArmA2OA.txt)

**Comment by kingpapawawa** [comment]
i have disabled the hotfix and it still happens so rule out that...

**Comment by icomrade** [comment]
This is not an epoch skin, it's defined as part of a2 if you're getting errors make sure you are running a2 CO properly
