### ISSUE TITLE
Server: Object 2:1907 not found (message 70) Can't join Server and chin yelllow don move 

### ISSUE THREAD

**Issue by jirakit2537** [EpochModTeam/DayZ-Epoch#1911]
1:38:54 Server: Object 2:1907 not found (message 70)
 1:38:54 Server: Object 2:1927 not found (message 70)
 1:38:54 Server: Object 2:2096 not found (message 70)
 1:38:54 Server: Object 2:2129 not found (message 70)
 1:38:54 Server: Object 2:2215 not found (message 70)
 1:38:54 Server: Object 2:633 not found (message 70)
 1:38:54 Server: Object 2:548 not found (message 70)
3000 line 

After restart server no problem

**Comment by icomrade** [comment]
Not sure what causes those messages, since they don't occur in a vanilla install on my servers. Possibly a problem with the base game (ArmA 2 and/or OA), or networking. Either way, I've seen them before and are generally just spam which isn't necessarily indicative of a problem.
