### ISSUE TITLE
Player inventory corrupted in database

### ISSUE THREAD

**Issue by ThatFellaNick** [EpochModTeam/DayZ-Epoch#1914]
Hey guys I updated to the new version 1.0.6.1, since then we have been having a problem where players cannot log in because it gets stuck on "Server responded, creating character". 

I looked into the problem. The problem seems to be a formatting issue for the inventory field in the character_data table

A player with...
`[["Binocular","ItemMap","ItemRadio","ItemCompass","M9_DZ"],["ItemPainkiller","ItemBloodbag","ItemMorphine","ItemSodaCoke","FoodPistachio","ItemBloodbag","ItemMorphine","ItemSodaCoke","ItemPainkiller","ItemBandage","ItemBandage","15Rnd_9x19_M9","ItemBandage"],""]` in the Inventory field can log in no problem

A player with...
`[["Binocular","ItemMap","ItemRadio","ItemToolbox","ItemCompass","M9_DZ"],"ItemPainkiller","ItemBloodbag"]` in the Inventory field can not log in.

I seems the string is missing a few brackets and commas, along with a double quotations.

I dont really see how I would fix this since the script that inserts the players gear into the database is stock code from the release 
`_playerGear = [weapons _character,_magazines select 0,_magazines select 1];`
^server_playerSync.sqf

**Comment by oiad** [comment]
It seems like those characters aren't getting the dayz_onBack set on them.
Is this a converted database or a fresh install?

**Comment by DAmNRelentless** [comment]
[["Binocular","ItemMap","ItemRadio","ItemToolbox","ItemCompass","M9_DZ"],["ItemPainkiller","ItemBloodbag"],""]

What about this?

**Comment by Stijnkluiters** [comment]
You're missing the complete point of an associative array..

these brackets [] are indicated as array, as this builder espects 3 array's in 1 array. you should put like 



```

 [
// weapons
['weapon'],
// magazines
['magazine...'],
// backpack
['backpack']
];
```

**Comment by ThatFellaNick** [comment]
@oiad Thank you for your reply. Im kind of cleaning up from a rouge-ish scripter and im not too sure if the structure of the database was converted to from the last version to 1.0.6.1, or if the database from the last version was wiped and used on 1.0.6.1. Ill look into it more. Basically the array of gear is being sent to the database with messed up syntax where its leaving out some quotes, commas, and brackets. Then when the player logs in the information is pulled from the database with no problem i suppose, but cant be converted into the variable in the script, because its not formatted right.

**Comment by ebayShopper** [comment]
I'm not sure how your inventory formatting managed to get corrupted as you have shown.

Check your 1051 database backup you are starting with and see if it has the same problem. If it is also missing opening brackets `[` on player magazine arrays this would not allow those players to login on 1051 either.

**Comment by ThatFellaNick** [comment]
@ebayShopper Thanks for the reply! I love you picture. The strange thing is that it didn't happen on 1051. So do you think the problem lies in the databases table structure? Im about to look into it more soon.

**Comment by SmokeyBR** [comment]
this might be releated to virtual garage script
testing i have come across the same situation 
https://epochmod.com/forum/topic/43491-release-virtual-garage-update-for-1061/?do=findComment&comment=289191

**Comment by ebayShopper** [comment]
Yes, calling server_playerSync with an array using the old 1.0.5.1 format will cause problems like this. In 1.0.6.1 the second element in PVDZ_plr_Save must be an array containing the return from player_countMagazines (which includes ammo counts) and dayz_onBack. The old 1051 format used (magazines player) with no ammo count and did not include dayz_onBack. The script Smokey mentioned had that problem:
https://epochmod.com/forum/topic/43491-release-virtual-garage-update-for-1061/?page=3#comment-289562

Make sure any old 1051 scripts that used PVDZ_plr_Save are updated to the correct format:
https://github.com/EpochModTeam/DayZ-Epoch/blob/master/SQF/dayz_code/compile/player_forceSave.sqf#L10

Most of the time it's better to just use `call player_forceSave;`
