### ISSUE TITLE
Bag with FR_Assault_R_DZ?

### ISSUE THREAD

**Issue by F507DMT** [EpochModTeam/DayZ-Epoch#1922]
I log in to server nearby vehcile Gaz_vodnik, primary weapon M4A1. If i change weapon to other, all ok, if take M4A1, bag show agen.
its was one time.
sorry for my en)
![20170322234425_1](https://cloud.githubusercontent.com/assets/6854424/24330225/b9f46e0c-123b-11e7-800f-387c3f3a2dfb.jpg)

**Comment by icomrade** [comment]
I can't replicate this. I did notice that the backpack doesn't show up on the players back (as you stated), but that's rather minor.
