### ISSUE TITLE
if "cont(str(gear vehcile))">2048, DB didn`t save it. Players can dupe anything.

### ISSUE THREAD

**Issue by F507DMT** [EpochModTeam/DayZ-Epoch#1924]
**if "cont(str(gear vehcile))">2048, DB didn`t save it. Players can dupe anything.**

full fix: "ItemBandage" to "0", "ItemPainkiller" to "1" IN all mod, or jast for save in vehices.
Or shrink an array by driver.dll

more 2048 can be in vault or truck, just put the different things in the vehicle.

my temp fix
**in object_monitorGear.sqf**
`if((count toArray(str((getWeaponCargo _object)+(getMagazineCargo _object)+(getBackpackCargo _object))))>1850)then{ //bla bla error, not all be save in BD`

**in server_updateObject.sqf, in _object_inventory**
```
//after
if ((str _inventory != _previous) || {_forceUpdate}) then {
if((count toArray(str((_inventory select 0)+(_inventory select 1)+(_inventory select 2))))>1850)then{
	_inventory=[_object]call fnc_resizeInvArray;
};
```

**in server_functions.sqf**

[fnc_resizeInvArray.txt](https://github.com/EpochModTeam/DayZ-Epoch/files/870960/fnc_resizeInvArray.txt)
fnc_resizeInvArray={
	private["_object","_NewInv","_step","_array","_a","_cntNewInv","_abort"];
	_object=_this select 0;
	_NewInv=[];
	_abort=-1;
	{
		_step=100;
		//better use while{_step>0}do{
		while{true}do{
			_array=[];
			{
				_a=_x;
				if((count _a)>_step)then{
					_a resize _step;
				};
				_array set[count _array,_a];
			}forEach _x;
			_cntNewInv=count toArray(str(_NewInv+_array));
			//diag_log(format["DEBAG: fnc_resizeInvArray _step:%1",_step]);
			if(_cntNewInv<1830)exitWith{
				_NewInv set[_forEachIndex,_array];
				if(_cntNewInv>1700)then{_abort=_forEachIndex};
			};
			_step=_step-50;
		};
		if(_abort!=-1)exitWith{
			switch(_abort)do{
				case 0:{
					_NewInv set[1,[[],[]]];
					_NewInv set[2,[[],[]]];
				};
				case 1:{
					_NewInv set[2,[[],[]]];	
				};
			};
		};
	}forEach [getWeaponCargo _object,getMagazineCargo _object,getBackpackCargo _object];
	//diag_log(format["DEBAG: fnc_resizeInvArray obj:%1 objID:%2",typeof _object,GetObjID(_object)]);
	_NewInv
};

**Comment by ebayShopper** [comment]
This was already fixed with 46a1441 and 145fbf0. The inventory field has no character limit in the database. The problem was the [[format command](https://community.bistudio.com/wiki/format)] in A2 is limited to 2048 characters. We have already replaced the necessary occurrences of it with str and formatText which do not have character limits.

I just tested a safe with inventory exceeding 2048 characters and it saved fine in the database. After restart and unlock it was still fine. 2,686 characters:
```
[[["M4A1_GL_DZ","MeleeHatchet","ItemCompass","ItemCrowbar","ItemEtool","ItemGPS","ItemKnife","ItemMatchbox","ItemToolbox","ItemKeyBlack10","M16A4_ACOG_DZ","Binocular_Vector","NVGoggles","SA58_Holo_FL_DZ"],[1,1,1,1,1,1,1,1,1,1,1,1,1,1]],[["ItemBloodbag","ItemAntibiotic","ItemEpinephrine","ItemMorphine","ItemPainkiller","FoodRabbitCooked","ItemWaterBottle","Skin_Camo1_DZ","Skin_Survivor2_DZ","30Rnd_556x45_Stanag","ItemBandage","ItemAntibacterialWipe","100Rnd_762x51_M240","ItemHeatPack","FoodCanPotatoes","ItemSodaR4z0r","1Rnd_Arrow_Wood","2000Rnd_762x51_L94A1","20Rnd_762x51_FNFAL","250Rnd_127x99_M3P","2Rnd_12Gauge_Buck","30Rnd_545x39_AK","30Rnd_556x45_G36SD","30Rnd_762x39_AK47","30Rnd_9x19_MP5SD","350Rnd_BB_Magazine","48Rnd_40mm_MK19","5Rnd_127x108_KSVK","5Rnd_762x51_M24","5x_22_LR_17_HMR","6Rnd_FlareYellow_M203","6Rnd_SmokeGreen_M203","75Rnd_545x39_RPK","8Rnd_12Gauge_Slug","8Rnd_B_Beneli_74Slug","AT13","Attachment_CCO","Attachment_Kobra","Attachment_PSO1","Attachment_Sup556","Attachment_SupMakarov","Attachment_SupBizon","Attachment_Sup9","Attachment_Sup545","Attachment_SCOPED","Attachment_SA58RIS","Attachment_MFL_Pist","Attachment_MFL","Attachment_M203","Attachment_Holo","Attachment_GP25","Attachment_Ghillie","Attachment_FL_Pist","Attachment_FL","Attachment_BELT","Attachment_ACOG","bloodBagABPOS","bloodBagBNEG","bulk_17Rnd_9x19_glock17","bulk_30Rnd_556x45_StanagSD","bulk_ItemSodaCoke","bulk_ItemSodaCokeFull","bulk_ItemSodaPepsi","bulk_ItemSodaPepsiFull","bulk_ItemTankTrap","bulk_ItemTankTrapHalf","bulk_PartGeneric","bulk_PartGenericHalf","desert_large_net_kit","CinderBlocks","equip_2inch_metal_pipe","equip_cable_tie","equip_Crossbow_Kit","equip_d_battery","equip_empty_barrel","equip_feathers","equip_floppywire","equip_gauze","equip_gauzepackaged","equip_herb_box","equip_hobo_fishing_kit","equip_lever","equip_needle","equip_note","equip_paint","equip_string","equip_tin_powder","equip_weapon_rails","equip_wood_pallet","equip_woodensplint","FishCookedTrout","15Rnd_9x19_M9SD","17Rnd_9x19_glock17","1Rnd_HE_GP25","1Rnd_HE_M203","1Rnd_SmokeGreen_GP25","20Rnd_B_765x17_Ball","6Rnd_45ACP","FlareGreen_GP25","FlareRed_M203","30Rnd_762x39_SA58","wholeBloodBagABNEG","wholeBloodBagABPOS","wholeBloodBagANEG","wholeBloodBagAPOS","wholeBloodBagBNEG","wholeBloodBagONEG","wholeBloodBagBPOS","wood_ramp_kit","wood_shack_kit","workbench_kit","SmokeShellYellow","sun_shade_kit","TrapBear"],[5,3,3,3,3,1,1,1,1,5,5,1,2,2,2,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,2,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,3,1,1,1,1,1,1,1,1,1,1,1,1,1]],[["DZ_Backpack_EP1","DZ_Patrol_Pack_EP1"],[1,1]]]
```
