### ISSUE TITLE
Optimize animation synchronization "medic"

### ISSUE THREAD

**Issue by F507DMT** [EpochModTeam/DayZ-Epoch#1925]
if player start animation:
`player playActionNow "Medic";
while {r_doLoop} do {
	_animState = animationState player;
	_isMedic = ["medic",_animState] call fnc_inString;`

"Medic" is "good" animation, for brake it dont need call RE:
`[objNull, player, rSwitchMove,""] call RE;
player playActionNow "stop";`

is enough:
`player switchMove "";
player playActionNow "stop";`

**Comment by icomrade** [comment]
I think there's an issue with animations now syncing if we don't use RE

**Comment by F507DMT** [comment]
If we use only "Medic", animate be synchronized, but if admin server use animate like:
`[objNull, player, rSwitchMove,"miles_c0briefing_odpovedel_loop"] call RE;`

It is necessary
`[objNull, player, rSwitchMove,""] call RE; player playActionNow "stop";`

**Comment by ebayShopper** [comment]
I tested with oiad and the RE is needed to synchronize the animation state to remote clients when interrupting. If you only execute the switchMove locally then remote players see you glitch moving while still in the medic animation.
