### ISSUE TITLE
PipeBomb error

### ISSUE THREAD

**Issue by SilvDev** [EpochModTeam/DayZ-Epoch#1927]
When I spawn with a Satchel Charge, "PipeBomb" classname, I see a popup error box in-game and the following error in the client RPT:

> Warning Message: No entry 'bin\config.bin/CfgMagazines.piepebomb'.
> Warning Message: No entry '.picture'.
> Warning Message: '/' is not a value
> Warning Message: No entry '.scope'.
> Warning Message: '/' is not a value
> Warning Message: Error: creating magazine piepebomb with scope=private
> Warning Message: No entry '.displayName'.
> Warning Message: '/' is not a value
> Warning Message: No entry '.displayNameShort'.
> Warning Message: '/' is not a value
> Warning Message: No entry '.nameSound'.
> Warning Message: '/' is not a value
> Warning Message: No entry '.Library'.
> Warning Message: No entry '.libTextDesc'.
> Warning Message: '/' is not a value
> Warning Message: No entry '.type'.
> Warning Message: '/' is not a value
> Warning Message: No entry '.count'.
> Warning Message: '/' is not a value
> Warning Message: No entry '.maxLeadSpeed'.
> Warning Message: '/' is not a value
> Warning Message: No entry '.initSpeed'.
> Warning Message: '/' is not a value
> Warning Message: No entry '.reloadAction'.
> Warning Message: '/' is not a value
> Warning Message: No entry '.modelSpecial'.
> Warning Message: '/' is not a value
> Warning Message: No entry '.ammo'.
> Warning Message: '/' is not a value

Edit: I'm also running Overwatch so disregard if the error comes from there. Although this error only appeared since 1.0.6+

**Comment by icomrade** [comment]
Works for me with vanilla Epoch
```player addMagazine "PipeBomb";```

**Comment by oiad** [comment]
`Warning Message: No entry 'bin\config.bin/CfgMagazines.piepebomb'.`

You've spelt it wrong: piepebomb

**Comment by icomrade** [comment]
actually, are you using a special skin?
https://epochmod.com/forum/topic/31458-no-entry-binconfigbincfgmagazinespiepebomb/#comment-195652

**Comment by SilvDev** [comment]
I didn't spell it wrong, I know the classname is "PipeBomb" and it adds fine onto the character, but that error message pops up. I don't use any custom skins only running Overwatch with Epoch.

**Comment by icomrade** [comment]
Look at the classname mentioned in the link I posted... make sure it's not on your server

**Comment by ebayShopper** [comment]
It is a typo in the Overwatch fr_reskin addon config:
```
class frb_stealth_sabot : frb_tl {
		displayName = "Stealth Saboteur";
		faceType = "HeadMask1Black";
		identityTypes[] = {"Head_USMC_CO", "FR_Glasses"};
		weapons[] = {"RH_hk416sdgleotech", "M9", "ItemGPS", "NVGoggles", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		magazines[] = {"30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "30Rnd_556x45_Stanag", "HandGrenade_West", "SmokeShellYellow", "SmokeShellPurple", "HandGrenade_West", "HandGrenade_West", "15Rnd_9x19_M9", "15Rnd_9x19_M9", "1Rnd_HE_M203", "1Rnd_HE_M203", "1Rnd_HE_M203", "1Rnd_HE_M203", "1Rnd_HE_M203", "1Rnd_SmokeRed_M203", "piepebomb", "pipebomb"};
        };
```
As soon as the unit is created it attempts to add these magazines, so the error will show even if you clear the unit inventory. Your best bet is to just not use that skin as icomrade said.

**Comment by SilvDev** [comment]
Thanks for the heads up. We have been using Overwatch for a long time and only now (since 1.0.6 update) does this error appear. I'm spawning with the default skin, traders are default and the database fresh install, so it's odd this is happening.
