### ISSUE TITLE
Suggestion: Adding Name to Player Database SQL

### ISSUE THREAD

**Issue by looter809** [EpochModTeam/DayZ-Epoch#1931]
As the title suggests, I think it would be very helpful and beneficial if we were to add the player's name in the character_data maybe between CharacterID and PlayerUID or between PlayerUID and InstanceID. Does this sound like a good idea to others too?

Edit: Maybe if it's possible add the steam name as well? That would also be very useful.

**Comment by ndavalos** [comment]
It's unnecessary, if you want to see it make a view

**Comment by icomrade** [comment]
Name is not very reliable, considering multiple players with the same UID can be of different names, if the player changes his profile name after dying. I agree, I think it's completely unnecessary, either reference player_data or your server logs with the PlayerUID

**Comment by Stijnkluiters** [comment]
you can create a website like i did, add me on github and ill add you to my repo.

( it creates a querry for every UID. the query gets saved for 30 minutes so the database wont have to load as much ).
