### ISSUE TITLE
m240 nest building is messed up

### ISSUE THREAD

**Issue by ndavalos** [EpochModTeam/DayZ-Epoch#1932]
It appears there was never a ghost preview defined for m240 nests, so you just end up with the green semi-outline for them, which when you actually place it, shifts dramatically from where you intended it to go.

**Comment by ndavalos** [comment]
Actually, it seems that WarfareBMGNest_Preview is what is coming out of looking up the ghost model, which is pretty useless for trying to build with it.

**Comment by ndavalos** [comment]
I ended up just substituting the actual M240Nest_DZ model for the ghost and it works fine, so maybe just define that as the ghost model or change modular_build to swap it.

**Comment by ebayShopper** [comment]
It is a little off, but close enough.
http://imgur.com/a/GFbPM

It is better than no ghost for now IMO. Ideally one day someone with the skills will make transparent versions for all the buildables missing them. The solid models have player sliding and other issues with collision like we saw in  #1945. If you disagree you can always override in modular/player_build.sqf.

**Comment by ndavalos** [comment]
Yeah that's what I ended up doing. Curiously enough my ghost model is pretty wildly different, wonder why, maybe due to not building on the ground, but on a metal floor 100m up instead. But yeah I'll just have mine swap for now.
