### ISSUE TITLE
UH60Wreck_DZ broken?

### ISSUE THREAD

**Issue by oiad** [EpochModTeam/DayZ-Epoch#1933]
22:09:16 Cannot create non-ai vehicle UH60Wreck_DZ,

Receiving this in my RPT, I can see that it is in the game: https://github.com/EpochModTeam/DayZ-Epoch/blob/b609dcf5190293d6cd6bfe741b968889749042fe/SQF/dayz_code/Configs/CfgVehicles/Helicopter/UH60Wreck.hpp

**Comment by ebayShopper** [comment]
The legacy wrecks are no longer used and were commented out. I just removed them to avoid confusion. The new ones are CrashSite_EU/UN/US/RU. Old scripts should be updated. [This was mentioned in the change log](https://github.com/EpochModTeam/DayZ-Epoch/blob/master/Documents/CHANGE%20LOG%201.0.6.txt#L62).

The new wrecks are essentially the same except they have a smoke effect, no more glitched mini gun flash and use nicer models from dayz_communityassets.

For UH60 you should use the custom ones from [the addon packed in Epoch](http://www.armaholic.com/page.php?id=10670). The classnames are "UH60_NAVY_Wreck_DZ", "UH60_ARMY_Wreck_DZ", "UH60_NAVY_Wreck_burned_DZ" and "UH60_ARMY_Wreck_burned_DZ".

You can also use the default Arma wrecks which are the same models as the legacy ones.
