### ISSUE TITLE
Dupe Method

### ISSUE THREAD

**Issue by SmokeyBR** [EpochModTeam/DayZ-Epoch#1936]
testing some more yesterday is still possible to dupe by aborting the game while another player removes a weapon from your backpack.

- press esc and wait for timer to finish
- click abort and wait at message "leave to lobby" "yes or no"
- have another player approach you
- make player remove item from backpack the same time as you press "yes"

**Comment by icomrade** [comment]
5acad04c43bc1d1fa11476614e6d5a6f708cc3a0
