### ISSUE TITLE
Top snap point for half cinder wall incorrect

### ISSUE THREAD

**Issue by ndavalos** [EpochModTeam/DayZ-Epoch#1949]
The top/middle snap point for half cinder walls is too high. This is for anything you try to attach to the top/middle point:

https://steamuserimages-a.akamaihd.net/ugc/83723269576107134/01E9C7E867259BAD1779D69B6333274EB8D19624/

**Comment by AirwavesMan** [comment]
Fixed with https://github.com/EpochModTeam/DayZ-Epoch/commit/8f10a36b994f299402415b87df81ef73664f5a56
