### ISSUE TITLE
M134 ammo in Bell gunship

### ISSUE THREAD

**Issue by AirwavesMan** [EpochModTeam/DayZ-Epoch#1950]
The Gunship Bell can use the normal 2000 M134 ammo. I think this is not the intention of the new 1300 M60 rounds.

**Comment by ebayShopper** [comment]
I don't see a problem with this. You can use either the pook_1300Rnd_762x51_M60 or 2000Rnd_762x51_M134. It makes sense they both work, because they are using the same model and caliber.
