### ISSUE TITLE
Removing Mines

### ISSUE THREAD

**Issue by AirwavesMan** [EpochModTeam/DayZ-Epoch#1954]
Some skins are able to remove placed mines. I think this is not intended? Can I disable this feature?

**Comment by F507DMT** [comment]
It's because your skin is engineer type.
If u use owerwach, Epoch Team can`t help u with that skins.

https://community.bistudio.com/wiki/ArmA_2:_Infantry

**Comment by AirwavesMan** [comment]
I use vanillia epoch. I know that is the engineer type but it should be the same like the medic typ. If we disable it like the medic typ it should work I think.

**Comment by icomrade** [comment]
You can disable the feature
in skin configs:
engineer = 0; 
canDeactivateMines = 0;
attendant = 0;

**Comment by ebayShopper** [comment]
Uncommenting this line should disable it with fewer changes:
https://github.com/EpochModTeam/DayZ-Epoch/blob/master/SQF/dayz_code/Configs/CfgArma.hpp#L23

**Comment by AirwavesMan** [comment]
Uncommenting does not disable it. Ive tested it and I was still able to remove mines.

**Comment by ebayShopper** [comment]
Try adding 
```
class DeactivateMine : None { show = 0; }
```

**Comment by ebayShopper** [comment]
@AirwavesMan which skin do you get the option with? You may have forgot to repack your dayz_code or have a third party script which is adding the action. After uncommenting the line I mentioned I do not get the option with any of the engineer skins on Mine or MineE.

**Comment by AirwavesMan** [comment]
@ebayShopper It was the FR_Sapper_DZ skin. Im really sure I repacked it correctly

**Comment by ebayShopper** [comment]
Yup, no action on that skin either. Your CfgArma may be getting overwritten in another addon, but that shouldn't happen as long as you load Epoch last in the addon order.
