### ISSUE TITLE
Skin Change Adding humanity

### ISSUE THREAD

**Issue by SmokeyBR** [EpochModTeam/DayZ-Epoch#1959]
while testing lastest changes on player_switchmodel.sqf and player_humanitymorph.sqf i noticed my humanity was changing every time i reloged.

-change skin
-open gear and right click skin
-spam left click "wear clothes" and wait dayz_actioninprogress to finish
-once skin changed check database for humanity
-should be doubled or added whatever humanity u had to begin with
-issue does not appear if you wait a while for another skin change (has to be done right after change)

the added humanity will not be displayed inside game it will update only after a relog. this was tested on a production server with custom stuff however player_switchmodel.sqf and player_humanitymorph.sqf are the ones updated here with NO infistar installed.
did test on a stock server (10.6.1 files) the issue is not present.

edit: meant to say spam left click on "wear clothes" not right click, corrected.

**Comment by icomrade** [comment]
is the issue double of negative or positive humanity?

I.E
2000 -> 4000
Vs.
-2000 -> -4000?

**Comment by SmokeyBR** [comment]
either way
if -2000 it will result in -4000
if 2000 it will result in 4000

**Comment by SmokeyBR** [comment]
confirmed issue present on stock server with only the newest:
player_humanityMorph.sqf
player_switchModel.sqf

**Comment by icomrade** [comment]
try changing this line https://github.com/EpochModTeam/DayZ-Epoch/blob/master/SQF/dayz_server/compile/server_playerSync.sqf#L58
to:
```
_humanity = (_character getVariable ["humanity",0]);
```

**Comment by SmokeyBR** [comment]
changed line 58 to what suggested, issue is still present.

**Comment by SmokeyBR** [comment]
i was able to pinpoint where the issue was introduced
https://github.com/EpochModTeam/DayZ-Epoch/blob/bd35e0a574956bd4bf6cf9eb21d5daec54919224/SQF/dayz_code/compile/player_humanityMorph.sqf#L41
if changed to the orginal code
`_model call player_switchModel;`
issue will disapear however the error
17:35:43 "ERROR: Cannot Sync Character Smokey has no characterID"
will show up again

**Comment by icomrade** [comment]
you are essentially disabling the entire dupe fix by reverting to a non-array parameter

**Comment by oiad** [comment]
There was issues in 1.0.5.1 with humanity doubling on skin changes that were fixed by community fixes, I'm at work but a search on epochmod should find them

On 2 August 2017 9:47:01 AM NZST, icomrade <notifications@github.com> wrote:
>you are essentially disabling the entire dupe fix by reverting to a
>non-array parameter
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/EpochModTeam/DayZ-Epoch/issues/1959#issuecomment-319506657

-- 
Sent from my phone

**Comment by SmokeyBR** [comment]
as far as i can notice it will only happen if you change twice really fast, doesn't seem to be an issue if you take a while between skin changes.

forum related issue
https://epochmod.com/forum/topic/17441-humanity-doubling-help-needed/?page=7

**Comment by icomrade** [comment]
try with https://github.com/EpochModTeam/DayZ-Epoch/commit/9cc3c82d5d6f82a852a5fc94dd51421f2b076502

**Comment by SmokeyBR** [comment]
seems good now, tried changing clothes alot, humanity stayed the same.
