### ISSUE TITLE
Not defined variable PVCDZ_plr_Login

### ISSUE THREAD

**Issue by Kohlekopf** [EpochModTeam/DayZ-Epoch#1973]
When i join my Server i recieve "Not defined variable PVCDZ_plr_Login" Line 9 dayz_code/groups/init.sqf

I dont know where i have to define this one, but cause of it my group management dont works

**Comment by icomrade** [comment]
seems like there's an issue in your server DB or server side scripting. You are more likely to receive help on the epochmod forums, please ask there. https://epochmod.com/forum/forum/1-arma-2/
