### ISSUE TITLE
Re-adding BAF_L85A2_RIS_CWS

### ISSUE THREAD

**Issue by AirwavesMan** [EpochModTeam/DayZ-Epoch#1983]
Hey guys,

the BAF_L85A2_RIS_CWS is broken since a corepatch version earlier. Normally it has nightvision and infrared sight. After the corepatch it has only nightvision sight. I got asked by many players why they cannot use the infrared sight until I noticed that the infrared sight is broken. Im not 100% sure that the change in the corepatch is intended but I think it was not. 

This commit changed the weapon:

https://github.com/Goliath86/CorePatch/commit/77b9e07c079e21a9b33e4b7d2c8f98e77204417d#diff-b474f04f04f3baaef3bfc58e3ac954b2

If would love to re-add the BAF_L85A2_RIS_CWS as a _DZ version but I do not know how add the old infrared sight again.

**Comment by icomrade** [comment]
Well to be fair the CWS is a sight in real life that doesn't have thermal imaging, only night vision. But I have a sweet spot for the weapon in ArmA.  I have added the weapon back with the class name BAF_L85A2_RIS_TWS_DZ

**Comment by AirwavesMan** [comment]
Ah you are right. The CWS is nightvision only. Thx for re-adding the old L85 version. It is really good to have it back again.
