### ISSUE TITLE
fn_exitSwim.sqf

### ISSUE THREAD

**Issue by AirwavesMan** [EpochModTeam/DayZ-Epoch#1993]
The workaround works fine. But there is a problem that players have on my server. They spawning, when logging out in rooms with a small ceiling height, on the roof of the building because of the parachute. If a camo net is above the position they log out, they spawn everytime on the camo net. This is really annoying because you cannot logout in normal rooms with 1x1 metal floors or barracks.

I fixed it partly by using 

_unit setpos _paraPosition;

before 

_unit allowDamage true;

But it still does not work everytime. With camo nets it does not work at all.

**Comment by ebayShopper** [comment]
@skigoggles just told me about this on Namalsk too.

SetPosATL works inside the barracks and under a camonet for me. This should not cause any issues except maybe position being slightly off when starting out in a halo spawn above water or relogging on a multistory built above water. Please test it out and let me know. Thanks.

**Comment by skigoggles** [comment]
funny you should bring up this issue and Namalsk @ebayShopper . We put up a Namalsk server again and a player noticed that when he changes clothes in a barracks, he ends up on the roof (which is essentially a respawn). When I went to look at it myself, it looks like when you login/spawn you are dropping/floating down a bit. ASL? ATL? I haven't had a chance to look at it.
