### ISSUE TITLE
Repair Vehicle issue

### ISSUE THREAD

**Issue by AngeloneIL** [EpochModTeam/DayZ-Epoch#1994]
Most Of It Will Be in The Video But i'll Explain First,
When a Vehicle Gets Damaged The"Repair Vehicle" Option Doesn't Let You To Repair it doesn't matter if you have the required parts or not this also applies to helicotpers aswell as "Salvage Vehicle"
you'll see in the video at the middle that i tried relogging too and that doesn't work

https://youtu.be/ZagvX7WYKWA

**Comment by ebayShopper** [comment]
The third party script you used to spawn the vehicle did not do it correctly. When a vehicle is spawned it needs the proper eventhandlers added to it on all machines. This is done on the server via:
```sqf
_object call fnc_veh_ResetEH;
PVDZE_veh_Init = _object;
publicVariable "PVDZE_veh_Init";
```
https://github.com/EpochModTeam/DayZ-Epoch/blob/master/SQF/dayz_server/compile/server_publishVehicle2.sqf#L97-L100

Try a trader purchased vehicle or a vehicle already on the map and you will see they work.
