### ISSUE TITLE
ETA for 1.0.6.2

### ISSUE THREAD

**Issue by MollyXVI** [EpochModTeam/DayZ-Epoch#1995]
I can see that v.1.0.6.2 is in development, do we have an est. ETA on when it's released and available for servers and DayZLauncher?

**Comment by ebayShopper** [comment]
I'm updating this repo with the vanilla changes since 1.8.9 release right now.

After that we will put up a test build that should probably run at least a week, or until it gets some feedback.

ETAs are hard to give. A rough estimate is maybe two to three weeks.

**Comment by MollyXVI** [comment]
Thankyou for the replay, im looking for 1.0.6 2, the changes look promising
!

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by MollyXVI** [comment]
Hey, I just wanna point out a Dupe Glitch/Bug that needs to be fixed, i'm
not sure if you're able to do this but if u are that be very great.
G3 Magazine - vil_20Rnd_762x51_G3 - Can be splitted into 4x M24 mags and
once that is done, the G3 Mag doesnt go away, it stays in inventory, and
the 4x M24 Mags can be then combined into 1x DMR Mag and if that meg is
beeing dropped, the process can be repeated to the unlimit.
I made a video to show you aswell: YouTube Video Link
<https://www.youtube.com/watch?v=sjDIseY7xtA&feature=youtu.be>

**Comment by icomrade** [comment]
just use regular A2 OA mags, the split definition is set in the config, and since this is not an epoch/A2 default mag we can't control the config definitions for it.

We are certainly happy to help, but this is not the place to report issues with third party addons, unless there is an issue with the epoch script itself.

**Comment by MollyXVI** [comment]
Is it possible to add a DZE Version of the M240 Nests so they dont have any
ammo?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
