### ISSUE TITLE
Glitch Through doors on a ladder

### ISSUE THREAD

**Issue by SmokeyBR** [EpochModTeam/DayZ-Epoch#1999]
Apparently you can glitch though a door on the sides by finding a ladder action, like so...
3 images showing position of ladder in relation to the door. https://imgur.com/a/cK3ha

**Comment by icomrade** [comment]
you can glitch through anything on a ladder, it's fairly well known and isn't really easy to fix. This is where smart base building comes into play, that and active admins, requiring proof for base takeovers/raids to make sure they're legit. 

additionally we don't have the source for the door to fix this :/

**Comment by SmokeyBR** [comment]
sounds fair enough, if there´s no way then there´s no way. thought a heads up wouldn't hurt.

**Comment by AirwavesMan** [comment]
As said before, we cannot really fix this. Admins have to keep their eyes open to find and punish those glitching people if needed.
