### ISSUE TITLE
M240 Nest Blackscreen

### ISSUE THREAD

**Issue by MollyXVI** [EpochModTeam/DayZ-Epoch#2003]
When a player enters a M240 nests it sometimes puts the player into black screen and the Get Out option doesn't work, in order for the player to get out of the black screen he need to relog (when logging back in the player is on ground if nest is elevated) or an admin can Eject the player.

**Comment by ebayShopper** [comment]
This was due to simulation being disabled client side on buildables when `DZE_GodModeBase = true;` in 1.0,6.1. It is already fixed for 1.0.6.2 in 6717b0c
