### ISSUE TITLE
Loot in air

### ISSUE THREAD

**Issue by TBsThug** [EpochModTeam/DayZ-Epoch#2014]
At all docks on the Taviana Server, I am finding loot in the air above where it should be. Seems that any place that spawns loot that is over the water like containers and cranes on docks puts the loot into the air.
[img]https://i.imgur.com/L1hkfZV.jpg[/img]
[img]https://i.imgur.com/PWxeIuY.jpg[/img]
[img]https://i.imgur.com/q6FkFoT.jpg[/img]
[img]https://i.imgur.com/1xn4atF.jpg[/img]
[img]https://i.imgur.com/iwIFWc2.jpg[/img]
[img]https://i.imgur.com/j1MjzeZ.jpg[/img]

**Comment by AirwavesMan** [comment]
Mainly fixed with https://github.com/EpochModTeam/DayZ-Epoch/commit/89bca2c94b4733ed00a0853645f5b066607f48cc

Add fixWaterPos = 1; to the building class that has this problem.

https://github.com/EpochModTeam/DayZ-Epoch/blob/master/SQF/dayz_code/Configs/CfgLoot/Buildings/Industrial.hpp#L753
