### ISSUE TITLE
group markers/map markers/chat messages

### ISSUE THREAD

**Issue by JakeQue** [EpochModTeam/DayZ-Epoch#2017]
I can't get the group markers to show on map, or the RIP marker for players. Also the chat messages for group won't stop spamming every 30 seconds. 

I added this into my configvariables 

`// Group System
dayz_groupSystem = true; // Enable group system
dayz_requireRadio = false; // Require players to have a radio on their toolbelt to create a group, be in a group and receive invites.
dayz_markGroup = 1; // Players can see their group members on the map 0=never, 1=always, 2=With GPS only
dayz_markSelf = 1; // Players can see their own position on the map 0=never, 1=always, 2=With GPS only
dayz_markBody = 1; // Players can see their corpse position on the map 0=never, 1=always, 2=With GPS only
DZE_NameTags = 1; // Name displays when looking at player up close  0 = Off, 1= On, 2 = Player choice
DZE_ForceNameTagsInTrader = true; // Force name display when looking at player up close in traders. Overrides player choice.
DZE_HumanityTargetDistance = 50; // Distance to show name tags (red for bandit, blue for hero, green for friend)`

Any help would be appreciated

**Comment by BigEgg17** [comment]
Help requests should be directed to the forum. This is not a bug with the mod, but local to your server.

**Comment by JakeQue** [comment]
https://i.gyazo.com/60360ddcb7232d315de16382b2d5c7c3.png

@BigEgg17

**Comment by BigEgg17** [comment]
It works fine on every other server :) This is clearly the result of other third party changes to your server files, which should be resolved on the forums or in the Epoch Discord. The issues on Github are for proven issues with the Mod itself.

**Comment by ebayShopper** [comment]
Automatic radio messages are a limitation with real groups in Arma 2. They can not be disabled completely with the default game settings and scripting. I may add the option to use fake groups with no group channel to alleviate that.

Your other issue is server specific and should be directed to the help forums.
