### ISSUE TITLE
Can you change basebuilding keybinds client-side?

### ISSUE THREAD

**Issue by ljc1035** [EpochModTeam/DayZ-Epoch#2022]
The title pretty much covers it; I have a condensed keyboard, so my page up/page down keys are combined with the numpad 9 and numpad 3 keys, respectively. Arma doesn't seem to accept secondary input from keys, because I have tried using page up/page down and neither work in the game, even though they work out of the game. I'm just wondering if there is any way to rebind the building keybinds for epoch (page up to move part up/ page down to move part down) to something else, or if they're stuck on page up/page down.

**Comment by AirwavesMan** [comment]
Changing keybinds would only really work if we use special actions on keys which would require every player to rebind their actions keys before they can acutally use the basebuilding. So this is not an option. Hit me up if someone sees a better way on doing this.
