### ISSUE TITLE
dze_buildChecks.sqf

### ISSUE THREAD

**Issue by Sandbird** [EpochModTeam/DayZ-Epoch#2025]
Why is this line here in the repo but not in the release ? 
https://github.com/EpochModTeam/DayZ-Epoch/blob/3bbdcb9e88fa8611058f5ee1694b05cd45eb6731/SQF/dayz_code/compile/dze_buildChecks.sqf#L47

`if (DZE_limitPlots > 0 && !_isAdmin) then {`
I've been getting errors for the past 3h and i couldnt figure out why.
All of the sudden i cant build anything ingame, and it lead me to this.

```
if (DZE_limitPlots && !_isAdmin) then {
{
if (_x getVariabl>
  Error position: <&& !_isAdmin) then {
{
if (_x getVariabl>
  Error &&: Type Number, expected Bool
```

**Comment by oiad** [comment]
Because you're using files from the release and then you're using files from GitHub which are post release.

You need to use the configVariables.sqf from the current release (I guess this is your problem)

**Comment by Sandbird** [comment]
crap....i just realised it...i copied the wrong .sqf at some point....
Sorry about that, i see the 'false' in both the file and me :)
