### ISSUE TITLE
uncouncious after combat log never enables user input again

### ISSUE THREAD

**Issue by SmokeyBR** [EpochModTeam/DayZ-Epoch#2029]
ive track it down and this line is the culprit
https://github.com/EpochModTeam/DayZ-Epoch/blob/634a01a8d3e415efc991b52e4cf6a7bda5433f72/SQF/dayz_code/compile/fn_unconscious.sqf#L94

it will keep looping never identifying the "out of unconscious state"

**Comment by ebayShopper** [comment]
Tested:
1. Shoot to enter combat
2. Alt F4 or close game
3. Rejoin server
4. After waking input is enabled

Make sure `fnc_usec_damageUnconscious` is not modified by a 3rd party script

If you have other repro steps working on stock please post them

**Comment by SmokeyBR** [comment]
ok i should've said i came up with this problem while testing the "anti combat log" which removes the entire gear from player when combat logging. Sorry your're right should always test on a stock server before opening an issue.

That being said, now i also tested on a stock server overwriting only `fnc_usec_unconscious` file.
- enter combat mode
- drop all guns and binoculars
- force PLAYER COMBAT LOGGED (i did with alt+f4 on esc menu)
it should result in the issue explained above

**Comment by ebayShopper** [comment]
Thanks 73118c2
