### ISSUE TITLE
[request] update all storage objects on maintain

### ISSUE THREAD

**Issue by SmokeyBR** [EpochModTeam/DayZ-Epoch#2034]
is there a reason why plot maintain will not update database columns "DateStamp" and "LastUpdated" for "Storage Sheds"?
I like to point out most players assume (i did too) that when doing plot maintain on the entire base every object would be updated removing the necessity to change static object gear.

**Comment by ArmaWizard** [comment]
Im pretty sure this is the case so the map doesn't get cluttered. Because if you run the SQL function to delete old storage sheds they wont get removed if you update the timestamps. 

Now this is a bit weird because players might still be using the shed, but in large bases where there are lots of sheds, player might not use all of them and could count one as obselete, then the SQL function will remove it.

**Comment by SmokeyBR** [comment]
i understand the need to have as less objects as possible on the map, but it does generate a lot of confusion on the server as most people do assume when doing maintain that their whole base is safe from being removed. On my server i have strict rules that state you have to use the storage so it wont be delete.
however i do think it would be easier to add these objects to the maintain and avoid the confusions all together.

**Comment by marciobarroso** [comment]
I think this is an interesting feature. Should be easy to implement this.

**Comment by SmokeyBR** [comment]
since i opened the request i took a look on how to implement and is in fact really easy since there is a variable for objects that should be maintained.
https://github.com/EpochModTeam/DayZ-Epoch/blob/master/SQF/dayz_code/init/variables.sqf#L513

i was mainly worried why some objects weren't added to DZE_maintainClasses, specially objects with gear but i added them and seems to be ok after a little test, since then no players have complained yet.
this is what mine looks right now
`DZE_maintainClasses = DayZ_GearedObjects + DZE_LockableStorage + ["DZ_buildables","DZ_storage_base","ModularItems","DZE_Housebase","LightPole_DZ","BuiltItems","Generator_DZ","DZ_buildables","Plastic_Pole_EP1_DZ","Fence_corrugated_DZ","CanvasHut_DZ","ParkBench_DZ","MetalGate_DZ","StickFence_DZ","DesertCamoNet_DZ","ForestCamoNet_DZ","DesertLargeCamoNet_DZ","ForestLargeCamoNet_DZ","DeerStand_DZ","Scaffolding_DZ","FireBarrel_DZ","M240Nest_DZ"];`

use it at your own peril...

**Comment by ndavalos** [comment]
It will work fine, I actually split it out and make players maintain storage/vehicles separately. As long as the class is in the lost it will maintain it, sort of. There’s a problem with how maintenance is implemented in general in epoch as well as the cleanup sql scripts. I ended up just adding maintenance to my own function dll and redoing maintenance altogether as well as cleanup scripts.

**Comment by AirwavesMan** [comment]
All gear objects will be mantained on maintain now. Add with https://github.com/EpochModTeam/DayZ-Epoch/commit/43006760f80fefe24f4d8b70a0623fd73e07eca9
