### ISSUE TITLE
[Request]Border of Icons

### ISSUE THREAD

**Issue by Plurnstyle** [EpochModTeam/DayZ-Epoch#2040]
![mkx8x6wcog221](https://user-images.githubusercontent.com/36934905/66677549-415a2680-ec40-11e9-8cba-c23af1faeabd.jpg)
Bring border of icons again. Thanks you

**Comment by AirwavesMan** [comment]
This is in already.

https://github.com/EpochModTeam/DayZ-Epoch/blob/master/SQF/dayz_code/configVariables.sqf#L24

**Comment by Plurnstyle** [comment]
Borders for old icons

**Comment by Plurnstyle** [comment]
The new ones are scribbles and I want to use the old ones but they don't have borders anymore

**Comment by worldwidesorrow** [comment]
Option for bordered status icons added to 1.0.7: https://github.com/EpochModTeam/DayZ-Epoch/pull/2065
