### ISSUE TITLE
[Request]New Weapons, Skins e etc...

### ISSUE THREAD

**Issue by Plurnstyle** [EpochModTeam/DayZ-Epoch#2054]
AK74M pack  - http://www.armaholic.com/page.php?id=14197
AEK pack  - http://www.armaholic.com/page.php?id=15615
ACE Cheytacpack M200 Intervention  - http://www.armaholic.com/page.php?id=24553
Black Weapon Variant Mod  - http://www.armaholic.com/page.php?id=11312
Dagger Weapons  - http://www.armaholic.com/page.php?id=25486
FFAA Weapons - http://www.armaholic.com/page.php?id=6748

Coast Guard Helicopter and Air Rescue - http://www.armaholic.com/page.php?id=13947
Danish Defence Army Module - http://www.armaholic.com/page.php?id=15710
MH-6J Retex Pack  - http://www.armaholic.com/page.php?id=15621
UAZ 451 Pack - http://www.armaholic.com/page.php?id=17619

**Comment by AirwavesMan** [comment]
We already have evaluted all those addons. There are a lot more weapons and addons to come in the next weeks. We can only use addons where we got the permission to use.
