### ISSUE TITLE
script restriction #72 | Dayz Epoch 1.0.6.2 Server | HELP

### ISSUE THREAD

**Issue by Defolt163** [EpochModTeam/DayZ-Epoch#2067]
BankDialogUpdateAmounts = {
private ["
28.02.2020 11:18:34: Rostelecom (46.0.110.40:2304) 13ddf70b0a98e11da49bdf715506afdc - #72 " _input - [_x];
} forEach _badChars;

_input = parseNumber (toString (_input));
_input
};

BankDialogUpdateAmounts = {
private ["

HELP

**Comment by oiad** [comment]
This is not an epoch problem, please read up on battleye filters
https://opendayz.net/threads/a-guide-to-battleye-filters.21066/
