### ISSUE TITLE
Help Script WAI

### ISSUE THREAD

**Issue by squidmaeki** [EpochModTeam/DayZ-Epoch#2068]
28.02.2020 15:46:45: TaMuek (223.207.241.101:2304) e5f98cf5d8b0b0b1f55331bd32c8f6c2 - #15 "r_traders.sqf","scripts\radio\switch_on_off.sqf","dayz_code\compile\remote_message.sqf"];
	
	_file = -1;
	{
		if ((_x select 0 !"

Need help

**Comment by oiad** [comment]
This is not an epoch problem, please read up on battleye filters
https://opendayz.net/threads/a-guide-to-battleye-filters.21066/
