### ISSUE TITLE
Enhancement - General

### ISSUE THREAD

**Issue by nadal28** [EpochModTeam/DayZ-Epoch#2072]
The following actions list worked in 1.0.5.1:

- When you saw in the ground, for example, any type of food , instead of open the inventory, the player were able to directly save the food in the inventory. The same for belt items (crowbar, etool etc...)

- When eating the inventory should not be closed

- Disconnect to re-spawn with the mags filled should be fine. Realism is not always good. Let this like the old good days.

- Fire barrel should not need box of matches, the same as before: I want to ligh my barrel and dont waste my time buying box of matches...

Pretty sure I'm missing things. I think the way of epoch is just solving bugs instead of adding a lot of items used by no one. Let the game as it should be, PVP survival and stop adding unnecessary realism, there is a game called RUST out there.

Regards

**Comment by IsGoose** [comment]
I agree with these, for the dev's reading -these are personal opinions.

 The ammo count for mags is more of a ballache to me. And considering that you can put your mags in your backpack when logging out circumvents this feature anyways.

I agree that some actions shouldnt force close the inventory on usage,however its understandable if a change like this may be awkward to implement.

I'd like to add to what OP said, the current (and most likely future) meta of Epoch Servers isnt survival, but rather PVP.

Note that these suggestions are just that, suggestions and personal opinions. There is nothing stopping server owners from changing the few things OP mentioned.
Have a nice day.
Regards,
Goose

**Comment by AirwavesMan** [comment]
Ive added the fire barrel suggestion. The other things are ok as they are.
