### ISSUE TITLE
[REQUEST] Trader Humanity

### ISSUE THREAD

**Issue by Plurnstyle** [EpochModTeam/DayZ-Epoch#2075]
Today we have something like this

```hpp
class AKS_GOLD 
{
	type = "trade_weapons";
	buy[] = {-8,"ItemGoldBar10oz"};
	sell[] = {4,"ItemGoldBar10oz"};
};

class AKS_GOLD {
	type = "trade_weapons";
	buy[] = {2000,"worth"};
	sell[] = {1000,"worth"};
};
```

I suggest something new in the new version.

```hpp
class AKS_GOLD 
{
	type = "trade_weapons";
	buy[] = {-8,"ItemGoldBar10oz"};
	sell[] = {4,"ItemGoldBar10oz"};
	humanity[] = {"5000"};
};

class AKS_GOLD {
	type = "trade_weapons";
	buy[] = {2000,"worth"};
	sell[] = {1000,"worth"};
	humanity[] = {"5000"};
};
```

It would be interesting because it would add an absurd roleplay because you would not only need 5000 to buy this item, but the one the server owner chose.

I don't know if it makes sense in your minds but in mine it would be something much better than the current method. If the server owner chooses not to use something like this, leave it default (5,000 or -5,000).

THANKS!
Translated by Google.

**Comment by AirwavesMan** [comment]
You can add different humanity traders for yourself. There is no need to have on every single item a humanity value,
