### ISSUE TITLE
-

### ISSUE THREAD

**Issue by SmokeyBR** [EpochModTeam/DayZ-Epoch#2081]
Edit: We are aware of this problem but we have no solution for it at the moment. I hide the information in here just to be sure.

**Comment by SmokeyBR** [comment]
meanwhile ive been using a batch to monitor the log and look for the text "Server_monitor.sqf.is.exiting" if it finds it shuts the server down else it loops every 20 seconds, something like
```
findstr /m /r "Server\_monitor\.sqf.is.exiting" "C:\somePath\arma2oaserver.RPT"
if errorlevel 1 (
text not found ... loop
) ELSE (
text found ... killserver
)
```
i really think this information should be available for all to see, specially if there is no solution, anyways appreciate all the work still being put into dze, thanks

**Comment by ArmaWizard** [comment]
Server monitoring exiting does not directly create this problem.
