### ISSUE TITLE
Linux Server??

### ISSUE THREAD

**Issue by ballaual** [EpochModTeam/DayZ-Epoch#2084]
are there finally working linux files for a2? :/

**Comment by ArmaWizard** [comment]
no a2 in general has no linux support currently

**Comment by ballaual** [comment]
so there is actually no way to get epoch 1.0.6.4 running on a linux root machine? :(

**Comment by ArmaWizard** [comment]
No unless you downgrade arma 2 (which requires your clients to downgrade arma) and edit client/server files to be compliant with an older version of arma 2.

So no, not viable.

**Comment by MathijsNL** [comment]
This topic seems to have binaries for newer versions.
https://forums.bohemia.net/forums/topic/213193-arma-2-oa-update-164-build-144629-release-candidate-for-eol-end-of-life/

with linux version 1.64.144373 which looks promising.

Probably needs some work on the writer though (no hive on Linux).

**Comment by IsGoose** [comment]
Epoch doesnt currently support Linux Hosts, atleast in the aspect of HiveExt since there ie no HiveExt.so shipped with epoch. Though an Implementation of one would not be particularly challenging

**Comment by ArmaWizard** [comment]
> This topic seems to have binaries for newer versions.
> https://forums.bohemia.net/forums/topic/213193-arma-2-oa-update-164-build-144629-release-candidate-for-eol-end-of-life/
> 
> with linux version 1.64.144373 which looks promising.
> 
> Probably needs some work on the writer though (no hive on Linux).

The linux builds do not function. Nor is there any plan for bohemia to make them work.
Note last reply ever about linux server:

![image](https://user-images.githubusercontent.com/6765262/104168796-e6911b00-53fe-11eb-887c-3736f0eebf8d.png)
