### ISSUE TITLE
UFO in Trader City Lenzburg

### ISSUE THREAD

**Issue by dreamforceinc** [EpochModTeam/DayZ-Epoch#2121]
![arma2oa 2021-04-01 10-59-52](https://user-images.githubusercontent.com/25371848/113263356-54e8c980-92da-11eb-94bd-088d4f9c73c0.png)
![arma2oa 2021-04-01 11-00-00_cr](https://user-images.githubusercontent.com/25371848/113263375-5b774100-92da-11eb-9ab1-5e7a982208e3.png)
![arma2oa 2021-04-01 11-00-13_cr](https://user-images.githubusercontent.com/25371848/113263385-5f0ac800-92da-11eb-8f15-0f448862861c.png)

**Comment by AirwavesMan** [comment]
Fixed with https://github.com/EpochModTeam/DayZ-Epoch/commit/70d3e0117d7be14e7f12e2b0849192c066549ce1
