### ISSUE TITLE
Epoch 1.0.7 Pre-Release

### ISSUE THREAD

**Issue by AirwavesMan** [EpochModTeam/DayZ-Epoch#2122]
Ladies and Gentlemen, this is the Epoch 1.0.7 Pre-Release with signed pbos and the needed server key. This will be in test until the 15th of April to make sure everything works correctly.

**Joining with the DayZ Launcher**

1. Download and install 7-zip from this website: https://7-zip.de/download.html
2. Download the Epoch 1.0.7 Client Files from google drive: https://drive.google.com/drive/folders/1Xx0wq8QJFG4AqeXquxMQADm8y73FYeYO
3. If you have finished the download, unpack the Epoch 1.0.7 Client Files. You need at least 7,4 GB of disk space.
4. Go into the folder where you have installed all your of Arma 2 OA DayZ mods. It depends on where the DayZ Launcher has set the path.
5. Once you found the folder with your mods rename @DayZ_Epoch to @DayZ_Epoch_old.
6. Copy and paste the downloaded and unpacked folder from 3. into the mods folder where you have renamed the Epoch Mod. Keep in mind you need at least 7,4 GB of disk space.
7. There should be a folder with the name @DayZ_Epoch_old and @DayZ_Epoch now.
8. Click on @DayZ_Epoch and check if there is a sub folder called addons. @DayZ_Epoch\addons.
9. If there is another folder called @DayZ_Epoch copy everything from this folder into the root folder called @DayZ_Epoch. So it looks like: that @DayZ_Epoch\addons and not: @DayZ_Epoch\@DayZ_Epoch\addons.
10. You are ready to join an Epoch 1.0.7 Server now. Open the DayZ Launcher and join 94.130.68.169 - Offical DayZ Epoch 1.0.7 Pre-Release Version
11. You will get a message that Epoch needs validating/updating. Click ok and ignore it. You can join the Test Server now.
12. If you want to join any other Epoch non 1.0.7 server, just rename @DayZ_Epoch_old back to @DayZ_Epoch

**For Server Admins: You have to update to the new server files that coming with this Pre-Release update.**

1. Download and install 7-zip from this website: https://7-zip.de/download.html
2. Download the Epoch 1.0.7 Server Files from google drive: https://drive.google.com/drive/folders/1gHNE4VBCeYXi0P_hosAI8k-49v15WNdr
3. Take the DayZEpoch107.bikey from the  Server Files keys folder and put them into your server keys folder.
4. Also set verifySignatures = 2; in your config.cfg to activate the signatures check.

**How to test:**

1. Do not use any third party scripts or tools. Do not use infistar as an admin tool. Use this testkit: https://github.com/worldwidesorrow/TestKit
2. Enable -showscripterrors in the DayZ Launcher and never ever use -nologs for testing.
3. If you have bugs and problems on testing always provide logs. Server(if you are the admin) and Client Logs. You can find the Client Logs under C:\Users\YourUsername\AppData\Local\ArmA 2 OA 
4. It is possbile that the folder is hidden in windows. You can make it visible: https://support.microsoft.com/en-us/help/4028316/windows-view-hidden-files-and-folders-in-windows-10
5. Do not post the logs directly, use pastebin.com, google drive, or something like that and add the link.

Report all bugs under this topic.

**Comment by ZizionarD** [comment]
What do you have left in your plans?

**Comment by looter809** [comment]
> What do you have left in your plans?

The fact that it's officially in pre-release makes me think there is nothing left in his current plans. I think it's just the final testing phase.

**Comment by AirwavesMan** [comment]
> 
> 
> > What do you have left in your plans?
> 
> The fact that it's officially in pre-release makes me think there is nothing left in his current plans. I think it's just the final testing phase.

Indeed there is nothing left on my list for the current version.

**Comment by cyberdemonv2** [comment]
Mod.cpp still showing Epoch1.0.6.2 not 1.0.7 , this intentional until final?

**Comment by AirwavesMan** [comment]
> 
> 
> Mod.cpp still showing Epoch1.0.6.2 not 1.0.7 , this intentional until final?

Yes, until the official release. From this point you can no longer launch or find any Epoch 1.0.7 server with the DayZ Launcher until Epoch 1.0.7 got uploaded there.

**Comment by ZizionarD** [comment]
Hello! Found a bug, if in the file if in the file fn_selfActions.sqf uncomment the block:
```
//Towing with tow truck
	if(_typeOfCursorTarget == "TOW_DZE") then {
		if (s_player_towing < 0) then {
			if(!(_cursorTarget getVariable ["DZEinTow", false])) then {
				s_player_towing = player addAction [localize "STR_EPOCH_ACTIONS_ATTACH" "\z\addons\dayz_code\actions\tow_AttachStraps.sqf",_cursorTarget, 0, false, true];
			} else {
				s_player_towing = player addAction [localize "STR_EPOCH_ACTIONS_DETACH", "\z\addons\dayz_code\actions\tow_DetachStraps.sqf",_cursorTarget, 0, false, true];
			};
		};
	} else {
		player removeAction s_player_towing;
		s_player_towing = -1;
	};
```
then the left menu stops working, for traders, for the 30m Plot

**Comment by AirwavesMan** [comment]
This code block is not functional and should no be uncomment.

**Comment by ZizionarD** [comment]
> This code block is not functional and should no be uncomment.

Will this be fixed or will you have to fix it yourself?

**Comment by AirwavesMan** [comment]
As I said tow is not functional since epoch has no longer the tow_dze truck. So if you want to use it, you have edit it by yourself.

**Comment by ZizionarD** [comment]
> As I said tow is not functional since epoch has no longer the tow_dze truck. So if you want to use it, you have edit it by yourself.

So, will it be possible to tow other equipment?

**Comment by AirwavesMan** [comment]
No

**Comment by looter809** [comment]
I'm probably stupid, but I can't get my RC4 version to work with the new pre-release version. I have tried using the default dayz_server  and mp misssion, as well as triple checking I'm using the right DayZ_Epoch mod folder.

Link to my server arma2oaserver.rpt: https://pastebin.com/QktZ2DWR
Link to client side ArmA2OA.rpt: https://pastebin.com/CfZaR59H

Also, is there a way for me to read the minidump files generated to try to make more sense of it?

**Comment by AirwavesMan** [comment]
You only need Epoch 1.0.7 Pre-Release. Delete your old folder @DayZ_Epoch with RC4 and download the new one. You have to use the new one with signed pbos.

**Comment by looter809** [comment]
> You only need Epoch 1.0.7 Pre-Release. Delete your old folder @DayZ_Epoch with RC4 and download the new one. You have to use the new one with signed pbos.

I've removed the old mod folder and moved in the new one.

**Comment by AirwavesMan** [comment]
Ah I see, currenly there is a bug in chernaurs_winter that why you get a chrash everytime. The bug got fixed today but it is just not in the Pre-Release. So all what you can do is waiting for the release now. Or you are using the normal chernaurs map.

**Comment by looter809** [comment]
Yeah I'm using the chernarus winter. It worked before, was there a change made?

**Comment by AirwavesMan** [comment]
Yes but Ive reverted the change because of the crashes.

**Comment by looter809** [comment]
Ah that explains it. Is that in the mod folder?

**Comment by AirwavesMan** [comment]
It is, you could use the old chernaurs_winter.pbo but you have to turn of the signature check then.

**Comment by looter809** [comment]
Okay gotcha. I may just switch back to normal chernarus. Thank you for the help and fast reply.

**Comment by ZizionarD** [comment]
Hello! How can I set up the water_fill.sqf file to prevent infection from drinking water?

**Comment by IsGoose** [comment]
> Hello! How can I set up the water_fill.sqf file to prevent infection from drinking water?

Set the dayz_infectiousWaterholes = false after configVariables.sqf has been called

**Comment by dreamforceinc** [comment]
![arma2oa 2021-04-09 13-07-51](https://user-images.githubusercontent.com/25371848/114168254-ad524380-9938-11eb-9a86-acf0481cfbb5.png)

**Comment by RedLink-kam** [comment]
Very strange. I can't find "Mi-8(Ambulance)" in github files.

**Comment by dreamforceinc** [comment]
I think, this string from original arma2 stringtable.xml.

**Comment by AirwavesMan** [comment]
Yes it comes from the original arma 2. But we stay with the Mi17 for now.

**Comment by RedLink-kam** [comment]
But in Epoch uses strintables from Epoch mod.
I can find this line in google only here "https://github.com/howiehu/vme_clp_a2/blob/master/AddOns/vme_clp_l/stringtable.xml" (line 1952)

**Comment by AirwavesMan** [comment]
No this is incorrect. Epoch just updates the stringtable from Arma 2. You can find it if you unpack the Arma 2 addons.

**Comment by RedLink-kam** [comment]
Yes. found it.
in a file stringtables.xml from language.pbo (line 44992)
Can you added correct names in epoch sringtables?

**Comment by AirwavesMan** [comment]
Acutally no. It will stay as it is since all Mis have Mi17 classnames. This confuses more as it helps. We can think about to update this later if it is really needed.
