### ISSUE TITLE
Epoch Group system settings not working

### ISSUE THREAD

**Issue by VoltanDan** [EpochModTeam/DayZ-Epoch#2139]
I am using Epoch 1.0.7 with Podagorsk map and Salival's mod pack, and changing the dayz_markGroup and dayz_markSelf makes no visible changes: 

`	// Group System
	dayz_markGroup = 2; // Players can see their group members on the map 0=never, 1=always, 2=With GPS only
	dayz_markSelf = 2; // Players can see their own position on the map 0=never, 1=always, 2=With GPS only
	dayz_markBody = 1; // Players can see their corpse position on the map 0=never, 1=always, 2=With GPS only
	dayz_requireRadio = true; // Require players to have a radio on their toolbelt to create a group, be in a group and receive invites.`

For instance, I have dayz_markGroup set to 2, but players can see themselves on the map with just a map and no GPS.

Already discussed this with Airwaves, and most likely an issue inside the group system script.

**Comment by AirwavesMan** [comment]
Ive tested everything and all works as intented.
