### ISSUE TITLE
Old style Double Garage Doors bug

### ISSUE THREAD

**Issue by vecuccio** [EpochModTeam/DayZ-Epoch#2141]
I am a player, not a server owner. 

I built an old style double garage door (because there is no Wiki or Googleable information on how to craft the 1.0.7 double doors, or any of the new stuff)
The beam of the inverted door is under the soil as it should be, the opened door opens completely under the soil, as it should do.

Yet the bottom door puts up an invisible barrier preventing any vehicle from entering. The player can vault over the barrier, but a vehicle can't enter or exit. It is caused by the bottom door. Because if you close it, you can then walk right up to the door.

https://imgur.com/a/WMnV8aT

**Comment by AirwavesMan** [comment]
There is a new cinder gate and two more cinder garage buildings so you do not have to invert those any longer. This is not a bug it is a side effect of the bigger building collision.
