### ISSUE TITLE
Add missing syntax in file server_swapObject.sqf

### ISSUE THREAD

**Issue by TheFirstNoob** [EpochModTeam/DayZ-Epoch#2142]
https://github.com/EpochModTeam/DayZ-Epoch/blob/1db1051a8a89b00a70f005ed56558f0181093800/SQF/dayz_server/compile/server_swapObject.sqf#L95

Missing "," Where TentStorage4 and DomeTentStorage0

**Comment by AirwavesMan** [comment]
Fixed with https://github.com/EpochModTeam/DayZ-Epoch/commit/c245e6d3c645e903cf081f07355ae103a34aeb5f
