### ISSUE TITLE
Dayz server file looses digital signature 

### ISSUE THREAD

**Issue by chopperprop** [EpochModTeam/DayZ-Epoch#2149]

**Comment by chopperprop** [comment]
So when I open scripts.pbo , game , then pull the constants.c file out it gives me error 
![image](https://user-images.githubusercontent.com/37424007/124204314-6cd01500-daa4-11eb-9dda-698446d7d1ac.jpg)
Then if it make the changes and put the file back in the server will not start

**Comment by chopperprop** [comment]
I have the original digital signature but PBO manager will not allow me to type it in it only allows me to generate a new signature however the server still errors out

**Comment by chopperprop** [comment]
![Uploading image.jpg…]()

**Comment by AirwavesMan** [comment]
Please join the epoch discord for help. This is not a problem of the epoch mod.
