### ISSUE TITLE
White/Black/Grey screen freeze on Return to Lobby or Death

### ISSUE THREAD

**Issue by MollyXVI** [EpochModTeam/DayZ-Epoch#2150]
Mod(s): **Epoch 1.0.7**
Map: **Chernarus**
Anti Hack: **infiSTAR**
Server host: **GTXGaming**
Scripts: **Wicked AI (WAI)** & **DayZMissionSystem (DZMS)**
Server LOG: [arma2oaserver.RPT](https://paste.md-5.net/uxuwujajuj.http)
Client LOG: [ArmA2OA.RPT](https://paste.md-5.net/esegefebaq.http)

When i die or log out from the server, instead of going to the lobby, i get a black, white or grey screen and the only thing i can do is Alt+F4.

**Comment by AirwavesMan** [comment]
This sounds like a normal infistar problem. infiSTAR is not compatible with Epoch 1.0.7. If you remove it your problem should be fixed. Use this Admin Tool and not infiSTAR: https://epochmod.com/forum/topic/47272-epoch-antihack-admin-tools/
