### ISSUE TITLE
Correct some weights

### ISSUE THREAD

**Issue by TheFirstNoob** [EpochModTeam/DayZ-Epoch#2169]
Greetings.
I suggest slightly changing the weight on some weapons because some numbers are not logical and not balanced.
I'm not asking you to do as in reality. Just need to fix some misunderstandings with some things.
All changes are up to you. Whether they are needed or not.

Groza 1 and 9 GL/Sniper:
- Groza1_DZ : 5.6kg
- Groza1_Sniper_DZ : 9.8kg (4.2kg optic?)
- Groza9_DZ : 5.6kg
- Groza9_GL_DZ : 5.6kg (0kg GP25? On AK Series is +0.01-0.5kg diff) (Real GP have 1.5kg)
- Groza9_Sniper_DZ : 9.8kg (4.2kg optic?)
- Groza9_GL_Sniper_DZ 9.8kg (4.2kg optic and 0kg GP25?)

All Mk16-17 have 5.6kg with any modules and variation but the modules themselves have weight.
All CTAR-21 have 5.4kg with any modules and variation but the modules themselves have weight.

AS Val and Vintorez:
- VAL_DZ : 6kg (Real 2.6kg)
- VSS_vintorez_DZE : 5kg - (Sniper variation have small weight?) (Real 2.6kg)
When compared with AK PSO SD we have 2.75kg.
VAL and Vintorez not profitable.

Magpull PDR:
- PDR_DZ : 5.1kg w\o modules
- PDR_CCO_DZ and PDR_Holo_DZ : 3.6kg (With modules easy?)

Mosin:
- Mosin_DZ : 4kg
- Mosin_FL_DZ : 4.2kg
- Mosin_MFL_DZ : 7.2kg (3.2kg MFL? On other weapons MFL have 0-0.8kg diff)
BELT and PU variation too.
I think need set FL and MFL variation same weight cause in game we change only color flash...

PKM and PKP Pecheneg
Both have 9kg but Pecheneg have optic and more stability shooting. Think admins can set more currency for Pecheneg but i think need +-1-2kg to change weight.

Barret MRAD:
- Barrett_MRAD_Iron_DZ : 12.6kg
- Barrett_MRAD_CCO_DZ : 12.8kg
- Barrett_MRAD_Sniper_DZ : 12.4kg (With optic easy?)

MSR XM2010:
- MSR_DZ : 3.2kg
- MSR_SD_DZ : 10.6kg (7.4 kg silencer?)
- MSR_NV_DZ : 10.8kg (7.6 kg optic?)
- MSR_NV_SD_DZ : 11kg (^)

- XM2010_DZ : 3.2kg
- XM2010_SD_DZ : 12kg (8.8 kg silencer?)
- XM2010_NV_DZ : 12.2kg (9 kg optic?)
- XM2010_NV_SD_DZ : 12.4kg (^)

RSASS:
- RSASS_DZ : 3.2kg
- RSASS_SD_DZ : 3.1kg (With silencer easy?)

This is all that I could notice and consider significant.
Perhaps I missed something.
Thx for all ^_^

**Comment by AirwavesMan** [comment]
Please be so kind an make a pull request with the changes or send me the files on discord.

**Comment by TheFirstNoob** [comment]
if u want i can try to correct all weights on items but i need some time for this.

**Comment by AirwavesMan** [comment]
Yes please

**Comment by TheFirstNoob** [comment]
Hi, can u give me u discord for send files. I almost finish edit all weight files.

**Comment by AirwavesMan** [comment]
https://discord.com/invite/0k4ynDDCsnMzkxk7 join and discord and message me.
