### ISSUE TITLE
Missing strings

### ISSUE THREAD

**Issue by dreamforceinc** [EpochModTeam/DayZ-Epoch#2175]
https://github.com/EpochModTeam/DayZ-Epoch/blob/e92287cbb2e8d95c999fac416b6b47d90bd57146/SQF/dayz_code/Configs/CfgMagazines/Buildings/Sandbag.hpp#L68

"$STR_EQUIP_DESC_21" is missing in the Stringtable.xml

**Comment by dreamforceinc** [comment]
But it present in 1.0.7 release

**Comment by AirwavesMan** [comment]
Thx, fixed with https://github.com/EpochModTeam/DayZ-Epoch/commit/bac89754fb2813e4d0ef998a42dc3265a1e87c0f
