### ISSUE TITLE
Spawn selector like DayZ

### ISSUE THREAD

**Issue by FramedYannick** [EpochModTeam/DayZ-Epoch#973]
I have fixed the spawn selector script like the one for dayz, I will upload the code later this week with some tweeks added as well.

Needed files to edit:
server_playersetup.sqf
player.fsm
description.ext
include extra file:
RscDisplaySpawnSelecter.hpp
(not standard version, some classes were missing)

**Comment by ebaydayz** [comment]
The 1.8.7 Chernarus spawn selector is now included for 1.0.6. 

If someone wants to make similar town pictures for the other maps check out:
SQF\dayz_code\gui\spawn\spawn_balota/berezino/etc.paa

I am not skilled enough with GIMP/Photoshop to make anything that pretty. But if someone wants to submit six town pictures for another map, feel free to make a pull request or open an issue with them. At that point it would be no problem to add the code for it.
