### ISSUE TITLE
Waves for storms

### ISSUE THREAD

**Issue by FramedYannick** [EpochModTeam/DayZ-Epoch#974]
By including this addon in your addons folder and in the mission.sqm file as addon, when bad weather and stormy, there will be huge waves on the chernarus ocean, its a nice feature to have.

https://dl.dropboxusercontent.com/u/219565667/Waves.pbo

**Comment by ebaydayz** [comment]
Added. Doesn't seem to affect FPS. https://github.com/EpochModTeam/DayZ-Epoch/commit/9876819da55ed6e83cb25298deff38f9231d9827

![2016-02-20_00008](https://cloud.githubusercontent.com/assets/7761693/13200014/fb41d6a4-d805-11e5-9491-79e1be9911ea.jpg)
